### ISSUE TITLE
Update MFE deployer configuration with recent variable additions

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#1]
One limitation of the current MFE deployer configuration in MFE_ENVIRONMENT_DEFAULT is that whenever new environment variables are added to MFEs, they must manually be added here too.

https://github.com/edx/configuration/blob/master/playbooks/roles/mfe/defaults/main.yml#L89

Recently some improvements have been made in the MFEs to allow for configurable logos and favicons, as shown here:

https://github.com/edx/frontend-template-application/blob/master/.env.development#L12-L15

The four variables highlighted there will need to be added to the MFE deployer configuration.

```
LOGO_URL=https://edx-cdn.org/v3/default/logo.svg
LOGO_TRADEMARK_URL=https://edx-cdn.org/v3/default/logo-trademark.svg
LOGO_WHITE_URL=https://edx-cdn.org/v3/default/logo-white.svg
FAVICON_URL=https://edx-cdn.org/v3/default/favicon.ico
```

Note that the assets at those four URLs are generic default images (not edx.org branded), so they make good default values. 

In the long term, we should figure out how we can either 1) remember to keep this list up to date, or 2) modify our configuration mechanism so that it doesn't rely on a comprehensive, hard-coded list of variable names to pass through.  

https://openedx.atlassian.net/jira/software/projects/BTR/boards/641?selectedIssue=BTR-47

**Comment by ericfab179** [comment]
Hi @BbrSofiane I would like to help solving this issue. A colleague at [edunext](https://www.edunext.co/) worked in the development of the MFE deployer and he can guide me through the process of fixing this.

**Comment by BbrSofiane** [comment]
Thanks @ericfab179!

**Comment by ericfab179** [comment]
@BbrSofiane I was checking the issue and it seems that the required variables were added the same day the JIRA ticket was created in this commit https://github.com/edx/configuration/commit/71ec3fa4343cc6ca38282064b37a292990d6b704. At least with those changes the mfe_deployer has already common default values for the new settings for all the MFEs. If one of those settings needs to be overridden for an specific MFE, the variable `env_extra` should be used (https://github.com/edx/configuration/blob/862f6240ee8775522387315adaac7b9411cfa1bd/playbooks/roles/mfe_deployer/tasks/main.yml#L16).

Regarding @davidjoy 's conecern about "how do we keep this up to date in the long term?", we need to consider that edx/configuration will be deprecated very soon, so I consider that our efforts must be focused on how do we want to keep this up to date when using Tutor. Based on the current Tutor approach to handle each MFE as a plugin repo, we may be able to set some kind of CI (maybe using GithubActions) that synchronises the .env files from the different MFE repositories with the .env values of the matching Tutor MFE plugin repositories. @regisb Do you think this is a good idea ? Or how do you think that we can avoid doing the manual updates ?

**Comment by regisb** [comment]
> Based on the current Tutor approach to handle each MFE as a plugin repo, we may be able to set some kind of CI (maybe using GithubActions) that synchronises the .env files from the different MFE repositories with the .env values of the matching Tutor MFE plugin repositories

I am almost certainly going to go with the following approach: shared common MFE settings will be stored in a base MFE plugin ("tutor-mfe") and actual MFE will ship with only the settings that they need to override. Based on my (admittedly limited) experience with the Gradebook, there should be very few MFE-specific settings.
