### ISSUE TITLE
The LMS register page includes incorrect links to honor code/privacy policy pages

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#10]
![register](https://user-images.githubusercontent.com/13796098/107240530-ed24a980-6a21-11eb-9c0c-a9a1795dfcc3.png)

In the default theme, there might not be any honor code page, or even a privacy policy. In that case, the register form should not link there.

Also, we should be able to remove the “Support education research by providing additional information” checkbox (and actually the entire feature).

https://openedx.atlassian.net/browse/BTR-33

**Comment by BbrSofiane** [comment]
@regisb any updatees on this?

**Comment by regisb** [comment]
This can be resolved by defining the following settings in the LMS:

```
REGISTRATION_EXTRA_FIELDS["terms_of_service"] = "required"
REGISTRATION_EXTRA_FIELDS["honor_code"] = "hidden"
```

Setting these values, we obtain the following registration page (https://demo.openedx.overhang.io/register):

![register](https://user-images.githubusercontent.com/44319/110311690-71a81f00-8004-11eb-89d8-6351cd446403.png)

Unfortunately, the `REGISTRATION_EXTRA_FIELDS` setting is not yet documented: https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/

I suggest we document it to close this issue.

**Comment by regisb** [comment]
I opened a PR to address this: https://github.com/edx/edx-platform/pull/27136

**Comment by pdpinch** [comment]
Reviewed, merged, closed.
