### ISSUE TITLE
Bulk course emails are rejected by email server because of an invalid "from" address

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#102]
See this conversation: https://discuss.overhang.io/t/sending-bulk-email-triggers-smtprecipientsrefused-error/1923/10

When sending bulk course emails, by default the "from" address is built as follows: `f"{courseid}-{bulk_email_from}"`. ([source](https://github.com/edx/edx-platform/blob/85065cd95a3733406310539ada36f934327b03f5/lms/djangoapps/bulk_email/tasks.py#L413)) In many cases, sender verification will fail for this address because it will not exist on the email server. 

This is all the more surprising for the user, as they have properly defined the `BULK_EMAIL_DEFAULT_FROM_EMAIL` setting. A way to bypass this strange behaviour is to enable the `EMAIL_USE_DEFAULT_FROM_FOR_BULK` toggle -- but it's counter intuitive that we need to manually enable a toggle to use the "default" behaviour.

Thus, I propose the following changes:

1. Switch the `EMAIL_USE_DEFAULT_FROM_FOR_BULK` toggle default to True (i.e: rename `EMAIL_USE_DEFAULT_FROM_FOR_BULK` to `EMAIL_USE_COURSE_ID_FROM_FOR_BULK`).
2. When ~~this toggle is True~~ (EDIT: clarity) `EMAIL_USE_COURSE_ID_FROM_FOR_BULK` is False, the “from” address should default to `settings.DEFAULT_FROM_EMAIL` only if `settings.BULK_EMAIL_DEFAULT_FROM_EMAIL` is undefined. In other words:

```
if is_email_use_default_from_bulk_enabled():
    from_addr = settings.BULK_EMAIL_DEFAULT_FROM_EMAIL or settings.DEFAULT_FROM_EMAIL
else:
    ...
```

**Comment by Drakko25** [comment]
Hey @regisb I am looking at this issue. I've create the PR by now is a draft to check if the CI passes https://github.com/edx/edx-platform/pull/29001. Please let me know if any issues. Regards.

**Comment by BbrSofiane** [comment]
Needs to be merged in maple.master

**Comment by nizarmah** [comment]
@BbrSofiane I'd like to merge this into maple.master. cc @regisb

**Comment by nizarmah** [comment]
@regisb @BbrSofiane I created the backport PR to the maple master branch. Would either of you have time to review the pull request? Otherwise, do you have an idea who would be best to reach out to?

**Comment by regisb** [comment]
I realize that this issue still affects Lilac, but since it is resolved in Maple I'm closing this.

**Comment by nizarmah** [comment]
@regisb would you like me to create a backport pull request to lilac master, or is that not going to be necessary?

**Comment by regisb** [comment]
If you have time, that would be great but not strictly necessary, I guess, since we are 4 days away from the release.

**Comment by nizarmah** [comment]
@regisb the backport PR to lilac is ready for your review 😃
