### ISSUE TITLE
edx-platform triggers too many deprecation warnings

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#105]
[Status of remaining warnings spreadsheet](https://docs.google.com/spreadsheets/d/1ijUV8vgnVSZJ3goBos5H_ytaSxCcFBHKfkxZFAbn9js/edit?usp=sharing)

Running any command in edx-platform triggers a lot of deprecation warnings of the following types:

1. (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0. HINT: Use BooleanField(null=True) instead.
2. RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext()
3. RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path()

In Tutor, we should either mute these warnings or resolve them (the latter solution is the preferred one, of course).

**Comment by regisb** [comment]
After getting rid of `RemovedInDjango40Warning` and `RemovedInDjango41Warning`, we are left with the following warnings:

```
2021-11-25 13:45:40,541 WARNING 14 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of
 importlib; see the module's documentation for alternative uses
  import imp

2021-11-25 13:45:40,606 WARNING 14 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1: DeprecationWarnin
g: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, MutableMapping

2021-11-25 13:45:42,133 WARNING 14 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/edx-platform/openedx/core/lib/api/view_utils.py:5: DeprecationWarning: Using or importing the ABCs from 'collecti
ons' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Sequence  # lint-amnesty, pylint: disable=no-name-in-module, deprecated-class

2021-11-25 13:45:42,515 WARNING 14 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/edx-platform/openedx/core/types/admin.py:49: DeprecationWarning: Django 3.2+ available: the _admin_display method
 and the AdminMethodclass should be removed from openedx.core.types
  warnings.warn(

System check identified some issues:

WARNINGS:
certificates.CertificateGenerationCourseSetting.include_hours_of_effort: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
consent.DataSharingConsent.granted: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
consent.HistoricalDataSharingConsent.granted: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
content_type_gating.ContentTypeGatingConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
content_type_gating.ContentTypeGatingConfig.studio_override_enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_date_signals.SelfPacedRelativeDatesConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_duration_limits.CourseDurationLimitConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_home_api.DisableProgressPageStackedConfig.disabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_home_api.DisableProgressPageStackedConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_overviews.CourseOverview.has_highlights: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
course_overviews.HistoricalCourseOverview.has_highlights: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
discounts.DiscountPercentageConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
discounts.DiscountRestrictionConfig.disabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
discounts.DiscountRestrictionConfig.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
discussions.ProviderFilter.enabled: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
```

**Comment by ichdamola** [comment]
Hello @regisb, I will like to contribute to this project by taking up this issue as my first. Could kindly share with me the link to the contributor's guide or/and any related doc?

**Comment by regisb** [comment]
I'll take a stab at resolving this one:

```
certificates.CertificateGenerationCourseSetting.include_hours_of_effort: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
```

@ichdamola we have not forgotten about you ;) someone will reach out to you very soon.

**Comment by nizarmah** [comment]
Hello @regisb! I'd like to work on one of these deprecation warnings.

**Comment by ziafazal** [comment]
I'd like to contribute in fixing one of these warnings.

**Comment by sarina** [comment]
Hi @ichdamola and welcome! Sorry for the late reply. We'd love to have your help. [This page is helpful but may be outdated](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1682211674/Open+edX+Platform+contributor+s+guide), it's a good place to start. Feel free to reach out to me (`@sarina`) on the [Open edX Slack](http://openedx-slack-invite.herokuapp.com/) and I am happy to get you pointed at all the right places.

**Comment by sarina** [comment]
[Here is a spreadsheet to track progress on this ticket](https://docs.google.com/spreadsheets/d/1ijUV8vgnVSZJ3goBos5H_ytaSxCcFBHKfkxZFAbn9js/edit?usp=sharing), please keep it updated.

**Comment by regisb** [comment]
Unless I'm mistaken, most of the changes that are required here were already applied to the master branch, thanks to this PR: https://github.com/edx/edx-platform/pull/28851/
Apparently, all we would need to do is to apply Django Codemod: https://django-codemod.readthedocs.io/en/stable/index.html
I'm not sure if we should simply merge that (relatively large) PR or run django codemod on the open-release/maple.master branch.

**Comment by nizarmah** [comment]
@regisb I'm not sure which approach would be best to follow here. If nothing was addressed in a different pull request, it would make sense to simply merge.

Otherwise, would it be possible to cherry-pick and then run django codemod in case something was addressed in a different pull request (or not addressed)?

**Comment by regisb** [comment]
I suggest the following approach:

- Cherry-pick f26bd63c732cf482f368ed5c2e893dc5925ca08d on open-release/maple.master (I just verified that there is no conflict)
- Check if it resolves all warnings
- If not, apply extra fixes (maybe by running django-codemod or cherry-picking another commit)
- If yes, close this issue

**Comment by cmltaWt0** [comment]
I've just checked the commit on top of  `open-release/maple.beta1`:
1. It fixes some deprecations but not all.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/877401/145612682-70a652d2-d311-4e72-8463-7518c0e72d55.png">

2. We have to cherry-pick from this PR too https://github.com/edx/edx-platform/pull/28854
3. Since the title of the first is `BOM-2781: Django codemods on LMS (1)` and my finding is `BOM-2781: Django codemods on LMS (4)` I believe there are also (2) and (3) somewhere to find and cherry-pick too.
4. A lot of warnings are from xblocks or external dependencies:
```
2021-12-10 16:52:47,417 WARNING 1 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/edx_sga/sga.py:145: RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext().
  help=_("When the annotated file was uploaded")
2021-12-10 16:52:47,243 WARNING 1 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/openassessment/xblock/openassesment_template_mixin.py:20: RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext().
  "staff-assessment": _("Staff Assessment Only"),
```

**Comment by ichdamola** [comment]
> Hi @ichdamola and welcome! Sorry for the late reply. We'd love to have your help. [This page is helpful but may be outdated](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1682211674/Open+edX+Platform+contributor+s+guide), it's a good place to start. Feel free to reach out to me (`@sarina`) on the [Open edX Slack](http://openedx-slack-invite.herokuapp.com/) and I am happy to get you pointed at all the right places.

Hello @sarina, thank you for this response.

**Comment by ziafazal** [comment]
@regisb @cmltaWt0 we need to pick BOM-2781 related [commits](https://github.com/edx/edx-platform/pulls?q=is%3Apr+is%3Amerged+BOM-2781). I have pick LMS 1 to LMS 4 in these PRs

https://github.com/edx/edx-platform/pull/29555
https://github.com/edx/edx-platform/pull/29558
https://github.com/edx/edx-platform/pull/29559
https://github.com/edx/edx-platform/pull/29560

We need to pick the remaing six PRs too. Let me know if anyone else can help with those otherwise I'll pick them too.

**Comment by cmltaWt0** [comment]
@ziafazal Great catch!
I will do BOM-2781: New codemods on OpenedX (1)(2)(3)(4)

**Comment by cmltaWt0** [comment]
@ziafazal Added PRs for all six.

**Comment by cmltaWt0** [comment]
@regisb Let's do some review on it and invoke bot merge.

**Comment by nizarmah** [comment]
Wow that was fast. Nice work on this and thanks for opening the pull requests! 🤗 

I'm assuming nothing else is left other than reviews and merging. I would've offered to review, but unfortunately that's not going to be possible because I don't have any core committer permissions, so my review wouldn't really count.

**Comment by sarina** [comment]
@nizarmah for what it's worth, I think your review does count! As a CC, when someone already reviews a PR it often makes my review take less time. It also helps to establish your part in the community, as a good stepping stone for becoming a coding core contributor.

**Comment by nizarmah** [comment]
@sarina, sounds reasonable. Thank you! 

I've reviewed all pull requests, they're ready for a CC's review 👍🏼

**Comment by regisb** [comment]
I've merged @ziafazal's PRs, waiting for @cmltaWt0 to resolve the questions raised by @nizarmah. Thanks a lot, both for the PRs and the reviews!

**Comment by cmltaWt0** [comment]
@regisb both `OpenedX 1` and `OpenedX 2` PRs have been updated based on comments from @nizarmah

**Comment by cmltaWt0** [comment]
@regisb could you merge remaining PRs (just for me to not merge my own PRs)?

**Comment by nizarmah** [comment]
@regisb I believe this issue can be closed. I don't have the privileges to do so, though. 
cc @cmltaWt0 @ziafazal

**Comment by regisb** [comment]
Nice job everyone :)
