### ISSUE TITLE
Django 3.2.9

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#106]
This security release should be applied to Maple.  In the past I have done it with ad-hoc manual/automated steps.  How do we want to do it now?

**Comment by regisb** [comment]
It would be awesome if we could have a bot, somewhat similar to github's own [dependabot](https://github.com/dependabot), which would take care of automatically opening pull requests to upgrade Django dependencies. Has anyone ever done something similar?

**Comment by nedbat** [comment]
I haven't seen something like that, but I also haven't looked.  This is different than the usual "dependabot-like" activity, because it is only for a single dependency.

**Comment by BbrSofiane** [comment]
https://discuss.openedx.org/t/django-2-2-19-security-update/4305

**Comment by nedbat** [comment]
Today we decided that @blarghmatey will look into using Dependabot to upgrade only Django, only on the open-release/* branches.  We won't apply this fix manually (yet).

**Comment by nedbat** [comment]
This is now obsolete, since I just applied 3.2.10.
