### ISSUE TITLE
Support for Transifex in the frontend-app-gradebook MFE

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#107]
This follows a conversation that happened previously on Slack: https://app.slack.com/client/T02SNA1T6/C02BMP2RD5Y/thread/C02BMP2RD5Y-1636646986.036900

It looks like all the scaffolding is in place to handle i18n strings from the Gradebook MFE in Transifex. From my perspective, all that is missing is to create the "frontend-app-gradebook" resource in the edx-platform project, such that the following url does not return a 404: https://www.transifex.com/api/2/project/edx-platform/resource/frontend-app-gradebook/translation/en/strings/
(for comparison, here is the content from the payment MFE: https://www.transifex.com/api/2/project/edx-platform/resource/frontend-app-payment/translation/en/strings/)

I believe that all we need to do is to run, from inside the gradebook repo:

```
make extract_translations
make push_translations
```

With my Transifex API token, the latter command returns:

```
tx INFO: No credentials file was found at /home/regis/.transifexrc.
tx INFO: Created /home/regis/.transifexrc 
tx INFO: Pushing resource edx-platform.frontend-app-gradebook
[?] Enter your api token: 1/*****************
Verifying token...
tx INFO: Updating /home/regis/.transifexrc file...
tx ERROR: Not Found
tx INFO: Pushing source file (src/i18n/transifex_input.json)
tx INFO: Resource does not exist.  Creating...
tx ERROR: Forbidden
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: 
Error: Authentication failed. Please make sure your credentials are valid.
For more information, visit:
https://docs.transifex.com/client/client-configuration#-transifexrc.
```

So, I believe that all we need is to create the "frontend-app-gradebook" resource in Transifex. Anyone with push rights should be able to do it.

**Comment by sarina** [comment]
Hi @regisb - in order to do this I need to initially upload the translation file which is a json. Transifex is asking me what type of json this is and I don't know, do you? (I'm asking around internally but haven't gotten an answer)

![image](https://user-images.githubusercontent.com/1985317/141520239-8270c862-94d2-44a8-a953-19e868e6e043.png)

**Comment by sarina** [comment]
OK, I think this is done. It would be good to figure out if we need to have an admin create a new resource with every new repo, or if it can be somehow done via script.

**Comment by regisb** [comment]
> OK, I think this is done. 

Are you referring to the creation of the "frontend-app-gradebook" resource in Transifex? As far as I understand, it is not done:

1. Opening this page returns a "Resource 'edx-platform.frontend-app-gradebook' does not exist": https://www.transifex.com/api/2/project/edx-platform/resource/frontend-app-gradebook/translation/en/strings/
2. In frontend-app-gradebook when I run `make pull_translations` I get:

```
tx pull -f --mode reviewed --language="ar,fr,es_419,zh_CN"
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource edx-platform.frontend-app-gradebook doesn't exist on the server.
tx INFO: Done.
```

I'm taking the liberty to reopen this.

**Comment by sarina** [comment]
@regisb just saw that somethink went wonky in the file upload and it uploaded as `transifex_input`. https://www.transifex.com/open-edx/edx-platform/frontend-app-gradebook/ now exists.

**Comment by BbrSofiane** [comment]
edx/frontend-app-gradebook#218 is merged.
