### ISSUE TITLE
In the frontend header component, a link to the Order History is displayed even when ecommerce is disabled

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#109]
When ecommerce is disabled, there should not be a link to the order history in the top-right user menu:

![orderhistory](https://user-images.githubusercontent.com/44319/141728390-3b999d46-d126-4292-88a4-02162889c03b.png)

("historique des commandes" is French for "order history")

This link is set by the `ORDER_HISTORY_URL` in the frontend-component-header repo: https://github.com/edx/frontend-component-header/blob/632938f354d1f87d43a6d0d6f1778471e3fc5387/src/Header.jsx#L62

It is not clear to me whether this link will be removed when ORDER_HISTORY_URL is explicitly unset in the tutor-mfe plugin.

cc @shimulch who is handling the tutor-mfe plugin upgrade to Maple.

**Comment by shimulch** [comment]
It will not be removed even if `ORDER_HISTORY_URL` is explicitly unset, as the user menu [doesn't filter out](https://github.com/edx/frontend-component-header/blob/632938f354d1f87d43a6d0d6f1778471e3fc5387/src/DesktopHeader.jsx#L76) unset links. Probably conditional adding that links [here](https://github.com/edx/frontend-component-header/blob/632938f354d1f87d43a6d0d6f1778471e3fc5387/src/Header.jsx#L62) would be a better approach.

**Comment by cmltaWt0** [comment]
This behavior is the same for non MFE flow (order history link will appear in header navigation area) and required additional effort to change it.

Also the actual order page handles e-commerce absence correctly presenting the message "You have no orders yet" (or something like this). However this behavior is truly distracting for all testers and eventually for devs :)

**Comment by regisb** [comment]
I believe this is an actual UX bug: for the vast majority of Open edX platforms out there, there is no reason at all to display a "order history" menu item.

**Comment by pdpinch** [comment]
We tried to fix this some time ago, but I think we misunderstood which repo to make the change in:

https://github.com/edx/frontend-component-header-edx/pull/161/

For open edX, I think the change needs to go into [`frontend-component-header`](https://github.com/edx/frontend-component-header/)

**Comment by asadiqbal08** [comment]
We are working to move the learning MFE header to `frontend-component-header` and import header from  `frontend-component-header` instead of learning MFE that would be helpful to manipulate with `Order History`

**Comment by davidjoy** [comment]
FYI - this code demonstrates the easiest way to turn this link off: https://github.com/edx/frontend-component-header-edx/blob/master/src/Header.jsx#L114

Ignoring the "enterprise" part of that line:

```
if (config.ORDER_HISTORY_URL) {
  userMenu.splice(-1, 0, orderHistoryItem);
}
```
