### ISSUE TITLE
In the learning MFE, the course upgrade button has an incorrect link

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#111]
I have setup a course in Ecommerce to provide verified certificates. When I access the course content in the learning MFE, an upgrade button is displayed ("Mise à niveau pour $100"). This button links to /dashboard.

![upgrade](https://user-images.githubusercontent.com/44319/142043007-852e3171-2140-49f0-a5b8-887c879a6961.png)

This link is incorrect: indeed, MFEs are running in a subpath of the main MFE domain name. For instance, the learning MFE is at apps.local.overhang.io/learning. The /dashboard links would send to apps.local.overhang.io/learning, which does not correspond to any MFE.

Instead, we should probably redirect the user to lms_host_url/dashboard.

In my (admittedly limited) understanding of the learning MFE, this link comes from here: https://github.com/edx/frontend-app-learning/blob/83fa3f78bc89beb7b0a2446fef66696a49290b54/src/course-home/data/__factories__/upgradeNotificationData.factory.js#L18

**Comment by cmltaWt0** [comment]
I've started to investigate the case.

1. Testing on Demo course shows that upgrade url is correct. Moreover some reverse engineering reveals the fact that the complete `upgrade_url` comes from Course metadata API:
```
"dates_banner_info": {
        "missed_deadlines": false,
        "content_type_gating_enabled": false,
        "missed_gated_content": false,
        "verified_upgrade_link": "http://localhost:18130/basket/add/?sku=8CF08E5"
    },
    "can_show_upgrade_sock": false,
    "verified_mode": {
        "access_expiration_date": null,
        "currency": "USD",
        "currency_symbol": "$",
        "price": 149,
        "sku": "8CF08E5",
        "upgrade_url": "http://localhost:18130/basket/add/?sku=8CF08E5"
    },
```
<img width="1328" alt="Screenshot 2021-12-04 at 17 06 20" src="https://user-images.githubusercontent.com/877401/144829397-c0ff2d20-535f-402f-bd3f-cc916a0f3dd5.png">

<img width="898" alt="image" src="https://user-images.githubusercontent.com/877401/144830314-beda3651-329e-42c3-b12c-c8ea2710af58.png">


2. I will try it again with custom course to try to reproduce your case.
3. upgradeNotificationData factory is just a test base and it defines host as `http://localhost:18000` and it's used by `UpgradeNotification.test.jsx` [here](https://github.com/edx/frontend-app-learning/blob/83fa3f78bc89beb7b0a2446fef66696a49290b54/src/generic/upgrade-notification/UpgradeNotification.test.jsx#L23):
```
describe('Upgrade Notification', () => {
  function buildAndRender(attributes) {
    const upgradeNotificationData = Factory.build('upgradeNotificationData', { ...attributes });
    render(<UpgradeNotification {...upgradeNotificationData} />);
  }
```

**Comment by cmltaWt0** [comment]
@regisb 

I've done the testing on tutor installation from a scratch.

**Long story short** - It looks like everything works as expected.

Testing steps:
---

1. Create honor and verified modes for a Course.

<img width="853" alt="Screenshot 2021-12-07 at 12 47 15" src="https://user-images.githubusercontent.com/877401/145016433-53f2b0b3-3127-4546-bf06-9ff4a8a8038a.png">

2. Create the new Course in ecommerce http://ecommerce.local.overhang.io/courses/

<img width="999" alt="Screenshot 2021-12-07 at 12 47 28" src="https://user-images.githubusercontent.com/877401/145016471-2d124e06-7202-4480-9bb2-c1c93a054e4c.png">

<img width="994" alt="Screenshot 2021-12-07 at 12 53 10" src="https://user-images.githubusercontent.com/877401/145016484-0a1ba3d7-5a63-4395-aaf8-ce1defe9ac82.png">


3. Open Old and new Courseware to check the upgrade link

<img width="1161" alt="Screenshot 2021-12-07 at 12 47 56" src="https://user-images.githubusercontent.com/877401/145016622-4101981e-9db0-4c3b-a09a-9df29819bbad.png">

<img width="1162" alt="Screenshot 2021-12-07 at 12 48 18" src="https://user-images.githubusercontent.com/877401/145016648-6d7223c5-0821-4f03-ad88-960e577289a8.png">



Is it correct way to check the flow?

**Comment by regisb** [comment]
Thanks for the verification @cmltaWt0, I can also confirm that the issue no longer appears. Let's close this for now and we'll reopen if necessary.
