### ISSUE TITLE
frontend-component-header is not translated

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#116]
The MFE header menu is not translated, as reported in this conversation: https://discuss.overhang.io/t/mfe-still-translation-bugs/2157

![header](https://discuss.overhang.io/uploads/default/optimized/2X/f/f40de7e46a820bab979adc1f75829cb447021d7e_2_690x219.png)

Indeed, there are no translation in the src/i18n/messages folder: https://github.com/edx/frontend-component-header/blob/master/src/i18n/messages/es_419.json

This is because the frontend-component-header is not on Transifex: https://www.transifex.com/api/2/project/edx-platform/resource/frontend-component-header/translation/en/strings/

Currently, the following command fails in the header repo:

```
$ make pull_translations 
tx pull -f --mode reviewed --language="ar,fr,es_419,zh_CN"
tx ERROR: Not Found
tx ERROR: Not Found
tx ERROR: Resource edx-platform.frontend-component-header doesn't exist on the server.
tx INFO: Done.
```

I recommend that the corresponding resource be created on Transifex and that we pull translations in the Maple branch.

**Comment by dianakhuang** [comment]
I have added the transifex resource and now translations are being created for this repo: https://github.com/edx/frontend-component-header/commit/2f0a07b7eb1099edab815ab48070e69bf3455b4d

I'm not sure the value of trying to merge these files in until the translations are reviewed on Transifex though:  https://www.transifex.com/open-edx/edx-platform/frontend-component-header/

**Comment by gabrieldamours** [comment]
FR-CA is 100% translated and reviewed now.

**Comment by dianakhuang** [comment]
Awesome, thanks @gabrieldamours ! I'm going to make sure our automation pulls down those translations so we can merge them into the Maple branch.

**Comment by BbrSofiane** [comment]
This can be closed once we've updated the component version in the maple branch of the MFEs.
