### ISSUE TITLE
MFEs should not make calls to NewRelic when the service is not configured

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#117]
See upstream issue in the frontend working group project: https://github.com/openedx/frontend-wg/issues/14

**Comment by BbrSofiane** [comment]
edx/frontend-build#215

**Comment by BbrSofiane** [comment]
@regisb you've closed openedx/frontend-wg#14 can we also close this issue?

**Comment by regisb** [comment]
Yes, absolutely.
