### ISSUE TITLE
In the payment MFE, the Cybersource payment processor does not work

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#121]
The payment fields in the payment MFE are greyed out when attempting to make payments with the Cybersource payment processor. Although I did not manage to get to a point where I could reproduce the issue, there are multiple credible reports from actual users:

https://discuss.overhang.io/t/have-you-configured-cybersource-in-liliac/2170/1
https://discuss.openedx.org/t/payment-mfe-configuration/5375/3
https://discuss.overhang.io/t/payment-mfe-and-cybersource/1864

@sambapete has reported that the Cybersource payment processor works in the devstack, so it might only be a matter of backend configuration.

**Comment by sumanchapai** [comment]
I found and fix the error, and have submitted a PR
<https://github.com/edx/ecommerce/pull/3586>

**Comment by pshiu** [comment]
Thanks, @sumanchapai! This looks great. I will start testing it tomorrow and provide you with an update as soon as I can.

**Comment by regisb** [comment]
This changed is pulled in the maple branch of tutor-ecommerce (https://github.com/overhangio/tutor-ecommerce/pull/18) and I verified that it resolves our issue. Thanks @sumanchapai! All we need to do now is to merge edx/ecommerce#3586, both in the master and the open-release/maple.master branches.

**Comment by BbrSofiane** [comment]
This fix is being patched in tutor overhang/tutor-ecommerce#18.
