### ISSUE TITLE
update lti-consumer-xblock to 3.1.1

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#122]
While working on the release notes, I noticed that v.3.1.1 of lti-consumer-xblock includes a "Long-term fix for cross-origin iFrames" which seems like something we should include in the maple release. 

https://github.com/edx/xblock-lti-consumer/releases/tag/3.1.1

There is a clean commit for this version that was merged in November at https://github.com/edx/edx-platform/commit/cea3f32d0db492b3123daa6ad14d9020e5fa3431

**Comment by BbrSofiane** [comment]
@pdpinch just making sure this is on your radar
