### ISSUE TITLE
Timed Exams breaking in Lilac with edx-proctoring version update

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#123]
[Forum thread](https://discuss.openedx.org/t/timed-exams-breaking-in-lilac-with-edx-proctoring-version-update/6161).

Proposed solution:

**Comment by regisb** [comment]
1. Rollback edx-proctoring 3.25.0 -> 3.8.5 migrations
2. Install edx-proctoring 3.8.5.1 from eduNEXT's fork
3. Verify that timed exams work correctly
4. Publish the solution on the forum

**Comment by clemente** [comment]
@regisb Hi; are you working on the steps you mentioned above, or are they ideas? If they're ideas or if it's a solution that works, maybe you can post it in the forum thread linked from the description?

From what I understand, this isn't a bug in upstream Lilac or in Maple, just in a custom installation where some code was modified, right? Is there anything to fix in this task? CC @BbrSofiane 

I'm taking a look at the BTR tasks to see whether there are easy contributions for new team members in OpenCraft. If this task represents a bug upstream, it could be such a task; let me know.

**Comment by regisb** [comment]
I was only suggesting an outline for a solution. 

This is an upstream bug in Lilac. edx-proctoring was upgraded to address a security issue, thus triggering another issue where timed exams no longer work.

As far as I understand, this issue does not affect Maple, so we can close this.

**Comment by jfavellar90** [comment]
@BbrSofiane I answered the post in [discuss](https://discuss.openedx.org/t/timed-exams-breaking-in-lilac-with-edx-proctoring-version-update/6161/4?u=jhony_avella)
