### ISSUE TITLE
The frontend-component-footer logo links to https://open.edx.org

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#128]
In all MFEs, the logo that is located in the bottom left corner is a hardcoded link to https://open.edx.org:

![footer-logo](https://user-images.githubusercontent.com/44319/148026775-7cff18b3-54b6-4599-ae4c-fe884dfad08a.png)

It should instead link to the LMS.

Here is the guilty line: https://github.com/edx/frontend-component-footer/blob/2b56d270a28e25ac9b89129abaa4d736d0cec1e2/src/components/Footer.jsx#L61

This issue was first detected here: https://discuss.overhang.io/t/footer-logo-in-tutor-mfe-points-to-open-edx-org-can-it-be-customized/2273

**Comment by ayrtonlr** [comment]
Hello @regisb, Can I contribute to this open source project by taking this issue as my first one?

**Comment by regisb** [comment]
That would be great @ayrtonlr! Thanks for your proposition. Are you already somewhat familiar with Open edX?

**Comment by ayrtonlr** [comment]
> That would be great @ayrtonlr! Thanks for your proposition. Are you already somewhat familiar with Open edX?

@regisb I've never done an Open edX issue, but I'm reading the Developer's Guide and would like to try this issue to get started in the open source world.

**Comment by BbrSofiane** [comment]
@ayrtonlr are you still working on this issue?

**Comment by ayrtonlr** [comment]
@BbrSofiane Yes, I am waiting the review:

https://github.com/openedx/frontend-component-footer/pull/178

**Comment by NeOneSoft** [comment]
Hi guys!! only as a friendly note, @arbrandes  is already reviewing the PR that @ayrtonlr created to solve this issue.

**Comment by arbrandes** [comment]
Fixed!  Thanks @ayrtonlr!
