### ISSUE TITLE
Backport Report Generation fix

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#130]
from https://github.com/mitodl/mitxpro/issues/2332

this should be fixed by https://github.com/edx/edx-platform/pull/29699

### Steps to Reproduce

- Go to the data download tab of the instructor dashboard of a course 
- Click on the `Select a section or problem` button for the `Create a report of problem responses` report

### Expected Behavior

- A menu of the course content should pop up 
![image](https://user-images.githubusercontent.com/21342568/146632048-a85d7475-81ff-4f45-ae29-7a536f1497de.png)

### Actual Behavior

- The page doesn't respond
- Errors appear in the Console (see below)

### Stacktrace

The Console
![image](https://user-images.githubusercontent.com/21342568/146632003-c7430fa9-c59d-449d-a88a-fbab16d40f98.png)

### Screenshot or Screencast

The Button / Report
![image](https://user-images.githubusercontent.com/21342568/146631992-ad4f381c-e3fc-4253-aa8b-072d565ea365.png)

**Comment by yekaifeng** [comment]
Hi, let me try to fix this

**Comment by BbrSofiane** [comment]
thanks for volunteering @yekaifeng.

The fix is in openedx/edx-platform#29699 and is waiting to be merged. Once it's done can you create the same PR on the maple release branch?

**Comment by pdpinch** [comment]
Sorry @yekaifeng we had some confusion about this. It turns out it was already fixed in master by this PR: https://github.com/openedx/edx-platform/pull/29388 

There's already a PR open to backport it to maple at https://github.com/openedx/edx-platform/pull/29742

However, we could use some help in testing the backport PR, to make sure it corrects the error described here. Would you be able to review https://github.com/openedx/edx-platform/pull/29742

**Comment by arslanashraf7** [comment]
@BbrSofiane @pdpinch @yekaifeng FYI,

A little clarification to the referred PRs in earlier comments:

I created https://github.com/openedx/edx-platform/pull/29699 to fix this in master and also created a backport of the same for maple(https://github.com/openedx/edx-platform/pull/29742). (Both of which I've closed in favor of https://github.com/openedx/edx-platform/pull/29388)

However, we later realized that another PR(https://github.com/openedx/edx-platform/pull/29388) was merged into the master earlier for the same fix. So, I think a backport PR for maple doesn't exist for https://github.com/openedx/edx-platform/pull/29388. We might need to create that.

**Comment by arslanashraf7** [comment]
> @arslanashraf7 @pdpinch Let me try to recap the situation: this issue has already been fixed in the master branch. It needs to be backported to maple branch which is open-release/maple.master. Please correct me if any misunderstand. This is my first PR. I need to get familiar with the product and figure-out how to test it.

Thanks for reaching out @yekaifeng 

>It needs to be backported to maple branch which is open-release/maple.master

You're correct, You need to open a PR against `open-release/maple.master`

Now, In case you want to know how you'd create the PR?
1) You won't have access to create a branch in the open edX, so create a branch from `open-release/maple.master` in your own fork. (Before creating a branch please, Make sure to locally pull the latest `open-release/maple.master` branch)
    - Once you have created a branch from `open-release/maple.master`, please cherry-pick [this commit](https://github.com/openedx/edx-platform/commit/2ebfe47077a51a5aaba56c0cd39f072d538dbd30) in your newly created branch.
2) Test your branch on the Open edX `maple` named release
    - Setup the `maple` release
    - Login with edx user e.g. `edx@example.com/edx` and open a course, Enroll in the course, Now open `Instructor Dashboard` and finally click `Data Download`
    - Once you are on `Data Download` tab click click `Select a section or problem` and you should see a menu instead of `404` response in the console.
3) Open a PR against `open-release/maple.master` and make sure that all the CI tests are passing in your PR.

Further instructions can be found on this ticket's description and [this PR](https://github.com/openedx/edx-platform/pull/29699)

**Comment by yekaifeng** [comment]
@arslanashraf7 Thanks, I am go ahead to fix it

**Comment by yekaifeng** [comment]
I've already know how to fix it. It need to be tested.
I am setting up a devstack environment(docker). The github network is not stable here. Trying to connect with my personal proxy.  It takes me a lot of time.

**Comment by BbrSofiane** [comment]
Thanks for closing this out @yekaifeng!
