### ISSUE TITLE
BTR requirements for an MFE to be included in a release

### ISSUE THREAD

**Issue by ghassanmas** [openedx/build-test-release-wg#131]
Update: the requirements list will live here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE
_____________________________________________

The FWG was discussing how to ease the process for BTRWG when deploying or adding a new MFE in a release, one thought we had is to get a **list of requirements or/and features** that an MFE should have (from BTR perspective) so that these requirements would be thought of or worked in advance.

For example, @davidjoy mentioned that there were issues regarding i18n strings, and to make specific components/elements customizable..etc. 
 
Also, we can issue a cross-collaboration between MFWG and BTRWG to brainstorm how to make the job of BTR when releasing an MFE easier or with less friction (coming out with a list of requirements is just one way to think of).

**Comment by arbrandes** [comment]
From today's BTR meeting:

* Find out what new MFEs will make it to Nutmeg?
* In particular, find out about Discussions and Learning.

**Comment by NeOneSoft** [comment]
Hi @arbrandes hope you doing well!!. As I understand this is still under discussion right?Thank you so much!!

**Comment by arbrandes** [comment]
@NeOneSoft, yes, this is very much still under discussion!

**Comment by arbrandes** [comment]
This is what is known to date:

This is the main ticket that tracks this question is: couldn't find any duplicates.

The frontend roadmap item that more closely tracks this is https://github.com/openedx/tcril-engineering/issues/417

There's an old MFE Definition of Done page in the wiki.  This is more pertinent, particularly starting with the [Architecture Concerns subheading](https://openedx.atlassian.net/wiki/spaces/FEDX/pages/1917944547/MFE+Definition+of+Done#Architecture-concerns).

The actual checklist the BTR group used for Lilac can be found in one of the related tickets, such as https://github.com/openedx/build-test-release-wg/issues/29.  It goes, in relation to each MFE:

- [ ] It passes a minimum standard of documentation: at the very least, the READMEs should have descriptive text that includes use cases, screenshots, and particularly, documentation on that MFE's environment variables.
- [ ] Its basic feature-set (as documented above) works reliably with the rest of the Lilac codebase.
- [ ] It's deployed by default using the Native Installation, and deployable as a plugin using Tutor.
- [ ] It is internationalized (i18n), localizable (l10n), and passes minimum accessibility (a11y) standards.
- [ ] It has a header and footer that are customizable via npm aliases: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#overriding-brand-specific-elements
- [ ] It is compatible with the @edx/brand system: https://open-edx-proposals.readthedocs.io/en/latest/oep-0048-brand-customization.html
- [ ] It uses CSS utility classes in a branding-friendly way. (i.e., don't use things like 'bg-white')

**Comment by arbrandes** [comment]
Copy-pasta of [a post](https://discuss.openedx.org/t/mfe-runtime-configuration/8495/7?u=arbrandes) I made in the forum:

#### Do we need to include every MFE in that list in Tutor/Olive? 

*TLDR: No.*

MFE developers (as of now mostly employed at or by 2U) are aware they can't remove a feature in edx-platform before the MFE that replaces it is officially accepted as being production-ready by the community.  This should apply to each MFE in that list, and it means we don't *have* to enable any of them for Olive if we don't want to.

#### How do we decide which ones to include?

*TLDR: Don't know.  We need to decide how to decide.*

While the ultimate decision on whether an MFE is ready is in fact up to the community, and in particular, the BTR group, there is no official method to arrive at this decision.  This is a problem we should fix *pronto*, precisely so we can answer the question of which ones to include.

[This comment](https://github.com/openedx/build-test-release-wg/issues/131#issuecomment-1270548031) in the ticket where we're tracking this question is a collation of the information I could find.  Please refer to it and add your comments, including which MFEs you would like to have included, and why.  Once we have a reasonable idea of where the community's opinion lies, we can start to narrow down the list in a technical fashion: by checking each MFE against the criteria.

(And yes, right off the bat it looks like a *sine qua non* criterion is whether the MFE supports runtime configuration.)

#### Product considerations

*TLDR: Let's consult the Product Working Group as well.*

There are product considerations to take into account.  Ultimately, I think the list will be narrowed down a lot by them.  I'm not saying they have ultimate say, but it doesn't make sense to start maintaining Tutor support for an MFE if it doesn't make sense to make it part of the Open edX product at a given point in time.

I've started discussing this with @jmakowski, yesterday.  The short of it is that my job will be to try and put all stakeholders together (mostly asynchronously, such as via this post) so we can decide ASAP which MFEs to work on for Olive.

**Comment by kdmccormick** [comment]
Relatedly, we have proposed [OEP-57](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3540713547/Open+edX+Proposal+57+Product+Offering), which would create a system for deciding what needs to be enabled by default in the named releases (the "Core Product Offering"). I encourage all of BTR to review it and I am hopeful that this will make things easier when the Palm release rolls around. I recognize that an unmerged OEP isn't extremely helpful for deciding what goes in Olive :P

**Comment by kdmccormick** [comment]
One criteria I’d add is: Has the legacy version of the frontend stopped working on master?. If yes, we’re forced to either get the legacy feature fixed, or to include & enable the MFE. When it’s unexpected, this scenario drives me crazy and represents an absolute failure of our deprecation process. Yet, it’s still something we need to look out for when considering MFEs for release.

**Comment by hurtstotouchfire** [comment]
@arbrandes Do we have a ticket somewhere tracking the list of potential MFEs and their status as far as potential inclusion?

**Comment by arbrandes** [comment]
@hurtstotouchfire, this is where the raw list is being gathered:

https://github.com/openedx/build-test-release-wg/issues/200

**Comment by ghassanmas** [comment]
> One criteria I’d add is: Has the legacy version of the frontend stopped working on master?. If yes, we’re forced to either get the legacy feature fixed, or to include & enable the MFE. When it’s unexpected, this scenario drives me crazy and represents an absolute failure of our deprecation process. Yet, it’s still something we need to look out for when considering MFEs for release.

@kdmccormick for this and also for documentation purpose, I have just opened an issue about changes of toggles/settings between nutmeg and olive #204

**Comment by arbrandes** [comment]
This is where the master list is now being tracked:

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE

Please leave your comments and suggestions in there.  The list is supposed to be modified organically.
