### ISSUE TITLE
Nutmeg Release notes

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#133]
- [ ] Meta: Review and update this checklist
- [ ] Meta: Commit this checklist to a more durable location 

The wiki page for [Process to Create an Open edX Release](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release) has a couple of steps for creating release notes:

### Things that _can_ be done before the release is cut
- [x] Get release notes started (what _exactly_ is involved?) 
   - [x] find the date for the previous release (for maple this was October 15, 2021)
   - [x] find the date for the next release (for nutmeg, this is planned to be April 11, 2022)
   - [x] these dates will be used to review commit logs and release notes from individual repos 
- [x] Create a wiki page for the _next_ release, on the [Open edX Release Planning](https://openedx.atlassian.net/wiki/spaces/COMM/pages/13205845) wiki page
- [x] take a [snapshot of the technical documentation](https://readthedocs.org/projects/edx-platform-technical/downloads/) (toggles and settings) for the maple release, so we can diff them with the nutmeg release 
- [x] add an appropriate TOC to the release notes

### Things to do after the release is cut
- [ ] [When the release branches are made](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#When-the-release-branches-are-made)
- [x] add any items from the [Nutmeg wiki page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2603816700/Maple)  
- [x] Review and incorporate any feature posts from [edX Partner announcements](https://partners.edx.org/announcements)
- [x] Review and incorporate any feature posts from the [open edX blog](https://open.edx.org/category/blog/)
- [x] Review commit messages from relevant repos. [Dinghy](https://github.com/nedbat/dinghy) seems like a userful tool for this. I used this config [nutmeg.yaml](https://gist.github.com/pdpinch/e315f150d39f77a22840f9a0ece89b71)
- [x] Review [DEPR tickets ](https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=452)
- [x] Diff the technical documentation and build a lists of links to both new and removed settings

### Things to do after the release is made public (after June 9th for nutmeg)
- [ ] update https://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/os_documentation.html and replace the maple documentation links with nutmeg documentation links 
- [ ] take a [snapshot of the technical documentation](https://readthedocs.org/projects/edx-platform-technical/downloads/) (toggles and settings) for the nutmeg release, so we can diff them with the olive release

**Comment by pdpinch** [comment]
Thinking about this step:

> take a [snapshot of the technical documentation](https://readthedocs.org/projects/edx-platform-technical/downloads/) (toggles and settings) for the maple release, so we can diff them with the nutmeg release

It seems like I should have done this when maple was first cut, so I could compare the diff from then until now. 

I'm wondering now if there's a way to recreate the state of the technical documentation from that date.

**Comment by Agrendalath** [comment]
@pdpinch, Read The Docs allows [setting multiple versions](https://readthedocs.org/projects/edx-platform-technical/versions/) that are built. We could even add public versions for tagged releases. This way, users will be able to switch between them with the panel in the bottom right corner of the [page](https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/):
![image](https://user-images.githubusercontent.com/3189670/162454697-efc5890b-d6bd-4737-b99c-c4be3a21a257.png)

**Comment by pdpinch** [comment]
Thanks for the suggestion @Agrendalath. I opened an issue for setting that up.

**Comment by ghassanmas** [comment]
@pdpinch 
If I understand correctly you want to view the diff of docs/technical in edx-platform to get an idea what settings are changed. 

So may be running: 
`git diff 0ce915273c2db14611d49165e9e7a708083d57ef 489ed46cb41a624f00385f3d6cead7f60584e695 docs/` Or `git diff 0ce915273c2db14611d49165e9e7a708083d57ef 489ed46cb41a624f00385f3d6cead7f60584e695 docs/technical`
Could be helpful? 

The first commit hash is what I found one the first commits on maple.master while the second hash is last commit on nutmeg.master.

docs/technical doesn't seems to be changed at all during that period, but the parent directory has changed, some meta changes for docs, not really sure. 

Also note seems docs/techncial isn't always the only source for trurth for settings? since during maple a new settings was added hence https://github.com/openedx/edx-platform/commit/43a0277a399d0980decc73681b09bf17cd2e8df8 but that change wasn't reflected docs/technical, shuold it?

**Comment by pdpinch** [comment]
Thanks @ghassanmas. I was referring to the [edx-platform technical reference](https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/index.html) which is generated automatically based on code annotations across multiple repositories. Going forward, I think we need to update the script that builds those docs to support each named release (#183).

**Comment by NeOneSoft** [comment]
Hi @pdpinch !!!! Since [PR](https://github.com/openedx/edx-documentation/pull/2056) was merged. Do we have any other concern regarding this issue. Thank's a lot!!!

**Comment by pdpinch** [comment]
I think there are some things I'd still like to do, but it's time to look forward to the next release!

**Comment by NeOneSoft** [comment]
Thank you so much @pdpinch !!!
