### ISSUE TITLE
BTR member roles assignments for Nutmeg.

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#136]
As with every new release cycle, the Build Test Release group is looking for volunteers to keep it running. A new release cycle means that BTR members can opt in or opt out of their current role(s).

- [x] [Chair](https://github.com/openedx/build-test-release-wg#group-chair)
- [x] [Release Manager](https://github.com/openedx/build-test-release-wg#release-manager)
- [x] [Release Testing Coordinator](https://github.com/openedx/build-test-release-wg#release-testing-coordinator)
- [x] [Release Documentation Expert](https://github.com/openedx/build-test-release-wg#release-documentation-expert)
- [x] [Bug Triager](https://github.com/openedx/build-test-release-wg#bug-triager)
- [x] [Community Liaison](https://github.com/openedx/build-test-release-wg#community-liaison)

If you'd like to put your name forward for one of the roles comment below.

**Comment by cmltaWt0** [comment]
@BbrSofiane could you add some roles description. I'm not sure we have all roles explained.

**Comment by BbrSofiane** [comment]
Available roles:
- Release Testing Coordinator

Roles where current members are willing to continue but also happy to step down if anyone else would like to volunteer:
- Chair
- Release Manager
- Release 

Roles Taken
- Release Documentation Expert @pdpinch
- Bug Triager @jfavellar90 and @NeOneSoft

**Comment by BbrSofiane** [comment]
https://discuss.openedx.org/t/nutmeg-btr-member-roles/6634/3

**Comment by jfavellar90** [comment]
Marked as done since roles were already assigned
