### ISSUE TITLE
Will devstack be included in Nutmeg?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/build-test-release-wg#138]
## Context

[Tutor](https://github.com/overhangio/tutor) is both a deployment tool and a development environment. Although Tutor has been the only community-support deployment method since Maple, [Devstack](https://github.com/openedx/devstack) remains the community-supported development environment.

There is an [ongoing "Tutor adoption initiative"](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3315335223/Tutor+Adoption+Initiative) which aims to replace Devstack with Tutor through a mix of education, plugin development, and core Tutor improvements. It will ultimately lead to Devstack's deprecation and removal.

## The question

Should devstack be:
1. included and 'supported' in Nutmeg,
2. included but 'deprecated' in Nutmeg, or
3. excluded from Nutmeg?

## Factors

* progress of the tutor adoption initiative
* whether the Tutor maintainers feel ready for us to ditch devstack
* community sentiment around the switch
* devstack maintainers' (edX Arch-BOM?) willingness to maintain devstack through Nutmeg

**Comment by kdmccormick** [comment]
My own opinion on this: I am on the fence... it would be really great to stop directing community energy at Devstack as soon as possible, but I also think our readiness will depend on how fast we can move in the adoption initiative. I would lean heavily on @regisb 's opinion here.

**Comment by regisb** [comment]
I'm confident that we can get the new plugin API to a production-ready state by Nutmeg. But from my perspective, the crux of the matter is whether the current Devstack maintainers are ready to keep maintaining the Devstack for the community after Nutmeg. Which raises the question: who are the maintainers of the Devstack? Is it 2U, tCRIL or someone else?
I don't want to impose Tutor on anyone's workflow. I think that anyone should be free to choose whatever their development environment should be. But what we owe to the community is being transparent with regards to the maintenance status of all Open edX projects.

**Comment by kdmccormick** [comment]
@rgraber @dianakhuang - I know repo ownership has gotten interesting since the tCRIL/2U split, but I think edX Arch-BOM still maintains devstack, right? Do y'all have thoughts and/or could you bring this question to your team?

**Comment by dianakhuang** [comment]
We can bring it to the team, and I think we're willing to support devstack until everyone feels comfortable using Tutor. I highly suspect the longest holdouts will be 2U/edX folks, so I don't think the release cycle will affect us as much.

**Comment by kdmccormick** [comment]
For clarity on the timeline: Nutmeg is cut in early April and released in early June, as far as I know.

After thinking this over more, I think it is fair to aim for Tutor being the *recommended* development environment by Nutmeg's release, but I would be hesitant to commit to it being the *only* supported development environment in Nutmeg, especially if 2U is willing to support devstack for one last release cycle.

I propose we follow what the [community decided when transitioning from the Native installation to Tutor](https://github.com/openedx/open-edx-proposals/blob/master/oeps/architectural-decisions/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst#decisions). That is, we would support both environments in Nutmeg, with the plan of dropping support for Tutor in Olive (~Oct-Dec 2022). 

If that plan sounds good to the Devstack maintainers (@dianakhuang and team) then I can write up a DEPR ticket for Devstack along these lines.

**Comment by kdmccormick** [comment]
Closing this in favor of a DEPR ticket: https://github.com/openedx/devstack/issues/907

Long story short: Yes, Devstack will be in Nutmeg, unless anyone seriously disagrees with what's I've proposed on that DEPR ticket.
