### ISSUE TITLE
Open sandbox to the community

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#140]
To help to test, It is suggested that the group facilitates the deployment of a public instance of release candidates to encourage non-technical community members.

**Comment by DeanJayMathew** [comment]
I'm on this! Régis Behmo will sponsor the instance and I assume pass some access credentials to pre-approved testers.

**Comment by NeOneSoft** [comment]
Hi@DeanJayMathew !! If I'm not wrong this instance is already working right? Do you think that we can close this issue or do we need something else?Thank you so much!!

**Comment by DeanJayMathew** [comment]
Hi @NeOneSoft and @BbrSofiane you are 100% correctamundo! Please go ahead a close it for us, thank you.

**Comment by NeOneSoft** [comment]
Perfect @DeanJayMathew thank you and @BbrSofiane !!! I'll proceed
