### ISSUE TITLE
Should the Discussion MFE be part of Nutmeg?

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#141]
What's required for the [Discussion MFE](https://github.com/openedx/frontend-app-discussions) to be part of the community release?

**Comment by pdpinch** [comment]
I'll follow up with the frontend-working group on this, to find out what the plan is for this MFE. As far as I know right now, it will be part of the codebase in time for nutmeg, but I don't think it will be in general release yet on edx.org.

**Comment by pdpinch** [comment]
The discussion MFE has only been released to staff on edx.org, so it seems premature to make it a supported part of the nutmeg release. 

We will include it in the release notes as an experimental feature, which operators can deploy if they choose and it can be enabled.
