### ISSUE TITLE
Should the Authentication MFE be part of Nutmeg?

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#142]
https://github.com/openedx/frontend-app-authn/

**Comment by nedbat** [comment]
Things BTR would like to know:

- [ ] Is it enabled on edx.org today?
- [ ] Is it brandable?
- [ ] Is it localizable?
- [ ] Does it support path-based routing?
- [ ] Does it require migrating data for it to work on migrated sites?
- [ ] Does it have feature parity with old authentication? If not, what is missing?
- [ ] Does third-party authentication still work?

**Comment by BbrSofiane** [comment]
[ ] Does it replace anything that will be deprecated? @kdmccormick

**Comment by kdmccormick** [comment]
Copying in my [discussion so far](https://openedx.slack.com/archives/C02R2PF91QA/p1649085317228539) with @waheedahmed :

> Kyle: Hey Waheed! My questions are:
> * Do you know if the legacy authn frontend still works?
> * Do you plan to support the legacy authn frontend going forward, such as fixing bugs or accepting community PRs to it?
> * Do you plan to deprecate and remove the legacy authn frontend?
> * Do you see any reason that the new authn MFE shouldn't be included in Nutmeg (which is being cut tomorrow) so community members can begin trying it out?

> Waheed:
> * Do you know if the legacy authn frontend still works?
>   * Yes
> * Do you plan to support the legacy authn frontend going forward, such as fixing bugs or accepting community PRs to it?
>   * Yes, we are already doing it
> * Do you plan to deprecate and remove the legacy authn frontend?
>   * The ticket is in our backlog but not in near future because Enterprise flows are not yet ported into the Authn MFE.
> * Do you see any reason that the new authn MFE shouldn’t be included in Nutmeg (which is being cut tomorrow) so community members can begin trying it out?
>   * Not exactly except two things:
>     * Enterprise flows are still using the legacy frontend
>     * Dynamic registration fields are not yet supported in Authn MFE

> Kyle: Thanks Waheed, this is super helpful!
>
> So it sounds like the old frontend is still used on edX.org for those enterprise cases? Good to know.
> 
> I think the community could find it valuable if they were able to optionally enable the MFE in an upcoming open release, either Nutmeg or Olive. It's OK if it's not feature complete; we would just let them know what features are still in progress. This would let them "preview" the new MFE while still being able to fall back to the old one, giving them more time to adapt and your team time to respond to any feedback. We have followed this pattern for other MFEs such as Learning. Let me know what you think. I will take a look at the Auth MFE today and see how much work it would take just to make it optionally available in an open release :) 
>
> Lastly, since you plan to eventually deprecate and remove, could you write up a DEPR ticket soon? Even if you're not ready to remove the old frontend, declaring your intent to deprecate and a rough timeline will be really helpful to us in the build-test-release group and community deployers as we plan for the future.

**Comment by kdmccormick** [comment]
So, with respect to our list of questions:

* How can we find out more about how it works and what it does?
  * TBD
* Is it enabled on edx.org today?
  * Yes, but not at 100%. Enterprise logins are still done through the old frontend.
* Is it brandable?
  * TBD
* Is it localizable?
  * TBD
* Does it support path-based routing?
  * TBD 
* Are there any constraints on the domain where the authn MFE is running?
  * TBD 
* Does it require migrating data for it to work on migrated sites?
  * I imagine not, but TBD 
* Does it have feature parity with old authentication? If not, what is missing?
  * Not yet. Enterprise login and dynamic registration fields are not supported. Based on the language above it sounds like they will be supported.
* Does third-party authentication still work?
  * Based on my experience, yes (Google SSO works at the very least) but we may want to dig deeper.
* Does it replace anything that will be deprecated?
  * It will eventually replace the legacy login and registration pages. But, the team still relies upon those legacy pages and says that they do not plan to remove them "in the near future".

**Comment by kdmccormick** [comment]
And two more questions from me:
* If included, how much of an impact on build times and resource consumption would this have on the Tutor MFE plugin?
* Bassed on this^, should we include Authn in the MFE plugin for Nutmeg, or wait?

**Comment by kdmccormick** [comment]
Our decision, copied in from Slack:

> * Background:
>   * The MFE is complete for common use cases but isn't feature-complete for advanced use cases (notably, dynamic registration fields),
>   * The legacy frontend still works and hasn't been marked deprecated yet,
>   * In its current design, building any new MFE into the tutor-mfe plugin slows down its build and increases its image size.
> * Proposal:
>   * We tag the Authn MFE for Nutmeg, describing it in the release notes as "experimental" and explaining which flag(s) would need to be toggled in order to enable it.
>   * We don't add the Authn MFE to upstream tutor-mfe yet, but we do point folks to [these instructions for adding extra MFEs to tutor-mfe](https://github.com/overhangio/tutor-mfe/#adding-new-mfes).
>   * We plan on properly adding the Authn MFE to tutor-mfe for Olive.
>   * We file a backlog issue around reducing the impact of adding new to MFEs to tutor (or is there already an issue for this?)

**Comment by kdmccormick** [comment]
Closing this since we have an answer to the immediate question.

Short-term follow (for Nutmeg):
* https://github.com/openedx/build-test-release-wg/issues/150

Longer-term follow-ups (Olive+):
* https://github.com/openedx/build-test-release-wg/issues/151
* https://github.com/openedx/build-test-release-wg/issues/152
