### ISSUE TITLE
Will Nutmeg include Mongo?

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#144]
https://discuss.openedx.org/t/adr-for-removing-mongodb-from-edx-platform/6001

Questions:
- [x] Will Mongo still be an option for Nutmeg installations? [Yes.](https://discuss.openedx.org/t/adr-for-removing-mongodb-from-edx-platform/6001/8?u=arbrandes)
- [ ] What is the migration path?

**Comment by arbrandes** [comment]
Dave pretty much [answered](https://discuss.openedx.org/t/adr-for-removing-mongodb-from-edx-platform/6001/8?u=arbrandes) the first question.  Yes, we will still have Mongo for Nutmeg.

As in, yes, we will still _have_ to use it.  It sounds like even if desired, one won't be able to do without it.
