### ISSUE TITLE
Cookie banner with hardcoded mention of edX

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#146]
The default cookie banner has a hardcoded mention of edX.

![image](https://user-images.githubusercontent.com/13796098/160465673-9a9fca77-2245-48a3-946f-5bf3f8ece162.png)

https://github.com/openedx/frontend-component-cookie-policy-banner/blob/a364669e259a2b8ab68d02004bf48197bb12344f/src/constants.js#L52

### Upstream issue

- [x] https://github.com/openedx/frontend-app-authn/issues/712

### Duplicate issues

- https://github.com/openedx/build-test-release-wg/issues/240

### PRs

- [x] https://github.com/openedx/frontend-app-authn/pull/707 (master)
- [x] https://github.com/openedx/frontend-app-authn/pull/713 (olive.master backport)

**Comment by ErdalDomi** [comment]
Hi @BbrSofiane, I was thinking to attempt this issue. The question is: what kind of context do we need to keep in mind to decide what string to show?

I was initially thinking to declare another constant array with the possible names instead of a hardcoded `edx`, however, it's not clear to me how the mechanism for switching would work. Is there another part of the code that gives information about what should be shown instead of `edx`?

**Comment by BbrSofiane** [comment]
Hi, @ErdalDomi thanks for volunteering for this issue!

I've seen [this](https://github.com/openedx/frontend-app-authn/blob/1c599d8d04e8b31062c0065d911fe92749349733/src/forgot-password/messages.js#L66) implementation on the authentication MFE. That's an option, it could be worth asking someone in the Frontend working group.

**Comment by ErdalDomi** [comment]
@BbrSofiane Thanks for the pointer. How do I get in touch with someone in the Frontend working group? The solution you suggested may work, however I'd like to double check

**Comment by BbrSofiane** [comment]
@ErdalDomi Have you managed to make any progress?

Here is another PR that fixes a similar issue: openedx/frontend-app-learning#945

**Comment by ErdalDomi** [comment]
Hi @BbrSofiane , 

Could you kindly unassign me from this issue? Unfortunately, due to a high workload, I am unable to devote the amount of time needed for the setup and development

**Comment by BbrSofiane** [comment]
No problem @ErdalDomi!

**Comment by bezalel001** [comment]
Hi @BbrSofiane 
 I would like to work on this, but the README states that the repo does not accept public contributions at this time

**Comment by BbrSofiane** [comment]
Thanks for you contribution @bezalel001! We'll use this as an opportunity to kickstart the conversation to make this repo available for contributions.

**Comment by arbrandes** [comment]
Assiging myself as a proxy for Zainab, who is tackling the issue as maintainer of the authn repo.  See [Slack conversation](https://openedx.slack.com/archives/C049JQZFR5E/p1670860847884129?thread_ts=1670847408.309689&cid=C049JQZFR5E).

**Comment by arbrandes** [comment]
This was fixed by https://github.com/openedx/frontend-app-authn/pull/707, but we still need to backport it to olive.master.
