### ISSUE TITLE
Authentication MFE - Hardcoded mentions of edX

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#147]
- [ ] [Password reset UI](https://github.com/openedx/frontend-app-authn/blob/1c599d8d04e8b31062c0065d911fe92749349733/src/forgot-password/messages.js#L87)

![image](https://user-images.githubusercontent.com/13796098/160601608-1cff2d8a-ae0d-49e7-a1e4-361cd5683a2e.png)

**Comment by BbrSofiane** [comment]
See =openedx/frontend-app-learning#945

**Comment by arbrandes** [comment]
It has been possible to change this for a while.  It's a configuration issue: what gets picked up is PLATFORM_NAME from the environment settings.
