### ISSUE TITLE
Warn about courseware_studentmodule index addition in Lilac release notes

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#15]
We should incorporate a warning and instructions about the following PR specifically in the release notes, including the fake migration idea:

https://github.com/edx/edx-platform/pull/26617

**Comment by arbrandes** [comment]
@pdpinch, do you mind assigning yourself to this one?  Of all the things that will go into the Release Notes, this is probably one of the most straight forward.

**Comment by pdpinch** [comment]
Will do. This one has actually been on my list.

**Comment by pdpinch** [comment]
Oh wait... I don't have the power to assign! I think I need the "triage" or the "admin" role in this repo is order to assign issues.

**Comment by arbrandes** [comment]
This is already in the draft release notes, so we can close the issue.
