### ISSUE TITLE
Include Authentication MFE in Nutmeg as "experimental"

### ISSUE THREAD

**Issue by kdmccormick** [openedx/build-test-release-wg#150]
## Context

See [this issue comment](https://github.com/openedx/build-test-release-wg/issues/142#issuecomment-1101448891).

In short: We want to tag the Authn MFE for Nutmeg, mentioning it in the release notes as an "experimental frontend", 

## Acceptance Criteria

1. In [frontend-app-authn](https://github.com/openedx/frontend-app-authn)'s openedx.yaml, delete the `maybe: true` line, so that the repo is automatically tagged in future releases.
2. Manually add the repo to Nutmeg by creating an `open-release/nutmeg.master` branch in [frontend-app-authn](https://github.com/openedx/frontend-app-authn)
3. Go through the release readiness checklist (below) for the Authn MFE. For each item, either (a) confirm that is already true, or (b) make it an action item on the ["Release Authn MFE in Olive"]() ticket.
   - [ ] Is there a DEPR ticket for the old frontend? 
   - [ ] How can we find out more about how the MFE works and what it does?
   - [ ] Is it enabled on edx.org today?
   - [ ] Is it brandable?
   - [ ] Is it localizable?
   - [ ] Does it support path-based routing?
   - [ ] Are there any constraints on the domain where the authn MFE is running?
   - [ ] Does it require migrating data for it to work on migrated sites?
   - [ ] Does it have feature parity with old authentication?
        - [ ] If not, what is missing? Is there a timeline for adding missing features (Olive, Poplar, etc.)?
        - [ ] If the missing features won't be added, are there DEPR tickets for them?
   - [ ] Does third-party authentication still work?
4. Coordinate with @waheedahmed to ensure that someone will complete ["Release Authn MFE in Olive"](https://github.com/openedx/build-test-release-wg/issues/151) by the Olive branch cut in October 2022.
5. Help @pdpinch add instructions for enabling the Authn MFE to the Nutmeg release notes.

**Comment by BbrSofiane** [comment]
@kdmccormick Is someone assigned to tag the MFE for Nutmeg?

**Comment by kdmccormick** [comment]
@BbrSofiane No, nobody is currently.

**Comment by BbrSofiane** [comment]
Thanks for this PR openedx/frontend-app-authn#588 @regisb and @kdmccormick
