### ISSUE TITLE
Discovery: How could we include new MFEs in releases without slowing down Tutor builds?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/build-test-release-wg#152]
## Context

The [tutor-mfe plugin](https://github.com/overhangio/tutor-mfe) is our method for including micro-frontends to the named releases. It currently builds four MFEs into its Docker image by default, leaving the end user the ability to build in extra MFEs. **Each additional MFE significantly increases the plugin's build time and image size.**

We need Open edX releases to work "out-of-the-box", so all MFEs that are required to in order for the platform to work need to be built into the tutor-mfe image by default.  As more MFEs become default and old frontends removed, the build time and size of the MFE image will continue to balloon.

In [this Nutmeg issue](https://github.com/openedx/build-test-release-wg/issues/142), we discussed whether the Authn MFE should be included in Nutmeg. One of the arguments against including it was that it'd increase tutor-mfe build time and size. Going forward, we'd like if this didn't need to be such a consideration.

The solution to this issue may be related to the [dynamic MFE config](https://github.com/openedx/frontend-wg/milestone/2) idea which is being floated at the frontend WG. There also may be salient points in the recent [MFE retrospective](https://discuss.openedx.org/t/microfrontends-a-retrospective/6486).

## Acceptance 

Investigate the problem and list potential solution(s).

**Comment by kdmccormick** [comment]
Since this is issue is a longer-term one and will require some discovery, I think it'd be fine to table it to post-Nutmeg.

**Comment by arbrandes** [comment]
eduNext is working on this, as outlined in [this exporation document](https://docs.google.com/document/d/1-FHIQmyeQZu3311x8eYUNMru4JX7Yb3UlqjmJxvM8do/edit).  (In particular, Epic 1.)

**Comment by kdmccormick** [comment]
Late update: This is being solved in time for Olive (🤞🏻) with:
* https://github.com/openedx/frontend-wg/issues/103 and
* https://github.com/openedx/wg-developer-experience/issues/87

Closing this since the discovery work has been done for a while.
