### ISSUE TITLE
Test Plan for Nutmeg and Beyond

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/build-test-release-wg#153]
The BTR WG was tasked with developing a **comprehensive** test plan to get Nutmeg ready for release. The test plan could be copied and used by anyone testing their own instances, and also as a basis for testing future Open edX® versions on the master branch. https://docs.google.com/spreadsheets/d/1A3LYVp9ivOLL1pj7eYeyel9zcxHM8BdQ_gVRpzMJqbU/edit#gid=1955774185

**Comment by kdmccormick** [comment]
FYI @BbrSofiane, after [we talked in Slack](https://openedx.slack.com/archives/C01AGTSB1LL/p1650463530107539) about how it'd be good to capture all non-code BTR work in GitHub, Dean retroactively made this issue.

**Comment by DeanJayMathew** [comment]
affects:nutmeg

**Comment by DeanJayMathew** [comment]
label: priority:high

**Comment by DeanJayMathew** [comment]
label: affects:nutmeg

**Comment by DeanJayMathew** [comment]
remove label: rity:high

**Comment by DeanJayMathew** [comment]
label: nutmeg testing

**Comment by DeanJayMathew** [comment]
label: type:bug

**Comment by DeanJayMathew** [comment]
remove label: type:bug

**Comment by DeanJayMathew** [comment]
remove label: affects:nutmeg

**Comment by DeanJayMathew** [comment]
label: affects:nutmeg

**Comment by NeOneSoft** [comment]
Hi amigo @DeanJayMathew!!! I was wondering if this issue should be still open. Thanks in advance!!!

**Comment by DeanJayMathew** [comment]
Hi @NeOneSoft I'm so sorry for the late reply my friend! I was not used to GitHub at that time. Let's close this yes!
