### ISSUE TITLE
Demo: add/remove labels by comment

### ISSUE THREAD

**Issue by sarina** [openedx/build-test-release-wg#154]

**Comment by sarina** [comment]
label: affects:nutmeg

**Comment by sarina** [comment]
label: affects:nutmeg

**Comment by sarina** [comment]
label: affects:nutmeg

**Comment by sarina** [comment]
label: help wanted

**Comment by sarina** [comment]
label: bad label name

**Comment by sarina** [comment]
remove label: help wanted

**Comment by sarina** [comment]
remove label: label: help wanted

**Comment by DeanJayMathew** [comment]
Hi @sarina  

That looks awesome! I tried to add labels myself but it's not working. Am I missing something?

<img width="497" alt="Screen Shot 2022-04-25 at 08 19 22" src="https://user-images.githubusercontent.com/9986523/165039559-98602b4a-a46c-4361-a37d-361e8678e0cd.png">

**Comment by sarina** [comment]
@DeanJayMathew it looks like the first one didn't work because you edited it (you have to get it right the first time, and it has to start with `label: `. The second one worked... kinda. It parsed it wrong, I don't know why.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1985317/165074546-6a4c3a05-2b4f-482e-86fa-978539bf71c1.png">

**Comment by DeanJayMathew** [comment]
@sarina that makes total sense, thank you.

**Comment by sarina** [comment]
@DeanJayMathew please make two separate comments. First one do:

`label: affects:nutmeg`

Second one do:

`remove label: rity:high`

**Comment by DeanJayMathew** [comment]
@sarina done

**Comment by sarina** [comment]
it works! 🎉 

Go forth and label!
