### ISSUE TITLE
Profile MFE has hardcoded mentions of edX

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#156]
The visibility message of profile fields has hardcoded mentions of "edX".

[Visibility.messages.jsx ](https://github.com/openedx/frontend-app-profile/blob/master/src/profile/forms/elements/Visibility.messages.jsx)

![image](https://user-images.githubusercontent.com/13796098/165072567-7e98d681-2879-4686-bcb6-6e1e25b4ef7b.png)

- [x] Merge https://github.com/openedx/frontend-app-profile/pull/543
- [x] Backport to nutmeg branch: openedx/frontend-app-profile#562

**Comment by mariajgrimaldi** [comment]
Hi! I believe that issue is resolved with [this](https://github.com/openedx/frontend-app-profile/pull/543). Should we tag someone for the review?

**Comment by BbrSofiane** [comment]
Yes, good spot! I can review it. We will also need to backport it to the nutmeg branch.

**Comment by mariajgrimaldi** [comment]
Hi! There's more reference to edX but in the learning MFE, [this PR](https://github.com/openedx/frontend-app-learning/pull/945) describes it. Should we solve that also?

**Comment by BbrSofiane** [comment]
Yes, can you open a separate issue for it? We will need to backport that PR to the nutmeg branch

**Comment by mariajgrimaldi** [comment]
There's already one: https://github.com/openedx/build-test-release-wg/issues/175
I mentioned the PR there also. Thanks!

**Comment by dcoa** [comment]
Hi @BbrSofiane this is the backport [PR](https://github.com/openedx/frontend-app-profile/pull/562)

**Comment by BbrSofiane** [comment]
Thank you @dcoa!
