### ISSUE TITLE
TC_AUTHOR_7 > Studio > Help > Page not exist

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#157]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to the help page

**Expected result:**
The Page should have valid content.
**Actual result:**
Page not exist error appears and redirected to https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-nutmeg.master/getting_started/CA_get_started_Studio.html

**Image:** 
<img width="1679" alt="Screenshot at Apr 26 15-51-38" src="https://user-images.githubusercontent.com/55684124/165295552-81f95594-5038-4860-9755-b16c39a31213.png">

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by awais786** [comment]
Invalid URL = https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-nutmeg.master/getting_started/CA_get_started_Studio.html

Valid URL = https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/getting_started/CA_get_started_Studio.html

Problem is `open-release-nutmeg.master` branch name.

**Comment by DeanJayMathew** [comment]
@awais786 @BbrSofiane @fayyazahmed66 this is similar to this issue: https://github.com/openedx/build-test-release-wg/issues/163

The result was that it should automatically be fixed when Nutmeg is released right?

**Comment by BbrSofiane** [comment]
I think so yes.

We should probably the test plan to reflect this. (Maybe we can have a couple of post-release tests)

**Comment by DeanJayMathew** [comment]
Hi @BbrSofiane 

This is now marked as Post-release test. We can think of a better way to mark them in the future but for now it's marked like this:

<img width="997" alt="Screen Shot 2022-05-29 at 14 27 42" src="https://user-images.githubusercontent.com/9986523/170871303-f4f32786-0839-4162-bc70-146435205f8b.png">
