### ISSUE TITLE
TC_AUTHOR_38 > Studio Outline > reindexing fails with Demo Course

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/build-test-release-wg#158]
### Description

I tested reindexing a course in nutmeg demo, and I got conflicting results:

Reindexing a course works for a brand new course ([Demo Course Honor](https://studio.nutmeg.demo.overhang.io/course/course-v1:edunext+EDNX-Demo-honor-2022+2022): with just one section):
![reindex-demo-honor](https://user-images.githubusercontent.com/64440265/165359091-84619666-acaa-498e-b653-7b805984f6a8.png)

But when trying to reindex the [Demonstration Course](https://studio.nutmeg.demo.overhang.io/course/course-v1:edX+DemoX+Demo_Course) (I imagine this course comes with the demo site) the page crashes -error 500-:
![reindex-demo](https://user-images.githubusercontent.com/64440265/165359176-c758a00f-c244-46c6-b4dd-b1e746ff8f72.png)

So I'm not sure if we can consider this a failure or if it's just an issue with the course -I don't know how to check without accessing the app logs-.

Can we have access to those? :thinking: 

### How to reproduce
- Login as the admin user
- Enter the course outline
- Reindex course

**Comment by mariajgrimaldi** [comment]
"label: nutmeg testing"

**Comment by mariajgrimaldi** [comment]
"label: nutmeg testing"

**Comment by mariajgrimaldi** [comment]
how do I add labels? :sweat_smile:

**Comment by DeanJayMathew** [comment]
Hey! Seems you used inverted commas. You should not use inverted commas.

See the test sheet README tab, Step 6.

**Comment by DeanJayMathew** [comment]
label: nutmeg testing

**Comment by DeanJayMathew** [comment]
label: affects:nutmeg

**Comment by DeanJayMathew** [comment]
label: type:bug

**Comment by mariajgrimaldi** [comment]
Thanks @regisb :1st_place_medal: 

The issue is with transcripts for each and every video in the course :thinking::
![transcript-not-found](https://user-images.githubusercontent.com/64440265/168919211-39d6689a-f998-4aac-9032-c50e5bbb9b15.png)

I fixed each one of them removing the component and adding it again with the video URL. Then, reindexing the course seemed to work. I also exported the course and imported it again to see if the issue re-appeared and it didn't. So I imagine this was an error with the course itself. What do you think?

**Comment by regisb** [comment]
Yes, I'm pretty sure that the demo course is kinda broken. I'm getting warnings related to transcripts every time I import it. I believe that the root cause is that transcripts are actually media files which are not exported with the course -- which is a problem in its own right, but an entirely different one.

**Comment by mariajgrimaldi** [comment]
I'm going to close this issue since reindexing course failed just with this course -and it worked after we fixed it-.

Thanks for the help!

**Comment by DeanJayMathew** [comment]
In the test sheet, I've marked this test case as Passed, and marked the GitHub issue as Resolved.
