### ISSUE TITLE
TC_AUTHOR_148 > Studio > Unit > Discussion > Component is giving error where discussion is added

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#160]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click on add unit 
4. add discussion unit
5. View live this unit

**Expected result:**
Content should be visible on the page.
**Actual result:**
Getting error for discussion

Image: 
<img width="1679" alt="discussion" src="https://user-images.githubusercontent.com/55684124/165487754-719aed10-eb05-488d-819e-4eb5b30d9fa8.png">

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by sambapete** [comment]
The forum plugin has not been updated to Nutmeg yet.

**Comment by regisb** [comment]
Can you try again now that the forum plugin has been enabled?

**Comment by ghassanmas** [comment]
I tested again and this should be fixed now. @fayyazahmed66 would you want to test it yourself again before closing it

**Comment by DeanJayMathew** [comment]
Thank you @ghassanmas I concur this is fixed.

@BbrSofiane kindly close this at your earliest convenience before 31 May pretty please.

**Comment by DeanJayMathew** [comment]
I've marked this as Passed and Resolved in the sheet.
