### ISSUE TITLE
TC_AUTHOR_37: STUDIO: CONTENT: OUTLINE: Learn more buttons

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/build-test-release-wg#163]
**Steps to reproduce:**

Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
Go to any course
Go to course outline
Click the three (3) learn more buttons on the right hand side of the page

**Expected result:**
Buttons should link to the correct page in documentation

**Actual result:**
Error maze shows

<img width="995" alt="Screen Shot 2022-04-27 at 11 49 48" src="https://user-images.githubusercontent.com/9986523/165502957-d349d06f-450a-4ad8-8e8e-6a4093bb3895.png">

**Comment by DeanJayMathew** [comment]
label: affects:nutmeg

**Comment by DeanJayMathew** [comment]
label: type:bug

**Comment by DeanJayMathew** [comment]
label: nutmeg testing

**Comment by ghassanmas** [comment]
This is beacuse nutmeg release isn't avaiable at https://edx.readthedocs.io/ , for example if you would replace nutmeg with maple in the url, it will okay. 
So I guess we should know weather edx.readthedocs.io/ will have a release for nutmeg at readthedocs for nutmeg, like is it a time issue or this will no loger be the case given the changes of the documentation.

**Comment by DeanJayMathew** [comment]
Thank you.

@feanil I was just wondering, since you are creating new docs for Open edX (i.e. not edx.readthedocs) will the function described by Regis above still work? As in, when we release Nutmeg, Olive etc, will the Learn More buttons in Studio update to the latest docs when they're under openedx.readthedocs?

**Comment by DeanJayMathew** [comment]
I have updated this as a **Post-release test** in the sheet.

**Comment by feanil** [comment]
@DeanJayMathew yes, the button should go to a page on the new site once the relevant content has been moved.  But we're not ready to do that yet so it should still get published to the old location for now.
