### ISSUE TITLE
TC_AUTHOR_133: STUDIO: SETTINGS: ADVANCED: Course visibility in catalog

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/build-test-release-wg#164]
**Steps to reproduce:**

Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
Go to Advanced Settings: Course Visibility in Catalog
Set to "none":

<img width="928" alt="Screen Shot 2022-04-27 at 12 57 08" src="https://user-images.githubusercontent.com/9986523/165513236-3fa90484-1408-49f7-ba8e-7a4de21e682f.png">

**Expected result:**
Go to **https://nutmeg.demo.overhang.io** and the course should NOT be visible.
Go to **https://nutmeg.demo.overhang.io/courses** and the course should NOT be visible.

**Actual result:**
Course is NOT visible on **https://nutmeg.demo.overhang.io** <-- this is good
Course is still visible on **https://nutmeg.demo.overhang.io/courses** **<-- this is the bug**

<img width="473" alt="Screen Shot 2022-04-27 at 12 56 58" src="https://user-images.githubusercontent.com/9986523/165513207-d1abc730-67ad-49b5-adda-9453ca9b913a.png">

**Comment by DeanJayMathew** [comment]
label: testing nutmeg

**Comment by ghassanmas** [comment]
I was trying to debug this, and I think simliar issue was raised in tutor forum before[^1]. However in the forum thread, it was resolved by disabeing the discovery service, where in nutmeg discovery is enabled. 

However I wasn't sure if the "Course visibility in catalog"  affects **discovery service**? I couldn't find any documentation about that explicitly. @regisb do you have any though on this? 
 

[^1]: https://discuss.overhang.io/t/catalog-visibility-in-tutor-deployed-open-edx/214

**Comment by ghassanmas** [comment]
Also to confirm what @DeanJayMathew have repoted: 

>Course is NOT visible on https://nutmeg.demo.overhang.io/ <-- this is good
Course is still visible on https://nutmeg.demo.overhang.io/courses <-- this is the bug
The first case it worked becasuse the result wasn't retrived by discovery/search service while second failed because it gets from discovery service

**Comment by DeanJayMathew** [comment]
@ghassanmas 

Thank you for debugging this, well noted. 

The Discovery service is an important service we use in almost all our separate instances. So for me it's a high priority. I will speak to my colleagues for their input too since they are experienced in this discovery service.

Let's aim to resolve this ticket this week.

**Comment by regisb** [comment]
@DeanJayMathew I'm not sure if this question can be resolved by next week, or even whether it's an actual issue at all. Let me refer to my answer to that forum topic : https://discuss.overhang.io/t/catalog-visibility-in-tutor-deployed-open-edx/214/6?u=regis

> /courses is _not_ the catalog, and the courses that are displayed there are unaffected by the visibility settings from the advanced settings. If you’d like to disable this page entirely, then you need to set FEATURES["ENABLE_COURSE_DISCOVERY"] = False in the lms settings.

In other words, the "course visibility in catalog" does NOT refer to the listing in the /courses page. It's very weird, but that's the way it has been since, well forever. If you ask me, I think that this advanced setting should indeed govern the course listing in /courses. We should simply be aware that this would not classify as a "bug fix" but a "breaking change feature".

**Comment by NeOneSoft** [comment]
Hi @ghassanmas !!!! do we have any update regarding this issue? Thanks in advance

**Comment by ghassanmas** [comment]
@NeOneSoft Yes I will comment below the summary of the finding. _I will just re post what I already repoted in the forum the forum_. 
> On the other hand, while I was going over testing for my changes, I find that edx-search has a setting for overriding filter class, and the LMS does override it and it use this filter instead [edx-platform/lms_filter_generator.py at a27247d14d2b77234fd004988f96258e29d0d000 · openedx/edx-platform · GitHub](https://github.com/openedx/edx-platform/blob/a27247d14d2b77234fd004988f96258e29d0d000/lms/lib/courseware_search/lms_filter_generator.py#L44-L61) . And filter shuold skip course visibility to none if SEARCH_SKIP_SHOW_IN_CATALOG_FILTERING = False. I am not 100% sure about that, since I just found about it and didn’t test it yet. [ref](https://discuss.openedx.org/t/request-for-feedbak-breaking-changes-for-course-visibility/7341/6?u=ghassan)
 
Given the above finding, tutor was changed to use that flag by [default](https://github.com/overhangio/tutor/blob/c4388e134ca4bf1961b9906dd3fb8600d197f7a5/tutor/templates/apps/openedx/settings/partials/common_lms.py#L25-L26). 

Note using that flag, would enable to hide the course if the settings is "none" only. It won't work for "about".

**Comment by NeOneSoft** [comment]
Thank you so much @ghassanmas for your update here!!!
