### ISSUE TITLE
TC_AUTHOR_110 > Studio > Settings > schedule > Cant find set certificate available date and time field

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#165]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click settings menu and select schedule 
4. Check certificate time field

**Expected result:**
There should be set certificate available date and time field
**Actual result:**
No certificate available date field found

Image: 
<img width="1671" alt="Screenshot at Apr 27 16-57-23" src="https://user-images.githubusercontent.com/55684124/165514024-a4312bb3-d1d6-497f-b3af-a585b14f7321.png">

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by sambapete** [comment]
As far as I know, the ecommerce MFE is not being enabled right now as of 2022-05-02. Therefore no courses currently have a mode that offers certificates. Maybe we need to be able to turn on certificates for a course first before seeing the dates?

**Comment by mariajgrimaldi** [comment]
Hi! After researching a bit, I found [this](https://github.com/edunext/edx-platform/blob/8a2d6835208303deb24f95ad2d8729bf5af8bf29/lms/djangoapps/courseware/date_summary.py#L480), and with a course with: 
- Certificate modes
- Active web certs
- Instructor paced
- Auto certificate generation enabled
It worked:
![image](https://user-images.githubusercontent.com/64440265/168389557-868b82f6-02ec-4616-97fc-291ef13d9422.png)

You can see it here: https://studio.nutmeg.demo.overhang.io/settings/details/course-v1:edunext+cert-demo-1+2022

**Comment by DeanJayMathew** [comment]
@***@***.*** ***@***.***>

You're becoming a certificates master :)

**Comment by BbrSofiane** [comment]
Can I confirm that we can close this issue? @mariajgrimaldi

**Comment by mariajgrimaldi** [comment]
Yes! I believe so @BbrSofiane
