### ISSUE TITLE
TC_AUTHOR_88 Upload files to course

### ISSUE THREAD

**Issue by ghassanmas** [openedx/build-test-release-wg#166]
I wasn't able to test files uploads in studio for any course, this due a bug where certian statics files wan't served i.e. 404 return error. 

Please Note: since this test fails it also going to block the testing for TC_AUTHOR_88 to TC_AUTHOR_102. Sice it's even not possible to try to upload any file. it's just a blank page.

This issue is not new was repoted in tutor forums before, please check the resources below. 

1- https://discuss.overhang.io/t/missing-js-css-files-missing-from-openedx-docker-image-in-studio/2629/18
2- https://discuss.overhang.io/t/files-uploads-page-is-blank/2631/3 

![image](https://user-images.githubusercontent.com/16361375/165650365-8793663c-c3b1-4011-9124-2a143f3dc2c1.png)

**Comment by ghassanmas** [comment]
A PR that might solve is open here https://github.com/openedx/edx-platform/pull/30309

**Comment by ghassanmas** [comment]
Also possible root fix is proposed at openedx/studio-frontend#341

**Comment by ghassanmas** [comment]
Since this https://github.com/openedx/studio-frontend/pull/341 is merged and also tutor has cherry picked this https://github.com/openedx/edx-platform/pull/30309 . I think its safe to close this

**Comment by DeanJayMathew** [comment]
This is now marked as Passed and Resolved in the test sheet.
