### ISSUE TITLE
LMS: COURSE HOME: PROGRESS: View and download certificate

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/build-test-release-wg#167]
### Description
Downloading a certificate is not working
https://user-images.githubusercontent.com/64440265/166333681-cc35cddb-77d1-4b7e-ab64-d47f4745ffb9.mp4

### How to replicate
1. Create a course for certificate generation. You could use [this](https://apps.nutmeg.demo.overhang.io/learning/course/course-v1:edunext+course-cert-1+2022/home) one.
[course_codejail_example.tar.gz](https://github.com/openedx/build-test-release-wg/files/8606187/course_codejail_example.tar.gz)
2. Configure a certificate for instructor paced: 
- Create course mode honor
- Activate certificate
- Certificates Downloadable Before End in the deprecated advanced settings
- Disable Certificate Web/HTML View Enabled in the deprecated advanced settings
- Certificate auto generation
3. Pass the course
4. Try to download the certificate

I'll be resarching what could be happening

**Comment by mariajgrimaldi** [comment]
label: affects:nutmeg

**Comment by mariajgrimaldi** [comment]
label: type:bug

**Comment by mariajgrimaldi** [comment]
label: nutmeg testing

**Comment by regisb** [comment]
This is almost certainly because persistent grades are not enabled by default. This will change in nutmeg. Assigning this to myself to implement the change.

**Comment by mariajgrimaldi** [comment]
I believe I misunderstood this issue and tried to force the "Download Certificate" page, and that happens only when disabling web-html certificates according to this [line](https://github.com/openedx/frontend-app-learning/blob/1e41547b3e456acd6a7b6d37f8360b6bdb70e0f6/src/courseware/course/course-exit/CourseCelebration.jsx#L109) in the learning MFE. The issue is that PDF certificates are long gone according to the DEPR ticket :thinking: 

Now that I found that out I don't think there's something wrong with this test at all, what do you think? should we close this issue?

**Comment by regisb** [comment]
Hi @mariajgrimaldi! So you are saying that pdf certificates are deprecated but the advanced setting to generate pdf certificates is still there? ("Disable Certificate Web/HTML View Enabled in the deprecated advanced settings") It seems to me that this setting should be removed.
