### ISSUE TITLE
TC_LEARNER_23:LMS:PROFILE:View my records button

### ISSUE THREAD

**Issue by NeOneSoft** [openedx/build-test-release-wg#168]
### Description
View my records button is not visible in /profile as usually
### How to replicate
1.- Sign in to test nutmeg instance as admin or staff(https://nutmeg.demo.overhang.io/)
2.- Click profile on right top corner user menu:
![Screenshot from 2022-05-03 09-11-51](https://user-images.githubusercontent.com/53199845/166469840-399f4191-c44c-4ff4-ab7b-85cd4b67df71.png)
### Expected result
Something similar to:
![Screenshot from 2022-05-03 09-11-59](https://user-images.githubusercontent.com/53199845/166469889-b5acc36b-f812-4ead-b87f-6b3cb6f30308.png)

**Comment by NeOneSoft** [comment]
label: affects:nutmeg

**Comment by NeOneSoft** [comment]
label: nutmeg testing

**Comment by ghassanmas** [comment]
A PR with possible fix  overhangio/tutor-mfe#51 (need to be cherry-picked to nutmeg)

**Comment by DeanJayMathew** [comment]
Brilliant machos! Well done! Great effort.

**Comment by regisb** [comment]
From what I can see, the records button is not enabled, although the fix was deployed on nutmeg.demo.overhang.io. @ghassanmas are you quite sure that your PR is actually fixing this issue?

**Comment by ghassanmas** [comment]
@regisb Yes you are right, it needs to have `LEARNER_RECORD_MFE_BASE_URL` and ifs its not defined it will try to get `CREDENTIALS_BASE_URL` which is empty by deafult in tutor. 
So to fix tutor-mfe should by have a default value for `LEARNER_RECORD_MFE_BASE_URL` or `CREDENTIALS_BASE_URL`. 
I can fix this with another PR but not sure what should be we use here, should this deafult to LMS_BASE? or is tied with ecommerce service

**Comment by ghassanmas** [comment]
So after doing some investgation here is what I found:

There are two scinarios for the button:
 - It would redirect to the learner-record MFE, if `EARNER_RECORD_MFE_BASE_URL`
   - This expects the [frontend-app-learner-record](https://github.com/edx/frontend-app-learner-record), which to my knowledge isn't a standard MFEs, nor is it a default/necessary MFE that comes with tutor-mfe
- It would redircts creditnals service if `CREDENTIALS_BASE_URL` is set _which what is happening on edx.org_. 

That being said do we expects different redirection beside the two scinarios above? if not, then I don't think the button being hidden suppose to be a bug after all, given our nutmeg instance doesn't have credintals serivce or nor there the record MFE.

It should be known at least for SysAdmin/DevOps who are enabling this service that these settings are needed in MFE profile.
