### ISSUE TITLE
TC_AUTHOR_72 > Studio > Xblock > pdf > Xblock is not appearing under advance xblock list

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#169]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click on add unit
4. Go to advance setting under settings dropdown and then add "pdf" in the list and save it
5. Check pdf xblock under advance xblocks list
**Expected result:**
Xblock should be available under advance xblock list
**Actual result:**
Xblock is not available under advance xblock list

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by DeanJayMathew** [comment]
This XBlock like many others needs to be manually installed because it's not a default feature.
