### ISSUE TITLE
Ignore this, just testing

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#17]
Hey, @kdmccormick, ignore this, I'm trying to reverse-engineer how GitHub offers type-ahead.

**Comment by nedbat** [comment]
@kdmccormick, actually if you don't mind, could you make a comment on this issue?

**Comment by nedbat-test-committer** [comment]
Hi, I'm new here, what's up?

**Comment by regisb** [comment]
FINALLY Ned managed to automate himself!
