### ISSUE TITLE
TC_AUTHOR_82 > Studio > Updates > Add handouts > Added Handouts are not showing on course detail

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#170]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Update menu button
4. Click on edit handout button
5. Save handouts 
6. check on home page of course in lms 
**Expected result:**
handouts should be showing
**Actual result:**
Handouts are not showing.
SS: 
<img width="1679" alt="Screenshot at May 08 16-48-13" src="https://user-images.githubusercontent.com/55684124/167294780-a8caf850-59ed-4e66-969f-5d1af2536987.png">

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by mariajgrimaldi** [comment]
I couldn't either. Do you by chance, have the course zip file so we can test it?

**Comment by DeanJayMathew** [comment]
This is working: https://apps.nutmeg.demo.overhang.io/learning/course/course-v1:ABC+ABC+ABC/home

@BbrSofiane pretty please close this.
