### ISSUE TITLE
TC_LEARNER_25:LMS:COURSEABOUTPAGE:Share course by Facebook 

### ISSUE THREAD

**Issue by NeOneSoft** [openedx/build-test-release-wg#174]
### Description
When you try to share the course from about page the link shows the next error:
![Screenshot from 2022-05-09 06-04-42](https://user-images.githubusercontent.com/53199845/167397545-2f361829-fff7-423d-9358-03e79a52b774.png)

### How to replicate

1.- Select one course from https://nutmeg.demo.overhang.io/ and try to share it using the facebook icon located in the about page
![Screenshot from 2022-05-09 06-08-37](https://user-images.githubusercontent.com/53199845/167398020-e4611fa6-73ea-475c-9d37-2b611bee9c71.png)

**Comment by ghassanmas** [comment]
Possible PR to fix https://github.com/openedx/edx-platform/pull/30389

**Comment by DeanJayMathew** [comment]
Looking forward to seeing this fix merged. https://github.com/openedx/edx-platform/pull/30389

Thanks @ghassanmas you really know your way around Open edX in such a short time. We should write a blog about you!
