### ISSUE TITLE
The student onboarding screen includes a hardcoded mention to edX in the learning MFE

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#175]
When signing up as a new user in the LMS, we are presented with an onboarding screen which includes a hardcoded mention of "edX". See the screenshot below.

![Screenshot from 2022-05-10 12-16-09](https://user-images.githubusercontent.com/44319/167613111-d6dbb0ab-56a8-4bd5-90b1-cdb376e0ee37.png)

FYI this issue was detected during a live stream: https://www.youtube.com/watch?v=28_lt90UREo (at about 1:58:00).

**Comment by mariajgrimaldi** [comment]
Hi! I believe [this issue](https://github.com/openedx/frontend-app-learning/pull/945) fixes that! Who should we mention?

**Comment by BbrSofiane** [comment]
Approved and merged.

**Comment by BbrSofiane** [comment]
Can someone backport it to nutmeg?

**Comment by mariajgrimaldi** [comment]
@BbrSofiane we're working on it!

**Comment by mariajgrimaldi** [comment]
Here's the backport: https://github.com/openedx/frontend-app-learning/pull/947

**Comment by BbrSofiane** [comment]
I've merged it

**Comment by BbrSofiane** [comment]
Can someone confirm that the issue is fixed on the demo instance?

**Comment by mariajgrimaldi** [comment]
I'll do it! @BbrSofiane

**Comment by regisb** [comment]
We almost certainly have to re-build the MFE image on the server to pick up the latest changes. I'm doing it right now.

**Comment by mariajgrimaldi** [comment]
It's working now!
![image](https://user-images.githubusercontent.com/64440265/170039155-d726fb97-13bc-44ad-8eef-d7eff4813abd.png)
We can close this :smile:
