### ISSUE TITLE
Tag Course Authoring MFE for nutmeg

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#181]
The course authoring MFE was released on edx.org before nutmeg was cut.

We can't make it a supported part of the nutmeg release, but we'd like to include it as an experimental feature. To do this, we need to:

- [ ] add a yaml tag in the repo https://github.com/openedx/frontend-app-course-authoring
- [ ] add a `nutmeg.master` branch in the repo https://github.com/openedx/frontend-app-course-authoring

**Comment by BbrSofiane** [comment]
Would additional permissions be required to create the nutmeg branch? And does a core commiter have those permissions?

**Comment by pdpinch** [comment]
@nedbat or @sarina do you know the answer to Sofiane's question?

**Comment by sarina** [comment]
Core committers to a repo have permissions to make a branch in that repo. I could do it for you; @xitij2000 is also a CC on that repo.

**Comment by BbrSofiane** [comment]
Thanks, @sarina!

We need to do the same for the other MFEs (I think the discussion MFE but I might be wrong on the specific MFE...) so I was also trying to figure out a sustainable way of doing it in the future. I think relying on CCs (or maintainers in the future) makes sense.

@xitij2000 can you take on this issue?

**Comment by sarina** [comment]
Agreed, @BbrSofiane . Discovering what repos need tagging but lack a CC would perhaps spur us to try to identify candidates for CC in that area.

**Comment by nedbat** [comment]
Sorry I missed this ping.  Does this still need to happen?

**Comment by xitij2000** [comment]
> Thanks, @sarina!
> 
> We need to do the same for the other MFEs (I think the discussion MFE but I might be wrong on the specific MFE...) so I was also trying to figure out a sustainable way of doing it in the future. I think relying on CCs (or maintainers in the future) makes sense.
> 
> @xitij2000 can you take on this issue?

Sure, I can take this on.

**Comment by nedbat** [comment]
> figure out a sustainable way of doing it in the future

@BbrSofiane Isn't this solved by putting the right metadata in the openedx.yaml file?  Or by "doing it" do you mean fixing up missed branches after they should have been made?

**Comment by BbrSofiane** [comment]
@nedbat I mean more of the latter for future new repositories to add to the default Open edX deployment. So right now it looks like:
1. Notify the repo maintainer
2. Update openedx.yaml
3. If applicable, create missing branches

**Comment by nedbat** [comment]
Yes, that's roughly the process.  "Notify" might be "Ask" or "Consult with", but yes.

**Comment by BbrSofiane** [comment]
Closed with https://github.com/openedx/frontend-app-course-authoring/commit/2f168034847d4c078c4fdc2ef8f580e0069bda4b
