### ISSUE TITLE
Proposed backport for nutmeg Open edX Filters last batch

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/build-test-release-wg#187]
Hello everyone! 

### Description

I'm opening this issue as a proposal for a backport to the latest release nutmeg, consisting of a few filters integrations that didn't make the nutmeg cut (for a variety of reasons):

> **Add filter before certificate creation starts**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/e8fa890af7aa9f03dd15013117ca87948cb3967f)
> 
> **Add cohort change filter before moving users from cohorts**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/465e5c02dd2bdde7f9590b51ff7bfc298a34dbbe)
> 
> **Add filter before certificate rendering process starts**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/7f974d1fffea5cfcc1c8cec8ee41de24f886c61f)
> 
> **Add filter before course dashboard rendering process starts**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/895a64928626760076650b923ced430349b182c7)
> 
> **Add filter before course about rendering process starts**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/ccfa0b484b5122e901087ed08dd0f468b51dd426)
> 
> **Integrate cohort assignment filter definition to cohort model**
> 
> (cherry picked from commit https://github.com/openedx/edx-platform/commit/ec69659253060aaaf398eb90d4f64deb569f3201)

[This](https://github.com/openedx/edx-platform/pull/30583) is the PR with those commits targeting nutmeg.

We are eager to know if these changes that the BTR wg would consider acceptable. I hope this is the right channel to start a discussion.

### Rationale

Some weeks back, the BTR group and @FelipeMontoya discussed having this functionality in nutmeg, given that we were not going to be able to meet the deadline of the cut -for multiple reasons, mainly the feedback process of each implementation-. So we're pushing this forward since this functionality is vital for the platform extension. 

### Consequences

If a filter is not configured, then it acts like a no operation. So the platform can still operate as usual.

**Comment by felipemontoya** [comment]
I'd like to add some of the previous reasons why we advocated to port this back to nutmeg.
The reason for the hooks framework is to generally allow for more maintainable extensions of the platform and reduce the necessity for some many forks out there.

Given the recent presentation of this framework in the conference and the hype we tried to build around it, we would like for devs to get their hands on this as soon as reasonable. Asking them to target master is not reasonable and waiting for olive seems like a missed opportunity for all the features that could already be built on top of a stronger foundation. Given that this change does not change anything in the data scheme and that ignoring it does not change anything in the platform's behaviour, we think is a good candidate for backporting.

**Comment by felipemontoya** [comment]
@BbrSofiane would it make sense to tag this as "nutmeg release" ?

**Comment by BbrSofiane** [comment]
Yes, I will assign it to the Nutmeg.2 Milestone. 

We can also cherry-pick the change in tutor to make it available before the official release of Nutmeg.2 (9th of August).

**Comment by mariajgrimaldi** [comment]
Hello! After the last (august 1st) BTR meeting, @NeOneSoft and @jfavellar90 reached out to me to know the extent of reviewing this issue; after explaining, they agreed to help us move forward. We had a meeting where we tested all six filters and we documented each step:

First, we set up the environment with the branch [MJG/backport-filters](https://github.com/openedx/edx-platform/pull/30583) rebased on the latest Nutmeg release tag (nutmeg.master). Then, we installed the required packages:
1. Latest release of the openedx-filters package 0.7.0, this library has all the six definitions we include here.
`pip install openedx-filters==0.7.0`
2. Master branch of the library where we implemented all steps definitions:
` pip install git+https://github.com/eduNEXT/openedx-filters-samples.git@master#egg=openedx_filters_samples`
And we tested each filter one by one with the following configuration:

```
OPEN_EDX_FILTERS_CONFIG = {
    "org.openedx.learning.certificate.creation.requested.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.StopCertificateCreation"
        ]
    },
    "org.openedx.learning.cohort.change.requested.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.StopCohortChange"
        ]
    },
    "org.openedx.learning.certificate.render.started.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.RenderAlternativeCertificate",
        ]
    },
    "org.openedx.learning.dashboard.render.started.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.RenderAlternativeDashboard",
        ]
    },
    "org.openedx.learning.course_about.render.started.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.RenderAlternativeCourseAbout",
        ]
    },
    "org.openedx.learning.cohort.assignment.requested.v1": {
        "fail_silently": False,
        "pipeline": [
            "openedx_filters_samples.samples.pipeline.StopCohortAssignment"
        ]
    },
}
```
Detailed explanation:

1. Certificate creation filter: after creating a course & setting up its certificates, we generated one certificate. Since the filter step -check implementation [here](https://github.com/eduNEXT/openedx-filters-samples/blob/master/openedx_filters_samples/samples/pipeline.py#L23)- was implemented to stop the generation process, bad request 400 was returned to the learning MFE:
![cert-creation-stop-step](https://user-images.githubusercontent.com/64440265/183218609-02ed8992-e2f0-4d1e-b5c0-9bb7affc2d54.png)

2. Certificate render filter: we removed the configuration for the certificate creation and generated a certificate. Since the filter step was implemented -check implementation here- to stop the rendering process & render an invalid certificate:
![certificate-render-stopped](https://user-images.githubusercontent.com/64440265/183218719-24af770f-f469-447e-b792-c848bbe2995e.png)

3. Dashboard render filter: we then went to the dashboard. And since the filter step -check implementation [here](https://github.com/eduNEXT/openedx-filters-samples/blob/master/openedx_filters_samples/samples/pipeline.py#L319)- was implemented to stop the generation process & render the 404 not found template:
![dashboard-filter-render-404](https://user-images.githubusercontent.com/64440265/183218786-c9e41477-da3b-484c-abbc-06ddea1db4f3.png)

4. Course about render filter: then we went to a course about an existent course. And since the filter step -check implementation [here](https://github.com/eduNEXT/openedx-filters-samples/blob/master/openedx_filters_samples/samples/pipeline.py#L428)- was implemented to stop the rendering of the course about replacing the fragment with the 404 not found template:
![course-about-stopped](https://user-images.githubusercontent.com/64440265/183219112-7be9e884-334c-4a81-9734-5434df961e02.png)

5. Cohort assignment render filter: as an instructor of the course, we went to the instructor panel. Since the filter step -check implementation [here](https://github.com/eduNEXT/openedx-filters-samples/blob/master/openedx_filters_samples/samples/pipeline.py#L708)- was implemented to stop the cohort assignment of a user:
![cohort-assignment-stop](https://user-images.githubusercontent.com/64440265/183219465-9693b95b-fbb0-4b47-981d-0b702796483c.png)

6. Cohort change render filter: as an instructor of the course, we went to the instructor panel. Since the filter step -check implementation [here](https://github.com/eduNEXT/openedx-filters-samples/blob/master/openedx_filters_samples/samples/pipeline.py#L687)- was implemented to stop the cohort change of a user from a cohort to another:
![cohort-change-stop](https://user-images.githubusercontent.com/64440265/183219275-29ba5848-9734-4741-b566-8e626a615cce.png)

Since the implementation of these PR(s) were already reviewed & supervised when targeting master, the objective of this exercise was to test the filter's functionality in the nutmeg context.

What do you think? @BbrSofiane

**Comment by BbrSofiane** [comment]
Hey, @mariajgrimaldi looks good to me!

I didn't know we would have filters that can alter the render cycles at this stage. That's pretty cool!

Can you use the dashboard to redirect to say a dashboard MFE?

**Comment by mariajgrimaldi** [comment]
Yes @BbrSofiane, you could use a filer like this:
```
class RedirectDifferentDashboard(PipelineStep):

    def run_filter(self, context, template_name):
        raise DashboardRenderStarted.RedirectToPage(
            "Redirecting to the dashboard MFE.",
            redirect_to="https://mfe-dashboard.com",
        )
```
And this configuration:

OPEN_EDX_FILTERS_CONFIG = {
    "org.openedx.learning.dashboard.render.started.v1": {
        "fail_silently": False,
        "pipeline": [
            "path.to.plugin.RedirectDifferentDashboard",
        ]
    },
}

To modify the dashboard rendering workflow

**Comment by BbrSofiane** [comment]
I merged the PR. Thank you @NeOneSoft @jfavellar90 and @mariajgrimaldi

**Comment by mariajgrimaldi** [comment]
Thank you guys! :heart:

**Comment by NeOneSoft** [comment]
Thank you all!!! @BbrSofiane @mariajgrimaldi @jfavellar90 !!!
