### ISSUE TITLE
Test koa.master before tagging as koa.3

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/build-test-release-wg#19]
On ~~March 10~~ April 9 we need to test the deployment of the latest `koa.master` branch.

TODO:
- add DoD of the task

**Comment by nedbat** [comment]
Why March 10th?  Koa.3 should be tagged on April 9th.

**Comment by BbrSofiane** [comment]
@cmltaWt0 Do you have any updates on this issue?

**Comment by cmltaWt0** [comment]
@BbrSofiane koa.master deployment is tested once a week.This week Im working on terraform app for automatic instastructure deployment and edx provision

**Comment by BbrSofiane** [comment]
Thanks @cmltaWt0, this might actually be useful to bring it up in the conversation for openedx/community-wg#14.

**Comment by BbrSofiane** [comment]
@cmltaWt0 Can this be closed?

**Comment by cmltaWt0** [comment]
> @cmltaWt0 Can this be closed?

Yes for now. Testing is done.
Attempt to add autotesting and infrastructure deployment will be done in another task.
