### ISSUE TITLE
Migrate BTR Project to new Project type

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#190]
Migrate BTR Project to new Project type

**Comment by nedbat** [comment]
I think you have to enable project migration as a feature preview (on the drop-down menu from your profile pic), then you get a green Start Migration button on the project.

**Comment by BbrSofiane** [comment]
I need an Org owner to switch the board to public. cc @kdmccormick 

![image](https://user-images.githubusercontent.com/13796098/182533374-66b7a942-4ffe-425a-b00a-f7e31581f0e8.png)

**Comment by kdmccormick** [comment]
All set @BbrSofiane
