### ISSUE TITLE
Nutmeg.2 Release

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#194]
Create Nutmeg.2 Tag across Open edX repositories.

Assigned on [this meeting](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3497328641/2022-08-01+BTR+Meeting+Notes).

**Comment by arbrandes** [comment]
@nedbat, would it be too much to ask you to be the adult in the room for this one, too? :)  Do you happen to have a slot available on Tuesday?

**Comment by nedbat** [comment]
11am Eastern time?

**Comment by arbrandes** [comment]
Works for me!

**Comment by arbrandes** [comment]
Done!  The following is a record of what @nedbat and I did, today:

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3506601989/Nutmeg.2
