### ISSUE TITLE
"Sign in with your company or school" link on registration page needs more finesse

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#2]
Should this link appear on Open edX sites? Under what conditions? Where should it go?

https://openedx.atlassian.net/browse/BTR-52

**Comment by cmltaWt0** [comment]
PR review in progress.
https://github.com/edx/edx-platform/pull/27130

**Comment by BbrSofiane** [comment]
This just needs to be cherry picked on lilac.master

**Comment by BbrSofiane** [comment]
@cmltaWt0 Just a reminder to get this onto lilac.master :)

**Comment by cmltaWt0** [comment]
@BbrSofiane yeeap :) 
Thanks! Actually I've planned this for today's work.

**Comment by pdpinch** [comment]
I merged the backport to lilac.
