### ISSUE TITLE
Identify in-progress work that won't land before Lilac is cut

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#20]
The BTR working group has proposed cutting the lilac release on April 9 instead of the planned May 9, in order to provide more time for testing before the official June 9 release date. 

We would like to know if there are any PRs, epics or features in progress that would be missing from Lilac if we cut the release April 9 instead of May 9.

**Comment by pdpinch** [comment]
This is a harder question to answer than I had originally thought. I've collected a list of features that I believe are in progress, but it's hard to tell when they will land. I think each of these would only affect our decision 1) if they will land after April 9 but before May 9 and 2) if we (the open edX community) care about the feature. For any given feature, I'm not sure which of those questions is harder to answer. 

[Basic support for 3rd party discussions via LTI](https://openedx.atlassian.net/browse/TNL-7140?src=confmacro)
[Common Cartridge Converter](https://openedx.atlassian.net/browse/TNL-7603) (is this repo even part of open edX?)
[Blockstore Powered Content Library](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) (does this mean Blockstore is part of open edX now?)
[frontend-app-authn MFE](https://github.com/edx/frontend-app-authn) (login, registration and password reset)
[notifier deprecation](https://github.com/openedx/build-test-release-wg/issues/22)
[ORA improvements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation)
[LTI upgrade](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545076784/BD-24+LTI+v1.3+Improvements+Advantage+Support) (not sure if this is 1.3 or Advantage or just specific APIs) 
xModule to xBlock conversion

**Comment by felipemontoya** [comment]
A big chunk of the Hooks extension framework falls in this category.
Some parts of it may be merged by April 9th, but certainly not all of it.

**Comment by pdpinch** [comment]
@felipemontoya if we cut the release on May 9, would that make a difference?

**Comment by felipemontoya** [comment]
That would directly affect 1) and according to my development estimates yes (by May 9 it should be done), but I am a known bad estimator. 

About 2, I'm not sure, I imagine that adoption will take a while so even having some hooks in place by April 9th will still let whoever is interested get started using the framework.

**Comment by blarghmatey** [comment]
Another "feature" that's a bit more diffuse is the overall capability of theming MFEs and whether there is a cohesive way of doing that. Unless there's any concerted effort underway that we expect to land in the next 1-2 months I would say that it's not a decisive factor in when to cut the release, but still something worth identifying and understanding when it will land.

**Comment by sarina** [comment]
I do know xModule -> xBlock is done! I will help follow up on these other things.

**Comment by pdpinch** [comment]
This issue is moot now. We didn't identify any features that would change our release schedule.
