### ISSUE TITLE
Remove the `edx` GitHub organization from the release process

### ISSUE THREAD

**Issue by kdmccormick** [openedx/build-test-release-wg#203]
## Context

Per https://discuss.openedx.org/t/interim-guidance-on-the-openedx-github-organization/8518, the Palm release must only tag repositories in the openedx GitHub organization.

This is related to, but not the same as: https://github.com/openedx/build-test-release-wg/issues/238

## Acceptance Criteria

(this might be better split up into subtasks)

Update the comment in openedx.yaml within edx-cookiecutters to explain that, in addition to setting the `ref:` key, the repo will need to be moved into the openedx organization in order to be released.

Look through our documentation on the wiki; see if there's anything along the lines of "how to get your repository into the release".  If there is, update it to include filing a tCRIL request to move the repository into the openedx org.

Generate the list of repos that would be included from the edx org. As of Olive this was:
```
edx/edx-e2e-tests
edx/enterprise-access
edx/frontend-app-communications
edx/frontend-app-learner-dashboard
edx/frontend-app-ora-grading
edx/testeng-ci
```
but it would be best to re-generate this list closer to Palm.

Create tCRIL request tickets to move all of those repositories into the openedx organization. Tag the owners/maintainers of the repositories and ask if they have any objections to the move. If they object, we'll need to decide whether:
* we remove the repo from Palm, or
* we fork the repository in despite their objection (hopefully this won't need to happen).

Update the release script to only pull from the openedx organization.

**Comment by feanil** [comment]
https://github.com/openedx/tcril-engineering/issues/591 takes care of everything except for edx/edx-e2e-tests which has a PR against it to remove it from the release process.

**Comment by feanil** [comment]
I think once the following PRs merge, we can mark this as complete:

* https://github.com/openedx/repo-tools/pull/330
* https://github.com/openedx/edx-cookiecutters/pull/283

**Comment by feanil** [comment]
Both PRs have merged so this is now all set.

**Comment by kdmccormick** [comment]
Thanks Feanil!
