### ISSUE TITLE
Features flags and Settings changes between nutmeg to olive

### ISSUE THREAD

**Issue by ghassanmas** [openedx/build-test-release-wg#204]
This issue records the changes of featuers flags and settings between nutmeg and olive. 
However this might nof include everything, since it captuers only settings/toggle that implement code-annotations. 

## New Features/Toggles 

1. `ENABLE_DYNAMIC_REGISTRATION_FIELDS` [cms/envs/common.py#L588](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/envs/common.py#L588)

1. `ENABLE_MFE_CONFIG_API` [lms/envs/common.py#L5192](https://github.com/openedx/edxplatform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L5192)

1. `DISABLE_UNENROLLMENT` [cms/envs/common.py#L508](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/envs/common.py#L508)

1. `ENABLE_CERTIFICATES_IDV_REQUIREMENT` [lms/envs/common.py#L1012](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L1012)

1. `SEND_CATALOG_INFO_SIGNAL` [cms/djangoapps/contentstore/signals/handlers.py#L55](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/djangoapps/contentstore/signals/handlers.py#L55)

1. `contentstore.bypass_olx_failure` [cms/djangoapps/contentstore/toggles.py#L39](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/djangoapps/contentstore/toggles.py#L39)

1. `contentstore.individualize_anonymous_user_id` [cms/djangoapps/contentstore/toggles.py#L144](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/djangoapps/contentstore/toggles.py#L144)

1. `contentstore.split_library_on_studio_dashboard` [cms/djangoapps/contentstore/toggles.py#L26](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/djangoapps/contentstore/toggles.py#L26)

1. `course_apps.exams_ida` [openedx/core/djangoapps/course_apps/toggles.py#L22](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/openedx/core/djangoapps/course_apps/toggles.py#L22)

1. `course_live.enable_big_blue_button` [openedx/core/djangoapps/course_live/config/waffle.py#L22](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/openedx/core/djangoapps/course_live/config/waffle.py#L22)

1. `credentials.use_learner_record_mfe` [openedx/core/djangoapps/credentials/config.py#L10](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/openedx/core/djangoapps/credentials/config.py#L10)

1. `discussions.enable_learners_stats` [lms/djangoapps/discussion/config/waffle.py#L9](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/djangoapps/discussion/config/waffle.py#L9)

1. `discussions.enable_reported_content_email_notifications` [lms/djangoapps/discussion/toggles.py#L38](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/djangoapps/discussion/toggles.py#L38)

1. `student.enable_2u_recommendations` [common/djangoapps/student/toggles.py#L2](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/common/djangoapps/student/toggles.py#L2)

1. `student.enable_amplitude_recommendations` [common/djangoapps/student/toggles.py#L9](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/common/djangoapps/student/toggles.py#L9)

1. `student.enable_redesign_enrollment_confirmation_email` [common/djangoapps/student/toggles.py#L43](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/common/djangoapps/student/toggles.py#L43)

## Delete Features/Toggles 

1. `bypass_olx_failure` _Note: proably relate to 6, 7, 8  above_

1. `PersistentGradesEnabledFlag.enabled` 

1. `course_experience.latest_update` 

1. `course_home.course_home_use_legacy_frontend`

1. `courseware.microfrontend_course_team_preview` 

1. `courseware.use_legacy_frontend` 

1. `grades.assume_zero_grade_if_absent` 

1. `split_library_on_studio_dashboard` 

## New settings

1. `LEARNER_RECORD_MFE_URL` [/lms/envs/common.py#L4898](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L4898)
1. `MFE_CONFIG` [lms/envs/common.py#L5204](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L5204)
1.  `MFE_CONFIG_API_CACHE_TIMEOUT` [lms/envs/common.py#L5244](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L5244)
1. `MFE_CONFIG_OVERRIDES` [lms/envs/common.py#L5225](https://github.com/openedx/edx-platform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/lms/envs/common.py#L5225)
1. `CUSTOM_RESOURCE_TEMPLATES_DIRECTORY` [cms/envs/common.py#L2141](https://github.com/openedx/edxplatform/blob/eed0dca524bfd71f7dc3c10a39d5a1154eed34b3/cms/envs/common.py#L2141)

## Deleted Settings

1. `DISCUSSIONS_MFE_FEEDBACK_URL`

**Comment by pdpinch** [comment]
Thanks @ghassanmas I was planning to build a similar list while working on the release notes. This saves me a lot of time. 

Can you share your method for building this list?

**Comment by ghassanmas** [comment]
@pdpinch yeah I knew it would helpful atleast for you. 

from inside edx-platform repo
```
git checkout open-release/nutmeg.master
cd docs/technical 
make xml 
mv _build/xml xml-nutmege
git checkout open-release/olive.master
rm -rf _build
make xml 
mv _build/xml xml-olive
git diff xml-nutmeg xml-olive
```
Scanning the git diff of the last step, you will get an idea about the changes.  
Note there will be a lot of noise because the changes of source url between edx to openedx and the warning which wasn't included nutmeg. 

I think we can ultimately automate this process.  On the bigger picture I persoally think having a mechanism of captuering those settings/toggles changes, default values, requirments, and to be able to debug an installation can be useful, i.e. you use a tool to tell you if your instance have the correct config/settings to use a certifan feature or if you have correct config/settings combination...etc.

**Comment by arbrandes** [comment]
Is this issue something we should continue to be concerned about as Olive approaches, or is the work here done?

**Comment by arbrandes** [comment]
Closing this, as the Release Notes are now up for final review.
