### ISSUE TITLE
PR(s) Needs to be backported or created to Olive 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/build-test-release-wg#205]
The issue purpose to list PRs (which might be open, or not open yet) that needs to back ported at some point: 

### Secuirty update
> PRs opened:
> 
> * openedx/enterprise-catalog/pull/514
> * openedx/blockstore/pull/211
> * openedx/edx-analytics-data-api/pull/588 
> * openedx/ecommerce/pull/3850) 
> * openedx/edx-analytics-dashboard/pull/1372 
> * openedx/xqueue/pull/868 
> * openedx/ecommerce-worker/pull/188 
> * edx/enterprise-access/pull/82)
> * openedx/edx-notes-api/pull/313
> * openedx/license-manager/pull/457 

Ref: https://github.com/openedx/build-test-release-wg/issues/201#issuecomment-1285024044 

### MFEs
- openedx/frontend-app-gradebook/pull/282 
- openedx/frontend-app-learning/pull/1000 
- openedx/frontend-app-profile/pull/632 
__________________________________________________________
## Not yet Opened:

Note: some items relate to the decsion of #200 
- ~openedx/frontend-app-learning/pull/955~ 
- openedx/frontend-app-learner-record/pull/103 or openedx/frontend-app-learner-record/pull/104  
- ~openedx/frontend-app-profile/pull/586~ 
- ~openedx/frontend-app-gradebook/pull/253~ 
- openedx/frontend-app-authn/pull/654 
-  openedx/frontend-app-support-tools/pull/274 
- openedx/frontend-app-learning/pull/976 _Fixes a bug_
- edx/frontend-app-ora-grading/pull/144 
- openedx/cs_comments_service/pull/392
- openedx/edx-app-android/pull/1694

**Comment by arbrandes** [comment]
@mariajgrimaldi, the problem with ORA grading is that there is [another PR](https://github.com/edx/frontend-app-ora-grading/pull/146) that's needed to fix path support, and it doesn't look like it's going to get merged in time in spite of me nagging the team constantly via different channels.

**Comment by arbrandes** [comment]
@ghassanmas, since Ruby 3 is now in, I think we're good to close this one, right?  That [app-learning fix](https://github.com/openedx/frontend-app-learning/pull/976) is not in master, and it won't be in time.
