### ISSUE TITLE
olive-testing (TC_AUTHOR_45): Advanced problem types 

### ISSUE THREAD

**Issue by ARMBouhali** [openedx/build-test-release-wg#206]
# Passing Tests
- [x] Blank advanced Problem
- [x] Circuit Schematic Builder 
- [x] Custom JavaScript Display and Grading
- [x] Custom Python-Evaluated Input
- [x] Drag and Drop
- [ ] Drag and Drop (Deprecated Version)
- [x] Image Mapped Input
- [x] Math Expression Input
- [x] Problem with Adaptive Hint
- [x] Staff Graded Points

**Comment by ARMBouhali** [comment]
- [ ] LMS submit error:

> Staff debug info: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 2298, in execute_check_function safe_exec.safe_exec( File "/opt/pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75, in inner return func(*args, **kwds) File "/openedx/edx-platform/xmodule/capa/safe_exec/safe_exec.py", line 170, in safe_exec exec_fn( File "/openedx/venv/src/codejail/codejail/safe_exec.py", line 154, in safe_exec res = jail_code.jail_code( File "/openedx/venv/src/codejail/codejail/jail_code.py", line 318, in jail_code status, stdout, stderr = run_subprocess_fn( File "/openedx/venv/src/codejail/codejail/subproc.py", line 39, in run_subprocess subproc = subprocess.Popen( # pylint: disable=subprocess-popen-preexec-fn File "/opt/pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 858, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/opt/pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 1704, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'TMPDIR=tmp' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa_module.py", line 1777, in submit_problem correct_map = self.lcp.grade_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 436, in grade_answers new_cmap = self.get_grade_from_current_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 494, in get_grade_from_current_answers results = responder.evaluate_answers(self.student_answers, oldcmap) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 314, in evaluate_answers new_cmap = self.get_score(student_answers) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 2268, in get_score self.execute_check_function(idset, submission) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 2309, in execute_check_function self._handle_exec_exception(err) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 2524, in _handle_exec_exception raise ResponseError(text_type(err), traceback_obj) xmodule.capa.responsetypes.ResponseError: ("[Errno 2] No such file or directory: 'TMPDIR=tmp'", ) 
encountered with: 
-  Circuit Schematic Builder
-  Drag and Drop (Deprecated Version)

**Comment by mariajgrimaldi** [comment]
Some of these issues could be solved by adding codejail in the sandbox, since it's not installed by default. I'll include it after I finish with olive support. I'll let you know :)

**Comment by ARMBouhali** [comment]
@mariajgrimaldi I've got reproduced the exact same error in a tutor-nightly installation.

    [Errno 2] No such file or directory: 'TMPDIR=tmp'

I could make the XBlocks work using the [unofficial codejail service tutor plugin by eduNEXT ](https://github.com/eduNEXT/tutor-contrib-codejail). But it won't count as a success since codejail is already installed along with edx-platform and should work with no worries.

Same issue reported in the forum in the past
https://discuss.openedx.org/t/errno-2-no-such-file-or-directory-tmpdir-tmp/5568

This probably would need intervention at Tutor's `openedx` Dockerfile template.
I hope someone provides a fix without having to use a dedicated container as I did above.

**Comment by mariajgrimaldi** [comment]
While secure code execution is enabled, you'll need a sandbox with special permissions & setup to execute problems with custom code, this is what the codejail plugin offers. That's why is failing. In case you want to execute unsafe code, you'll need to add this to your settings:
`COURSES_WITH_UNSAFE_CODE = ["regex for courses with unsafe code"]`
Which needs to be added manually. Now, the demo is supposed to use the codejail plugin. I added it to the installation a couple of days ago, can you try again?

**Comment by mariajgrimaldi** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
@ARMBouhali let me know if I can help test these now that codejail is added to the installation by @mariajgrimaldi.

**Comment by mariajgrimaldi** [comment]
As part of my codejail testing efforts, I tested:

- [ ]     Custom JavaScript Display and Grading
- [ ]     Custom Python-Evaluated Input
- [ ]     Problem with Adaptive Hint

Uploading 2022-11-22 06-53-58.mp4…

**Comment by mariajgrimaldi** [comment]
There's an issue with the Circuit Schematic Builder, so I opened a PR that solves it 😅

**Comment by DeanJayMathew** [comment]
label: release blocker

**Comment by mariajgrimaldi** [comment]
[Here's](https://github.com/overhangio/tutor/pull/752) the PR to tutor olive branch fixing the template error. 

Also, we got [this ticket](https://github.com/eduNEXT/tutor-contrib-codejail/issues/29) a few days ago, and I thought it was related to the olive upgrade. But after researching a bit more with my team, we realized we'd had that issue since the Lilac release, i.e, it has never worked 😅. We're working on it, but I just wanted to let you guys know since it's related to the Advanced Blank Problem capabilities. Also, if you have any suggestions on how to solve it, we're all ears.

**Comment by ARMBouhali** [comment]
@mariajgrimaldi with this we have only the **drag and drop (deprecated) image display issue in studio** to clear the list.
I re-tested it now and I'm getting this screen:
![image](https://user-images.githubusercontent.com/10594967/206211777-d456ae3a-f5c3-4367-9dbf-5a63b3fc0618.png)

And this console error:
```
drag_and_drop.a31124208b9b.js:8 Uncaught TypeError: requirejs.config is not a function
    at drag_and_drop.a31124208b9b.js:8:19
    at drag_and_drop.a31124208b9b.js:25:2
```

**Comment by mariajgrimaldi** [comment]
@arbrandes @DeanJayMathew: should we remove the release blocker label? IMO the issues left are not blockers

**Comment by arbrandes** [comment]
Let's ditch the deprecated (and clearly unsupported) drag-and-drop test, and call this done.
