### ISSUE TITLE
Demonstration Course not exporting in Open edX Olive Demo Server

### ISSUE THREAD

**Issue by sambapete** [openedx/build-test-release-wg#207]
An attempt on exporting the Demonstration Course course-v1:edX+DemoX+Demo_Course failed over the week-end on the previous Open edX Olive Demo Server. Something about a transcript file not being available.

![image](https://user-images.githubusercontent.com/8906669/197574595-cfc6233c-ade6-4bd8-95e2-a35e91a71fd5.png)

A second attempt on exporting the Demonstration Course course-v1:edX+DemoX+Demo_Course failed today (Oct 24) with the export just hanging on us.

I imported the https://github.com/openedx/openedx-demo-course with the tarball available https://github.com/openedx/edx-demo-course/releases/download/v1.1/edx_demo_course_1_1.tar.gz. The course is available on the Open edX Olive Demo Server as course-v1:edX+DemoX+Demo_Course2

I did not have any problems exporting this course on the new server or in the old server.

We might be a defective Demonstration Course on the Open edX Olive Demo Server.

Please note that there seems to be differences in the contents of the course I imported and the course with is having export issues. There is a new "holding section" at the end of course-v1:edX+DemoX+Demo_Course2. It seems to replace the "prerequisites" section at the end of course-v1:edX+DemoX+Demo_Course.

We should determine which is the "real" Demonstration Course.

**Comment by mariajgrimaldi** [comment]
Hi there! Something similar happened during the nutmeg testing: https://github.com/openedx/build-test-release-wg/issues/158#issuecomment-1127615140

**Comment by sambapete** [comment]
Thanks for pointing it out @mariajgrimaldi

**Comment by regisb** [comment]
AFAIK this issue is related to the demonstration course itself. We should probably open an issue in the upstream repository: https://github.com/openedx/openedx-demo-course

**Comment by DeanJayMathew** [comment]
@sambapete can we mark this as resolved? I just exported and imported a new course with success.

**Comment by sambapete** [comment]
Yes. The only problem I have encountered is with the demo course that is imported by Tutor.

**Comment by sambapete** [comment]
I will close this issue as it only applies to the demo course. Export of other courses do work.

**Comment by DeanJayMathew** [comment]
We'll have to ensure this is resolved for Palm I guess.

**Comment by mariajgrimaldi** [comment]
I can work on this in the meantime.
