### ISSUE TITLE
olve-testing TC_AUTHOR_50: all basic problem types

### ISSUE THREAD

**Issue by ARMBouhali** [openedx/build-test-release-wg#209]
## Passing tests:
- [x] Blank Common Problem
- [x] Checkboxes
- [x] Dropdown
- [x] Multiple Choice
- [x] Numerical Input
- [x] Text Input
- [x] Checkboxes with Hints and Feedback
- [x] Dropdown with Hints and Feedback
- [x] Multiple Choice with Hints and Feedback
- [x] Numerical Input with Hints and Feedback
- [x] Text Input with Hints and Feedback

## Issue
**Numerical Input:** staff debug error message showing when the input is an invalid non-numerical value. (only in LMS)
> Staff debug info: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 1608, in get_score student_float = evaluator({}, {}, student_answer) File "/openedx/venv/lib/python3.8/site-packages/calc/calc.py", line 255, in evaluator math_interpreter.check_variables(all_variables, all_functions) File "/openedx/venv/lib/python3.8/site-packages/calc/calc.py", line 478, in check_variables raise UndefinedVariable(message) calc.calc.UndefinedVariable: Invalid Input: aze not permitted in answer as a variable During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa_module.py", line 1777, in submit_problem correct_map = self.lcp.grade_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 436, in grade_answers new_cmap = self.get_grade_from_current_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 494, in get_grade_from_current_answers results = responder.evaluate_answers(self.student_answers, oldcmap) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 314, in evaluate_answers new_cmap = self.get_score(student_answers) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 1610, in get_score raise StudentInputError( # lint-amnesty, pylint: disable=raise-missing-from xmodule.capa.responsetypes.StudentInputError: Invalid Input: aze not permitted in answer as a variable

Maybe it shows because `DEBUG=True` in LMS. If anyone can confirm this, then we can dismiss this issue.

**Comment by ARMBouhali** [comment]
- [ ] **Numerical Input:** staff debug error message showing when the input is an invalid non-numerical value. (only in LMS)
> Staff debug info: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 1608, in get_score student_float = evaluator({}, {}, student_answer) File "/openedx/venv/lib/python3.8/site-packages/calc/calc.py", line 255, in evaluator math_interpreter.check_variables(all_variables, all_functions) File "/openedx/venv/lib/python3.8/site-packages/calc/calc.py", line 478, in check_variables raise UndefinedVariable(message) calc.calc.UndefinedVariable: Invalid Input: aze not permitted in answer as a variable During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/openedx/edx-platform/xmodule/capa_module.py", line 1777, in submit_problem correct_map = self.lcp.grade_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 436, in grade_answers new_cmap = self.get_grade_from_current_answers(answers) File "/openedx/edx-platform/xmodule/capa/capa_problem.py", line 494, in get_grade_from_current_answers results = responder.evaluate_answers(self.student_answers, oldcmap) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 314, in evaluate_answers new_cmap = self.get_score(student_answers) File "/openedx/edx-platform/xmodule/capa/responsetypes.py", line 1610, in get_score raise StudentInputError( # lint-amnesty, pylint: disable=raise-missing-from xmodule.capa.responsetypes.StudentInputError: Invalid Input: aze not permitted in answer as a variable

Maybe it shows because `DEBUG=True` in LMS. If anyone can confirm this, then we can dismiss this issue.

**Comment by mariajgrimaldi** [comment]
As far as I know, the whole traceback is printed as staff debug info when you're a staff member.

**Comment by mariajgrimaldi** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
label: release blocker

**Comment by ARMBouhali** [comment]
I've retested the numerical input and I'm getting the expected message to show without debug info.
![image](https://user-images.githubusercontent.com/10594967/204745086-af07b80a-dd58-478f-a861-186045f9fe4a.png)

That's it for this issue so I'm closing it

**Comment by ARMBouhali** [comment]
I've retested the numerical input and I'm getting the expected message to show without debug info.
![image](https://user-images.githubusercontent.com/10594967/204745086-af07b80a-dd58-478f-a861-186045f9fe4a.png)

That's it for this issue so it needs to be closed
