### ISSUE TITLE
Course outline visual bug when edxnotes is enabled for a course

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#21]
When edxnotes is enabled in a course, the following visual bug appears in the course outline.

![image](https://user-images.githubusercontent.com/13796098/109625223-f8f22000-7b36-11eb-8451-b0d04aa9c64f.png)

Tested on native install and tutor.

**Comment by cmltaWt0** [comment]
I believe I can take this task due to the fact we have the same task internally on RG.
One note here - I have to clear understanding of **expected result** of this bug.
The actual result is clear but not an ER (how should it work).

**Comment by BbrSofiane** [comment]
I would expect the Annotator element to be only accessible within course content so this shouldn't appear outside of the course.

**Comment by BbrSofiane** [comment]
@cmltaWt0 Do you have any updates on this issue?

**Comment by cmltaWt0** [comment]
@BbrSofiane investigation and fix are planned for this week. I hope to have this issue fixed or investigated before our next meetup.

**Comment by cmltaWt0** [comment]
UPD: issue has been fixed.
We are going to open PR tomorrow or on Monday.

P.S. My teammate is going to sign the Individual Contributor Agreement to open the PR.

**Comment by BbrSofiane** [comment]
Is the issue present in master too? It will mean a PR for both master and koa.master

**Comment by cmltaWt0** [comment]
@BbrSofiane Yeap. PR will be opened to the master and koa.master branches.

**Comment by cmltaWt0** [comment]
@BbrSofiane @nedbat

Fix was already introduced in [master](https://github.com/edx/edx-platform/tree/master) branch.
So we simply [back-porting](https://github.com/edx/edx-platform/pull/27198) it to `koa.master`.
