### ISSUE TITLE
Missing footer links during Olive testing

### ISSUE THREAD

**Issue by michaelwheeler** [openedx/build-test-release-wg#212]
The footer on legacy pages was missing the following links specified in `TC_LEARNER_3`:

- FAQ
- Blog
- Donate
- Privacy Policy

![image](https://user-images.githubusercontent.com/763388/197607586-50d6520a-e264-4972-82eb-dd6281586f1c.png)

MFE is missing all links, but I'm not sure if that is considered outside the scope of this test.

**Comment by mariajgrimaldi** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
@michaelwheeler thank you for doing this test case. I will update the test case to be in line with Tutor's Olive instead of the legacy interface.

You can mark this as resolved I think.

**Comment by michaelwheeler** [comment]
@DeanJayMathew Sorry, I'm not sure that I follow your meaning. Both legacy-rendered pages and MFE-rendered pages were missing at least some of the specified footer links on the Olive test instance.

**Comment by DeanJayMathew** [comment]
@michaelwheeler thanks for the follow up! What I meant was, I was unaware Tutor had removed those links in the legacy and MFE front ends so my Test Case is out of date so to say. We actually need two test cases, one for legacy and one for MFE, until such a time that legacy is deprecated.

But let's take a closer look. The current Test Case lists the following links:

**About
FAQ
Blog
Contact
Donate
ToS & Honor Code
Privacy Policy**


**The Legacy links according to your findings:**

About  - Visible
FAQ - **Missing**
Blog - **Missing**.  **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**
Contact - Visible
Donate - **Missing** **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**
ToS & Honor Code - Visible
Privacy Policy - Missing
Indigo Theme for Open edX - Visible **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**

**The MFE links:**
Taken from this freshly installed Nutmeg instance: https://lms.bantutribes.com/

About - Visible
FAQ - Missing
Blog - Visible **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**
Contact - Visible 
Donate - Visible  **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**
Terms of Service & Honor Code - Visible 
Privacy Policy - Visible 
Take free online courses at edX.org - Visible **<-- I would say this link should be removed from Open edX® as we don't use it so we have to remove it for each new client**


_____

Any thoughts on removing those links from the Open edX® standard installation? Once we are decided, and it passed the BTR Working Group review, we could proceed to finalise and update the test cases.

**Comment by michaelwheeler** [comment]
@michaelwheeler Got it, thanks. Yes all of your suggested modifications seem reasonable to me.

**Comment by michaelwheeler** [comment]
Hey @arbrandes I noticed that this has been assigned to me. Is there a specific step I am expected to take to resolve this issue?

**Comment by DeanJayMathew** [comment]
I think the next step is to decide as a community what links we want to
have as standard. After that, we need to get Règis' opinion and ask him how
he would like to proceed. For example someone could open a PR, for example.

I stand corrected.

**Comment by arbrandes** [comment]
@michaelwheeler, I assigned you as tester, primarily so you get credit for the investigation. 👍🏼 

Otherwise, we don't have to do anything here.  Most people are going to want to install a custom footer anyway, as per [the customization instructions](https://github.com/overhangio/tutor-mfe#customising-mfes).  I'm reasonably sure the demo server also has a custom footer, as the default install of Tutor uses `frontend-component-footer`, and that doesn't have any links other than the logo.

**Comment by arbrandes** [comment]
PS, @DeanJayMathew, I'm pretty sure this test can be removed from the list.
