### ISSUE TITLE
[TC_AUTHOR_96]  Learn more link 404

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/build-test-release-wg#219]
Learn more link point to non existent page.

STR:
- open Files & Uploads
- Click delete asset button
- Click on Learn more link

AR:
- opening non existent page in edx.readthedocs.io

ER:
- opening help page (to decide which one)

<img width="1454" alt="TC_AUTHOR_96" src="https://user-images.githubusercontent.com/877401/197824155-79db9c9e-ff50-42b1-b149-67993e3fadee.png">

**Comment by DeanJayMathew** [comment]
label: release blocker

**Comment by DeanJayMathew** [comment]
label: olive testing

**Comment by cmltaWt0** [comment]
I've removed the `release blocker` label due to issue minor severity.

**Comment by cmltaWt0** [comment]
@arbrandes @DeanJayMathew the issue fixed automatically after Olive release - the Help link points to olive.master readthedocs.

Source code compiles the link based on release name so we are getting the working target only after documentation [brach](https://github.com/openedx/edx-documentation/tree/open-release/olive.master) is created.


Current help link: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-olive.master/course_assets/course_files.html

Closing the issue.
