### ISSUE TITLE
[TC_LEARNER_17 > Configure course email preferences] email check is not working for me

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#221]
I think this issue is linked with https://github.com/openedx/build-test-release-wg/issues/220 . Once emails start working it will be fixed.

**Comment by fayyazahmed66** [comment]
label: olive testing

**Comment by mariajgrimaldi** [comment]
label: olive testing

**Comment by mariajgrimaldi** [comment]
Can you describe how we can replicate this? so we can discard or not if this is related to 220

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 @mariajgrimaldi

I can confirm this is now passed. Please mark as resolved.
