### ISSUE TITLE
[LMS > Courses page > User menu dropdown] > Logout button is hidden behind refine your search card 

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#224]
**Steps to reproduce:**

1. Go to the courses page
2. click on the user menu
3. check the logout button
**Expected result:**
All menus should be visible
**Actual result:**
The logout button is hidden

<img width="1679" alt="logout layout" src="https://user-images.githubusercontent.com/55684124/199194649-a2c5296b-fc71-43b8-9e5e-9a4f7e9c12e1.png">

**Comment by fayyazahmed66** [comment]
label: olive testing

**Comment by mariajgrimaldi** [comment]
label: olive testing
