### ISSUE TITLE
[Register new account/ reset password] Emails are going to spam

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#226]
**Steps to reproduce:**

1. Register a new user or reset your password
2. Check your inbox
**Expected result:**
Email should come to inbox
**Actual result:**
Emails coming to spam
<img width="1678" alt="spam" src="https://user-images.githubusercontent.com/55684124/199198758-a7b9f752-ed8b-48ee-aab0-c30f7a5536c8.png">

**Comment by fayyazahmed66** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 this is normal for Open edX® so to say. The SMTP service is enabled, but the server is not configured for email authentication (DKIM, SPF, etc.). This means that emails do get sent, but it's very likely that they will end up in spam, depending on your email client configuration.

Should we add this to the list of post-launch test cases? That way we can wait for someone in our team to launch an Olive instance and configure email authentication and see if it works.

Honestly, even with authentication, some emails still end up going to spam.

**Comment by mariajgrimaldi** [comment]
I've registered some users, and I'm getting the activation emails just fine. Can you test this again? should the server setup be a prerequisite for the demo installation?

**Comment by sambapete** [comment]
I just want to point out that we would never have received our own activation emails for our accounts on the demo server if there was a problem. It might depend on the rules used by the service receiving the emails?

**Comment by DeanJayMathew** [comment]
It's working for me fine with GSuite email.

**Comment by fayyazahmed66** [comment]
I have verified it again. Emails are coming fine now.
