### ISSUE TITLE
Figure out what the Lilac release process is going to be

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#23]
We need to figure out what the exact Lilac release process is going to look like _before_ April 9th, when we're considering cutting `open-release/lilac.master`.  Such as:

* Who's going to do the cutting?  @nedbat or @arbrandes?  
* Will we follow the exact procedure as the one done originally for `koa.master`?
* How, where, and by whom will the testing be done?
* What are the pre-lilac.1 milestones we need to target?

Etc.

**Comment by arbrandes** [comment]
[This ADR](https://github.com/openedx/build-test-release-wg/pull/25) was submitted as part of this effort, in order to establish the release timeline.

**Comment by BbrSofiane** [comment]
@arbrandes is there anything left to close this issue?

**Comment by arbrandes** [comment]
@BbrSofiane, not really.  If you have no objections, I think we can merge the ADR and close this.
