### ISSUE TITLE
TC_AUTHOR_56 & 57: STUDIO: CONTENT: OUTLINE: UNIT: Edit discussion display name, category and subcategory

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/build-test-release-wg#230]
**Summary of Issue:** When adding a discussion component at the unit level, the category name and subcategory name that you add should appear in the left pane of the main discussion forum for the course. However, the category name and subcategory name that I added do not appear in the left pane.

**Steps to reproduce:**

1. Add a discussion component at the Unit level.
2. Edit the display name, category and subcategory:
<img width="1381" alt="Screen Shot 2022-11-22 at 20 20 06" src="https://user-images.githubusercontent.com/9986523/203325444-3d54da08-68fe-46e9-adce-e2d85147e2ca.png">

**Expected Outcome:** The category and subcategory names should appear in the left pane of the main discussion forum.

**Actual Outcome:** The category and subcategory names do not appear in the left pane of the main discussion forum:

<img width="1244" alt="Screen Shot 2022-11-22 at 20 21 29" src="https://user-images.githubusercontent.com/9986523/203325580-b190f774-8b70-4888-82c9-8924dcedd673.png">

**Comment by DeanJayMathew** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
label: release blocker

**Comment by mariajgrimaldi** [comment]
I tested this using the Demonstration Course and it seems to be working. Not sure why didn't work for you 🤔. Let me know if this problem persists.

![image](https://user-images.githubusercontent.com/64440265/204544179-2eacb45f-5edd-43f9-a291-9bd2e9ea31c7.png)

![image](https://user-images.githubusercontent.com/64440265/204544075-639831e9-d9f4-4d4b-933a-56f29446f2a4.png)

**Comment by DeanJayMathew** [comment]
@mariajgrimaldi this is a big relief thank you for testing this one! Maybe my eyes were not working properly the first time I tested it.

It's also working for me now so I will close this issue.
