### ISSUE TITLE
TC_AUTHOR_64: STUDIO XBLOCKS: FREETEXT RESPONSE

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/build-test-release-wg#232]
**Summary of Issue:**

We need someone to install free text response and test it. It seems no free text response comes default with Tutor as far as I know.

**Steps to reproduce:**

1. In Studio go to Advanced Setting and try add "freetextresponse" or "freetext" to the Advanced Modules List.
2. In Studio at the Unit level, try add an Advanced Component but there is no option in the dropdown.

**Expected Outcome:** Freetext response should be available as an Advanced component.

**Actual Outcome:** Freetext response is not available by default and needs to be installed/configured.

**Comment by DeanJayMathew** [comment]
label: olive testing

**Comment by DeanJayMathew** [comment]
label: release blocker

**Comment by sambapete** [comment]
It's not a default XBlock. This brings us back to the question of what is supported or what we want to support by default with Tutor or even Open edX. This should be a question for both the Marketing working group and the Build Test Release working group.

**Comment by pdpinch** [comment]
Is this the xBlock in question? https://github.com/Stanford-Online/xblock-free-text-response ?

**Comment by sambapete** [comment]
Originally, yes. But I've made a fork for our own use at EDUlib a few months ago from https://github.com/openedx/xblock-free-text-response 

It probably ended up in the openedx organization after Stanford closed their own Open edX instance?

**Comment by sambapete** [comment]
I currently install it in own Tutor installation with the following lines in config.yml
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- git+https://github.com/openedx/xblock-free-text-response.git

**Comment by arbrandes** [comment]
I'm curious: why is this a test case?  Is there consensus that this should be part of the default installation?

It feels like this should be a more general "which custom XBlocks do we want to add to the default set".  The XBlocks would then be subject to a checklist like [the MFEs'](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE).

**Comment by sambapete** [comment]
It was a test case probably because Dean took it from my personal list of test cases for our installation when we originally created the new test plan.

But I agree we should have a list of XBlocks to test, but previously when we raised that question we were always reminded that we want to test the build of a default Open edX installation and not necessarily XBlocks. But before we do that, we need to determine what is part of a release. Isn't that where the Product Working Group and OEP-57 should come in? 

As a matter of fact, we don't even test release upgrades (from Nutmeg to Olive) for example. All we do is test the current build.

**Comment by DeanJayMathew** [comment]
Hi All, sorry for the late reply!

Pierre, thanks, yes you're right it does not come with the standard
distribution of Open edX/Tutor. There's also a test case for invideoquiz
which I should deprecate too, until such a time it gets added to the
standard distro, if ever. Thanks for reminding me.

Peter, we at ABC also fork someones freetextresponse, I think we've even
used a fork of a fork before. Do you want me to ask our CTO which one he
used?

Adolfo, it would be great if freetextresponse was standard as it allows for
traditional classroom experiences but it's not a perfect feature as is,
because viewing the results is difficult to read and clunky in the download
file that one gets. But yeah it should not be a test case until such point,
if ever. I like the point about a checklist for included XBlocks!

**Comment by DeanJayMathew** [comment]
Nice point, Pierre. Perhaps having a test case for the upgrade itself would
be a good idea, and quite a task that would be.

**Comment by DeanJayMathew** [comment]
@sambapete @arbrandes @pdpinch 

A new Test Case has been added to test the actual software version upgrade works and is titled **TC_DEVOPS_13** in the Olive Test Sheet: https://docs.google.com/spreadsheets/d/128g8Rfx-Eu8vjeSPw7E7eU0-Ss_oF232kmZEJvM2NmM/edit#gid=0
