### ISSUE TITLE
Create small MFE base image using runtime MFE config system

### ISSUE THREAD

**Issue by kdmccormick** [openedx/build-test-release-wg#235]
## Context

The MFE runtime config API has been added to frontend-platform and edx-platform! Issue: https://github.com/openedx/frontend-wg/issues/103

We would like to make use of that API in the tutor-mfe plugin so that we can statically build a minimal tutor-mfe image, which can be used by anyone along with runtime configuration.

## Acceptance

* Ensure all built-in MFEs have upgraded frontend-platform and specify an `APP_ID`
* ...
* Update mfe plugin to use dynamic config API instead of static config
* Build & publish an upstream `mfe` image.
* TODO: add remaining steps
* ...
* Remove `--build` flag from `tutor dev start`, as it's no longer needed.

**Comment by ghassanmas** [comment]
[Update]: From my end one of the current blocker is this openedx/frontend-app-gradebook/pull/290

**Comment by arbrandes** [comment]
Gradebook is no longer a blocker, and it looks like images are going to [start being built](https://github.com/overhangio/tutor-mfe/commit/d470e876dd34d75234d8840c02f87b7b3b5b9c4a) by CI!  I think we can close this.
