### ISSUE TITLE
Backport Mongo 4.0 support to Koa

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#24]
[Mongo 3.6 is EOL on April 30th](https://mongosilverback.net/2020/08/06/mongodb-3-6-eol-announced/).

**Comment by BbrSofiane** [comment]
@blarghmatey I've added you to the repo, once you accept or comment on this issue I can assign it to you.

**Comment by blarghmatey** [comment]
If anyone has pointers to specific code changes that need to be backported that would help, otherwise I'll do some code spelunking and test things out in our QA environment.

**Comment by BbrSofiane** [comment]
Pinging @cmltaWt0 in case he has any pointers

**Comment by cmltaWt0** [comment]
Thanks @BbrSofiane 

I've done some quick finding and it appears that backported code is already on koa.master ([commit](https://github.com/edx/edx-platform/commit/ba4de2f933d693e8cae771b8b7755a26700ea11d)) and I hope we can find related commits.

@blarghmatey I'm going to search for the pymongo/mongo related updates in master branch and post here anything I'll find.

**Comment by pomegranited** [comment]
Brilliant, thank you for finding that [commit](https://github.com/edx/edx-platform/commit/ba4de2f933d693e8cae771b8b7755a26700ea11d) @cmltaWt0 !
OpenCraft are testing the koa.1 release against a new Mongo 4.0 cluster (FAL-859), so we'll ensure the results are posted here.
CC @arbrandes

**Comment by BbrSofiane** [comment]
@blarghmatey do you have any updates on this issue?

**Comment by pomegranited** [comment]
@BbrSofiane @blarghmatey CC @arbrandes  We ran some testing with MongoDB 4.0 and `open-release/koa.2a`, and didn't find any issues with using the forum or modifying courseware.

So I think we can call this issue done!

**Comment by BbrSofiane** [comment]
@pomegranited sounds good. @blarghmatey  Do we need to make mongo 4.0 the default in the configuration repo?

**Comment by nedbat** [comment]
Don't we have to change what version of Mongo is installed when you run the native installation?

**Comment by pomegranited** [comment]
@nedbat  Ach yep we do.. @BbrSofiane @blarghmatey CC @arbrandes  If someone can create a PR against the edx:configuration repo, I can review and merge as core committer.

**Comment by arbrandes** [comment]
For the time being, we're not porting Mongo 4.0 to Koa.  We'll instead focus on installing it by default on Lilac.  (See #47).
