### ISSUE TITLE
Support for the Profile MFE

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#28]
Coordinate, and if necessary execute, the tasks necessary to get the [Profile MFE](https://github.com/edx/frontend-app-profile) up to speed for Lilac:

1. It passes a minimum standard of documentation: at the very least, the READMEs should have descriptive text that includes use cases, screenshots, and particularly, documentation on that MFE's environment variables.
2. Its basic feature-set (as documented above) works reliably with the rest of the Lilac codebase.
3. It's deployed by default using the Native Installation, and deployable as a plugin using Tutor.
4. It is internationalized (i18n), localizable (l10n), and passes minimum accessibility (a11y) standards.
5. It has a header and footer that are customizable via npm aliases: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#overriding-brand-specific-elements
6. It is compatible with the @edx/brand system: https://open-edx-proposals.readthedocs.io/en/latest/oep-0048-brand-customization.html
7. It uses CSS utility classes in a branding-friendly way. (i.e., don't use things like 'bg-white')

**Comment by davidjoy** [comment]
I don't think anyone at edX is actively looking at this list.  I can be a contact to help get things merged here.

**Comment by regisb** [comment]
As far as I understand, the profile MFE is not internationalized or localized at all, either in Lilac or the master branch:

![Screenshot from 2021-10-05 16-44-03](https://user-images.githubusercontent.com/44319/136045894-47933929-ee2d-4b88-a43e-59d472e20f60.png)

I would expect the profile page to be in French, given my browser and my Open edX account settings.

If it is any comfort, the profile page on edX.org is not translated either:

![Screenshot from 2021-10-05 16-45-23](https://user-images.githubusercontent.com/44319/136046133-d002148b-17aa-4094-9cbd-057576691eab.png)

It should be noted that the Account MFE does not seem to be translated either on edX.org. However, the "Order History" (ecommerce) page is partially translated, so something right must be happening there:

![Screenshot from 2021-10-05 16-48-34](https://user-images.githubusercontent.com/44319/136046705-ec59b661-f3cb-4438-a33a-44e643ed253f.png)

I can reproduce the problem, both locally and on edx.org, in French and in Spanish. 

It seems like we have an overarching problem with MFE translations. In my understanding, the projects are translated with the help of Transifex. For instance, here are the Spanish strings for the profile MFE: https://www.transifex.com/open-edx/edx-platform/viewstrings/#es_419/frontend-app-profile/186018400 As we can see, the profile MFE is fully translated. The translation strings were correctly collected in the frontend-app-profile repo: https://github.com/edx/frontend-app-profile/blob/master/src/i18n/messages/es_419.json

However, I can't get these strings to be displayed in my locally running Profile MFE (or on edX.org). @davidjoy can you shed some light on this?

**Comment by davidjoy** [comment]
Note that "Primary Language Spoken" is _not_ the same as setting the site language, which is done in your account settings (either through the MFE or old experience)

That said, I see that the FR translations are all in English right now, which means they probably haven't been accepted in Transifex.  es_419, on the other hand, looks to be fully translated.  If you set your site language in account settings and come back, I'd expect Spanish to be translated, but FR to appear English.

**Comment by regisb** [comment]
> Note that "Primary Language Spoken" is not the same as setting the site language, which is done in your account settings (either through the MFE or old experience)

Right! However, I still can't get the Profile MFE in Spanish, even when I set the platform language to es_419 and change the user site language, from the account. I'll keep investigating.

**Comment by regisb** [comment]
We got i18n to work in the profile MFE, thanks to a [tutor bugfix](https://github.com/overhangio/tutor-mfe/pull/21). We should also be able to override branding assets, thanks to a pending [PR by @BbrSofiane](https://github.com/overhangio/tutor-mfe/pull/16).

So this issue should be closed pretty soon.
