### ISSUE TITLE
Evaluate Tutor as a candidate for community installation

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#3]
Work with the community in evaluating Tutor as a candidate for the “official” community installation method.

https://openedx.atlassian.net/browse/OEROADMAP-21

https://github.com/edx/open-edx-proposals/pull/178

https://openedx.atlassian.net/browse/BTR-43

**Comment by arbrandes** [comment]
https://github.com/edx/open-edx-proposals/pull/178 is set to be merged, so we can mark this as done.  I'll create follow-up tickets on this and/or the open-edx-proposals board.
