### ISSUE TITLE
Support for the Payment MFE

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#30]
Coordinate, and if necessary execute, the tasks necessary to get the [Payment MFE](https://github.com/edx/frontend-app-payment) up to speed for Lilac:

1. It passes a minimum standard of documentation: at the very least, the READMEs should have descriptive text that includes use cases, screenshots, and particularly, documentation on that MFE's environment variables.
2. Its basic feature-set (as documented above) works reliably with the rest of the Lilac codebase.
3. It's deployed by default using the Native Installation, and deployable as a plugin using Tutor.
4. It is internationalized (i18n), localizable (l10n), and passes minimum accessibility (a11y) standards.
5. It is reasonably themable.

This is in response to [this thread](https://discuss.openedx.org/t/build-test-release-biweekly-2021-03-15/4526/3).

**Comment by nedbat** [comment]
Is this in addition to the three MFE's we discussed supporting (https://discuss.openedx.org/t/build-test-release-biweekly-2021-03-15/4526)?  Where is the official list of what we are tackling for Lilac?

**Comment by sarina** [comment]
@nedbat We discovered the payment stuff will not work in legacy mode so we *have* to support this MFE, probably at the cost of the Profile MFE. See my post here: https://discuss.openedx.org/t/build-test-release-biweekly-2021-03-15/4526/2?u=sarina

**Comment by BbrSofiane** [comment]
@sarina can the documentation for the payment MFE get the same treatment as #27 ?

**Comment by sarina** [comment]
@BbrSofiane what is missing? We did a pass on https://github.com/edx/frontend-app-payment/pull/479

**Comment by BbrSofiane** [comment]
@sarina Ah perfect thanks! I wanted to check that it was covered.

Overall looks good! I think the only thing that's missing is a screenshot of the UI.

**Comment by sarina** [comment]
OK. I could try to set it up and take a picture, but it will not be this week.

**Comment by BbrSofiane** [comment]
Thanks, it won't block the progress on this.

**Comment by sarina** [comment]
the readme says ` Rather, log into the LMS at http://localhost:18000/login and enroll in a course, choosing to upgrade to be taken to the checkout page.`

I'm not sure how to get an upgradable course. If these are instructions _you_ can follow and post a screenshot that'd be great (and probably clarify the instructions to explain how to make courses upgradable). Otherwise this will have to wait until I find time with someone on Payments team, which I can't give a timeline on.

**Comment by BbrSofiane** [comment]
Fair enough, I don't know how to do it myself so I would have to ask the group.

**Comment by cmltaWt0** [comment]
Actually I'm doing the same work just right now. I'll post here steps to be able to make the Course "upgradable" via payment flow.

**Comment by cmltaWt0** [comment]
@sarina I'm not finished with full testing for payment MFE but anyway I'll post some screenshots and instructions to help you enabling paid/upgradable course.

**Flow to add paid course**
1. After Course creation open `{LMS_BASE_URL}/admin/course_modes/coursemode/`
2. Add verified mode for your Course
<img width="1601" alt="Screenshot 2021-04-29 at 23 52 10" src="https://user-images.githubusercontent.com/877401/116618392-a91db280-a947-11eb-8b84-8bb82ee57011.png">
3. Add honor mode for the Course
<img width="1586" alt=" Screenshot 2021-04-29 at 23 52 27" src="https://user-images.githubusercontent.com/877401/116620673-d324a400-a94a-11eb-9e6c-4c78aa094514.png">
4. Open `{ECOMMERCE_BASE_URL}/courses/`
<img width="1207" alt="Screenshot 2021-04-29 at 23 53 40" src="https://user-images.githubusercontent.com/877401/116620173-264a2700-a94a-11eb-996f-7ac28968a958.png">
5. Add new Course with Verified and Audit mode, set price (5 USD in my case)
<img width="1232" alt="Screenshot 2021-04-29 at 23 54 20" src="https://user-images.githubusercontent.com/877401/116620222-34984300-a94a-11eb-9b5d-ffa30737e80b.png">
<img width="1236" alt="Screenshot 2021-04-29 at 23 54 38" src="https://user-images.githubusercontent.com/877401/116620265-437ef580-a94a-11eb-9812-516b551743e5.png">
6. Enroll to the Course
<img width="1611" alt="Screenshot 2021-04-29 at 23 56 18" src="https://user-images.githubusercontent.com/877401/116620386-6e694980-a94a-11eb-8637-245ab1609395.png">
7. Now you can Audit Course or Upgrade it to Verified
<img width="1592" alt="Screenshot 2021-04-29 at 23 56 28" src="https://user-images.githubusercontent.com/877401/116620451-83de7380-a94a-11eb-9aee-6251452db03a.png">
8. The same option you can find at `{LMS_BASE_URL}/dashboard `
<img width="1228" alt="Screenshot 2021-04-29 at 23 56 52" src="https://user-images.githubusercontent.com/877401/116620559-a83a5000-a94a-11eb-92d8-329641602a7f.png">


Hope the instruction is correct. If something is not accurate or I've miss some steps please let me know - I'll re-check the flow and test it from scratch.

**Comment by regisb** [comment]
:clap: screenshots are awesome, thanks @cmltaWt0!

**Comment by cmltaWt0** [comment]
Will leave here my notes for Ecommerce integration in native installation.

Ecommerce and Payment MFE PR is ready and it is in the internal code review status now.
But I need to discuss Ecommerce service in native installation as is.
What I can see right now is that Ecommerce is installed via native installation but it’s not usable by default:
it is not configured for login via LMS using edx-oauth2
LMS is not enabled for oauth2 login
ECOMMERCE_SESSION_COOKIE_SECURE is true by default but native installation is used http (as result we are unable to login to ecommerce at all by default)
it is not configured for using LMS API and Discovery API
LMS and Discovery is defaulted to localhosts and not re-configured in openedx_native.yml (probably should or should be configured in config.yml)
I’ve fixed the described issues by adding required changes in openedx_native.yml but I’m not sure it’s a goal of the PR so it will be great to discuss how to proceed with Ecommerce configuration for native installation by default.

**Comment by cmltaWt0** [comment]
I’ve created draft [PR](https://github.com/edx/configuration/pull/6403) with all changes and I’ll remove unnecessary during code review. 
UPD: the PR will be removed and new one will be created to the master.

I'm waiting for https://github.com/edx/configuration/pull/6405 and https://github.com/edx/configuration/pull/6406 to be merged to updated my PR.

**Comment by cmltaWt0** [comment]
[PR](https://github.com/edx/configuration/pull/6408) has been created.
Will be back ported to the lilac master after merge.

Ecommerce additional configuration during provision will be added as a separate PR.

**Comment by arbrandes** [comment]
@cmltaWt0, thanks for this.  I tested it, and both payment and ecommerce MFEs are getting deployed correctly.

However, the default configuration is not really usable out of the box on a native install.  Yes, I know, this is how it's always been with ecommerce.   But is this what you mean by "ecommerce additional configuration" on a separate PR?

I'm just trying to gauge if we want to go the extra mile and make ecommerce as easy to enable as Studio itself.

**Comment by cmltaWt0** [comment]
@arbrandes yes it's exactly what I meant by additional configuration.

Fixes were introduced in my previous PR and I'll add changes I separated from mfe PR later. But for sure it will require some deep testing.

**Comment by arbrandes** [comment]
We can consider this technically done.  The practical task of getting this (and the Ecomerce MFE) into Lilac.1 is being taken care of via #64 and #65.
