### ISSUE TITLE
Find out if order history still works

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#31]
See [this post](https://discuss.openedx.org/t/build-test-release-biweekly-2021-03-15/4526/3).  Before we decide if we want to support frontend-app-ecommerce, we need to find out if legacy order history functionality still works (and is still likely to work by around April 9).

**Comment by arbrandes** [comment]
@kdmccormick, ok if I assign you this one, to expedite communication?

**Comment by kdmccormick** [comment]
@arbrandes Can you assign @inventhouse ? He's a member of the edX Revenue squad, which owns this MFE.

**Comment by BbrSofiane** [comment]
@inventhouse can you comment on this issue so I can assign it to you.

**Comment by BbrSofiane** [comment]
@inventhouse just following up on this, do you have any updates? Also once you comment on the issue I will be able to assign to to you.

**Comment by inventhouse** [comment]
> @inventhouse just following up on this, do you have any updates? Also once you comment on the issue I will be able to assign to to you.

We have an internal ticket tracking this work and will be picking it up soon; you can assign this to me in the meantime (now that I've commented.)

**Comment by inventhouse** [comment]
The order history page still works in the legacy (non-MFE) implementation, at least locally.

**Comment by inventhouse** [comment]
@BbrSofiane @kdmccormick Is there anything more you need on this?

**Comment by BbrSofiane** [comment]
@kdmccormick can you confirm that this mean that frontend-app-ecommerce is not a hard requirement for Lilac?

**Comment by kdmccormick** [comment]
Sorry @BbrSofiane ; I guess I'm not subscribed to notifiations on this board. Will fix that.

Yes, this means that front-app-ecomm is not a hard req.
