### ISSUE TITLE
Guide to getting started with MFE Branding

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#36]
With the incremental support of MFEs coming with Lilac, it would be useful for the community to have a starting point when it comes to theming MFEs.

Acceptance criteria: one or two lines about this to the release notes, to the effect that MFE theming is still a work in progress and the community has yet to reach a consensus on what is the way forward, but that there are ways to do (some) MFE theming in Lilac as per:

* https://opencraft.gitlab.io/dev/branding-and-theming/discoveries/01-discovery-theming-and-branding-capabilities/
* https://discuss.openedx.org/t/open-edx-branding-and-theming-improvements/4747/2

**Comment by BbrSofiane** [comment]
https://opencraft.gitlab.io/dev/branding-and-theming/discoveries/01-discovery-theming-and-branding-capabilities/

**Comment by BbrSofiane** [comment]
https://discuss.openedx.org/t/open-edx-branding-and-theming-improvements/4747/2

**Comment by BbrSofiane** [comment]
https://github.com/open-craft/edx-simple-theme/pull/18

**Comment by arbrandes** [comment]
@pdpinch agreed to add one or two lines about this to the release notes, to the effect that MFE theming is still a work in progress and the community has yet to reach a consensus on what is the way forward, but that there are ways to do (some) MFE theming in Lilac as per the links above.

(For Lilac.2, by which time one hopes this year's conference videos are released, @jfavellar90 reports that there is a talk by Daniel on this very subject which we should also link to.)

**Comment by BbrSofiane** [comment]
@pdpinch there are instructions for [changing the logos ](https://github.com/overhangio/tutor-mfe#customise-mfes-logos)in tutor but nothing yet about the branding package. I'll add that to the plugin README so you can point to it in the release notes.
