### ISSUE TITLE
Cherry-pick Upgrade py2neo in edx-platform

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#37]
This issue currently breaks the installation of open edX.
https://github.com/edx/edx-platform/pull/27168
https://openedx.atlassian.net/browse/BOM-2466

Once merged into master, the fix needs to be backported to koa.

**Comment by cmltaWt0** [comment]
@BbrSofiane my applauses! Confirmed the same build fail today.
Just to note - I believe we have top back-port only https://github.com/edx/edx-platform/pull/27168/commits/41b01c07eb10982589da6b6e55f70ba36d592d68 commit.

**Comment by BbrSofiane** [comment]
I just opened a [PR](https://github.com/edx/edx-platform/pull/27186) to backport the fix. @nedbat or @pdpinch Can one of you review it?

**Comment by pdpinch** [comment]
@nedbat merged it back into koa in https://github.com/edx/edx-platform/commit/f3dca8e81ff244ff9b0914a11ae6f9c15fc9be12
