### ISSUE TITLE
Juniper fails to install requirements

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/build-test-release-wg#38]
**Context**

There is a new [setuptools-scm](https://pypi.org/project/setuptools-scm/6.0.1/) was introduced on March 17 with breaking python3.5 support.
[Juniper master](https://github.com/edx/edx-platform/tree/open-release/juniper.master) has a [development.txt](https://github.com/edx/edx-platform/blob/open-release/juniper.master/requirements/edx/development.txt#L41) leading us to the [setup.py](https://github.com/edx-unsupported/bridgekeeper/blob/edx_release_py3/setup.py#L10) with not well formed dependency setup_requires=["setuptools_scm>=1.11.1"]

**Result**

Requirements can’t installed at all due to python3.6+ requirements from setuptools-scm 6.0.1 package.

**Proposed fix**

Updated [setup.py](https://github.com/edx-unsupported/bridgekeeper/blob/edx_release_py3/setup.py#L10)  setup_requires  to >=1.11.1 and < 6.0.0

If we support Juniper installation at least in the installable state we have to return back the [bridgekeeper](https://github.com/edx-unsupported/bridgekeepe) repo from read-only mode to introduce a fix.

**Error detail**

```python
 cwd: /tmp/pip-install-owuurkz8/bridgekeeper/
 Complete output (31 lines)
 ERROR: Package 'setuptools-scm' requires a different Python: 3.5.2 not in '>=3.6'
 Traceback (most recent call last):
   File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
     subprocess.check_call(cmd)
   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
     raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/edx/app/edxapp/venvs/edxapp/bin/python3.5', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplwhd17q2', '--quiet', 'setuptools_scm>=1.11.1']' returned non-zero exit status 1
```

**Comment by jfavellar90** [comment]
@cmltaWt0 @BbrSofiane what do you think about closing this one?

**Comment by jfavellar90** [comment]
Since this is a bug related to an old OpenedX release (Juniper), we proceed to close the issue
