### ISSUE TITLE
"mfe : create nodeenv" failure installing master

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#39]
Installing master of April 7, the installation failed:
```
TASK [mfe : create nodeenv] ****************************************************
fatal: [localhost]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable.
The error was: 'COMMON_ECOMMERCE_BASE_URL' is undefined
The error appears to be in '/var/tmp/configuration/playbooks/roles/mfe/tasks/main.yml': line 59, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:

- name: create nodeenv
  ^ here
"}
```

**Comment by arbrandes** [comment]
I have [a PR](https://github.com/edx/configuration/pull/6358).  @cmltaWt0, would you like to test it?  @nedbat, as well.

**Comment by cmltaWt0** [comment]
@arbrandes 👍 build has been passed. Platform is working fine.
ok=688  changed=238  unreachable=0  failed=0    skipped=1493 rescued=0    ignored=0

**Comment by jfavellar90** [comment]
@arbrandes working from my side as well

**Comment by arbrandes** [comment]
Ok, so apparently the PR was merged (yay) before I could get to resubmitting it to master.  So we now need to cherry-pick it.

**Comment by arbrandes** [comment]
Sent a [new PR](https://github.com/edx/configuration/pull/6369) to master.

**Comment by BbrSofiane** [comment]
The PR has been merged so I'll close this.
