### ISSUE TITLE
Circle CI is broken in edx-platform

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#4]
@felipemontoya can you please add more details to this ticket?

https://openedx.atlassian.net/browse/BTR-19

**Comment by BbrSofiane** [comment]
@felipemontoya any updates on this?

**Comment by felipemontoya** [comment]
Hey @BbrSofiane,
The update we have is that we have this PR https://github.com/edx/edx-platform/pull/25725. However after some talk with arch members at edX we realized it would be more useful if we turned this into github actions instead of circle ci.

**Comment by felipemontoya** [comment]
@mariagrimaldi fyi

**Comment by felipemontoya** [comment]
Also @BbrSofiane where should we write this? here or the jira ticket?

**Comment by BbrSofiane** [comment]
@felipemontoya here, the BTR group is moving to github projects and issues to manage tasks.

**Comment by BbrSofiane** [comment]
@felipemontoya am I ok to close this issue if the PR is not going to be merged?

**Comment by arbrandes** [comment]
@BbrSofiane, looks to me like its fine to move this to "Not Doing", as far as the group is concerned.  (Which is what I just did.)

**Comment by felipemontoya** [comment]
Yeah, I also agree with moving this to not doing. We will still work on it on our own time, but it does not block any other work or release for this group.
