### ISSUE TITLE
Missing lilac.master repositories?

### ISSUE THREAD

**Issue by sambapete** [openedx/build-test-release-wg#42]
frontend-app-ecommerce and frontend-app-payment do not seem to have been tagged for lilac.master

**Comment by BbrSofiane** [comment]
Hey @arbrandes, do you have any updates on this?

**Comment by nedbat** [comment]
Steps:
[] Fix the openedx.yaml files so that they would have been branched properly.
[] Create lilac.master branches in the two repos from the right point in time.

**Comment by BbrSofiane** [comment]
@arbrandes any update on this?

**Comment by nedbat** [comment]
> [ ] Fix the openedx.yaml files so that they would have been branched properly.

- https://github.com/edx/frontend-app-ecommerce/pull/152
- https://github.com/edx/frontend-app-payment/pull/484
