### ISSUE TITLE
Test frontend-app-payment native deployment

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#43]
Deploy frontend-app-payment with edx/configuration

**Comment by BbrSofiane** [comment]
@cmltaWt0 did you manage to get the MFE installed with the native installation?

**Comment by cmltaWt0** [comment]
Not yet. Working on it.

**Comment by cmltaWt0** [comment]
MFE is deployable and configurable.

I'l post screenshots of testing steps.




**[Empty Cart](https://github.com/edx/frontend-app-payment/blob/c9b31b6c657f4c3eb710cf861fec4b07807082dc/README.rst#cart-states)**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/877401/116273631-96aa4a00-a78a-11eb-8d82-3d83b345c979.png">

**Comment by BbrSofiane** [comment]
@cmltaWt0 can we close this?

**Comment by cmltaWt0** [comment]
Not yet. There are other use cases I have to test.

**Comment by cmltaWt0** [comment]
**Testings report**

MFE description

```
Micro-frontend for the single-page payment/checkout process; order history and receipt pages are still served by the ecommerce service. This application only supports PayPal and Cybersource credit card payments.
```

[Application](https://github.com/edx/frontend-app-payment) was deployed using edx/configuration and tested.


Required deployment and configuration actions:


1. Add required MFE section
```
MFES:
  ...
  - name: payment
    repo: frontend-app-payment
    public_path: "/payment/"
```
2. Add following changes to the lms.yml
```
CSRF_TRUSTED_ORIGINS:
  - { $MFE_BASE }

CORS_ORIGIN_WHITELIST:
  - { $MFE_BASE }
  
FEATURES:
  ENABLE_CORS_HEADERS: true
```
3. Add following to the ECommerce Site Configuration

- [x] Enable Microfrontend for Basket Page

Payment Microfrontend URL: https://{ $MFE_BASE }/payment 
(To investigate how we can use it) Account Microfrontend URL: https://{ $MFE_BASE }/account 

![image](https://user-images.githubusercontent.com/877401/117642448-f55ec300-b18f-11eb-8d5a-2ecf4740faa7.png)

4. Add following to the `ecommerce.yml`
```
CORS_ORIGIN_WHITELIST:
  - { $MFE_BASE }

CSRF_TRUSTED_ORIGINS:
  - { $MFE_BASE }
```
5. Create paid course
6. Create different coupons for full discount and partial discount.
![image](https://user-images.githubusercontent.com/877401/117642576-1d4e2680-b190-11eb-9f2f-1aafbf08ae84.png)

7. Enroll into course
8. Apply partial coupon to check PayPal redirection
![image](https://user-images.githubusercontent.com/877401/117642651-36ef6e00-b190-11eb-9219-149a885e3efe.png)
![image](https://user-images.githubusercontent.com/877401/117642688-4078d600-b190-11eb-9343-7d65aa5c43ec.png)

9. Apply full discount coupon code
![image](https://user-images.githubusercontent.com/877401/117642721-4e2e5b80-b190-11eb-856c-7cd9d627bdd6.png)
10. Check you order by clicking on place order button
![image](https://user-images.githubusercontent.com/877401/117642762-5b4b4a80-b190-11eb-909d-b566d5796db5.png)
11. Check your order history on Order History (https://{ $MFE_BASE }/ecommerce/orders) 
![image](https://user-images.githubusercontent.com/877401/117642882-7e75fa00-b190-11eb-8fa9-e9b37e124a53.png)
12. Apply incorrect or expired coupons
![image](https://user-images.githubusercontent.com/877401/117642921-89c92580-b190-11eb-970f-655e80ae2afa.png)
![image](https://user-images.githubusercontent.com/877401/117642950-8f267000-b190-11eb-95bb-a1b2b804fda1.png)
![image](https://user-images.githubusercontent.com/877401/117642966-92b9f700-b190-11eb-9e4b-177227137ef9.png)
![image](https://user-images.githubusercontent.com/877401/117642984-98afd800-b190-11eb-8048-58088db20db5.png)
13. Check order history to see incorrect orders
![image](https://user-images.githubusercontent.com/877401/117643033-a5343080-b190-11eb-8ea2-d514cc1f52c3.png)


**NOT FULLY TESTED**
- Real payment using PayPal and cybersource

**KNOWN ISSUES**

- by default Order history is not visible in MFE's header

**Comment by cmltaWt0** [comment]
@BbrSofiane Testing is done. Issue can be closed.
New issue for the integration and enabling by default to the native installation should be created separately (and linked to this issue).

**Comment by BbrSofiane** [comment]
🥇

**Comment by cmltaWt0** [comment]
Yeap. Let's check - it's just a description from MFE repo.
It means that app supports these two processors right now and I hope it will be trivial to add stripe, netbanx etc.
