### ISSUE TITLE
Test frontend-app-ecommerce native deployment

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#44]
Deploy frontend-app-ecommerce with edx/configuration

**Comment by BbrSofiane** [comment]
@cmltaWt0 did you manage to get the MFE installed with the native installation?

**Comment by cmltaWt0** [comment]
Not yet. Working on it.

**Comment by cmltaWt0** [comment]
MFE is deployable and configurable.
Yet I have to finish CORS configuration for e-commerce .

<img width="991" alt="image" src="https://user-images.githubusercontent.com/877401/116278467-2fdb5f80-a78f-11eb-930e-c03736ef1df4.png">

**Comment by cmltaWt0** [comment]
**Testings report**

MFE description

```
This is a micro-frontend application responsible for the display of an authenticated user's order history.
```

[Application](https://github.com/edx/frontend-app-ecommerce) was deployed using edx/configuration and tested.


Required deployment and configuration actions:


1. Add required MFE section
```
MFES:
  ...
  - name: ecommerce
    repo: frontend-app-ecommerce
    public_path: "/ecommerce/"
```
2. Add following changes to the lms.yml
```
CSRF_TRUSTED_ORIGINS:
  - { $MFE_BASE }

CORS_ORIGIN_WHITELIST:
  - { $MFE_BASE }
  
FEATURES:
  ENABLE_CORS_HEADERS: true

ORDER_HISTORY_MICROFRONTEND_URL: https://{ $MFE_BASE }/ecommerce/orders
```
3. Add following to the LMS Site Configuration
```
{“ENABLE_ORDER_HISTORY_MICROFRONTEND”: true}
```
4. Add the Waffle flag  `order_history.redirect_to_microfrontend` manually or programmatically
```
./manage.py lms waffle_flag --create --everyone order_history.redirect_to_microfrontend --settings=production
```
5. Add following to the `ecommerce.yml`
```
CORS_ORIGIN_WHITELIST:
  - { $MFE_BASE }
```
6. Create paid course
7. Do some positive and negative payment attempts
8. Open navbar
![image](https://user-images.githubusercontent.com/877401/117640259-82544d00-b18d-11eb-8af4-03af06d04db9.png)
![image](https://user-images.githubusercontent.com/877401/117640410-ad3ea100-b18d-11eb-9477-6fb2f948729e.png)

9. Open Order history
![image](https://user-images.githubusercontent.com/877401/117640435-b3cd1880-b18d-11eb-80ee-4021133aa2d2.png)


**Known Issues**
1. by default Order history is not visible in MFEs
![image](https://user-images.githubusercontent.com/877401/117640514-c6dfe880-b18d-11eb-8781-897d7d9c59af.png)

2. There is no default DevStack integration yet

**Comment by cmltaWt0** [comment]
@BbrSofiane Testing is done. Issue can be closed.
New issue for the integration and enabling by default to the native installation should be created separately.,

**Comment by BbrSofiane** [comment]
Awesome @cmltaWt0!

I've created #64.

**Comment by regisb** [comment]
Big up @cmltaWt0! This is tremendously useful and makes my life so much easier to integrate MFEs with Tutor. You get my vote for the Academy Award of the week :)
