### ISSUE TITLE
Lilac.master CI

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#46]
Lilac.master CI with email

**Comment by regisb** [comment]
WIP here: https://git.overhang.io/community/openedx-configuration-ci
This uses Packer to launch a DigitalOcean server, install Open edX there, and if it succeeds make a server image.
It was working for Ironwood, and it looks like it is now failing on Koa.

**Comment by regisb** [comment]
[Running](https://git.overhang.io/community/openedx-configuration-ci/-/jobs/3322) ...

**Comment by regisb** [comment]
Well at least the email notification works: https://groups.google.com/g/open-edx-btr-notifications/c/DVj8opf6qHc

**Comment by regisb** [comment]
Btw at what time of the day should we be running the daily build? In my experience it's best if it is run at the beginning of the work day, such that we can actually do something about it when the failure occurs. So maybe start the job at 9 AM UTC?

**Comment by BbrSofiane** [comment]
9 AM sounds good to me.

**Comment by BbrSofiane** [comment]
I had a discussion with @adzuci to get more information about using github actions to do the same. It looks like it would be possible to run the installation instruction in an ubuntu runner since the resources and time required to run the install are within the [limits](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) allocated to Github Actions.

If it works, the main advantages that I see are:
- We can setup the github action in this repo and the group could take on the burden of maintaining it.
- It doesn't require any server provision, so no need for an org to create credentials to give access to a cloud provider.

What does everyone think? Is it worth investing some time into this or should we go with https://git.overhang.io/community/openedx-configuration-ci which we know works?

**Comment by regisb** [comment]
I think it makes sense to migrate the CI to Github actions, such that there is a clearly identified group that is responsible for maintaining it.

**Comment by BbrSofiane** [comment]
Posted my current issue in the [forum](https://discuss.openedx.org/t/help-running-native-install-inside-a-github-runner-for-ci/4855), I will spend some time on it this Friday and share my progress.

**Comment by BbrSofiane** [comment]
The issue with the installation of the discovery service is still outstanding. I will commit a first iteration without it, I'm just waiting for a webhook to a slack channel.

**Comment by BbrSofiane** [comment]
Merged #57 - Installation without discovery.

**Comment by arbrandes** [comment]
This is not blocking Lilac.1 (we're still gonna test it manually anyway), so moved it to Lilac.2.
