### ISSUE TITLE
Contact Us page has edX-specific messaging

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#51]
Noticed here: http://gsedxdev.com/support/contact_us

The entire Contact Us page is a neutered version of edX's links to the Zendesk support system.  It's not right for Open edX installations at all.

**Comment by alfredchavez** [comment]
Is it about the banner with a link to edX Help Center? I think a change to remove that banner have already been merged to master https://github.com/edx/edx-platform/pull/27229, or maybe I am looking in the wrong direction

**Comment by BbrSofiane** [comment]
Hi @alfredchavez Can you check if the change was backported to Lilac?

**Comment by alfredchavez** [comment]
Hi @BbrSofiane, that change is also in open-release/lilac.master

**Comment by BbrSofiane** [comment]
@alfredchavez thanks, you're correct this issue can be closed. I'll attach a screenshot of the current page for reference.

![image](https://user-images.githubusercontent.com/13796098/120389665-a20e0980-c324-11eb-86a9-0a62476b3100.png)
