### ISSUE TITLE
Move Native installation instructions from the wiki to ReadTheDocs

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#53]
Is this a good idea?  It feels odd that the official installation instructions that lots of people need are on the wiki instead of "real" books.

wiki: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Lilac+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation

**Comment by regisb** [comment]
> Is this a good idea?

:arrow_right::arrow_right::arrow_right:   **YES!!!** :arrow_left::arrow_left::arrow_left:
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by alfredchavez** [comment]
I'd like to contribute to this issue, I am migrating that page to the edx-documentation repository

**Comment by BbrSofiane** [comment]
Thanks, @alfredchavez for your interest! Do you need any help getting started on this?

**Comment by alfredchavez** [comment]
@BbrSofiane thanks, I didn't have run into problems so far, but as soon as I need help I'll ping you

**Comment by alfredchavez** [comment]
@BbrSofiane Hi, I created a PR https://github.com/edx/edx-documentation/pull/1948, maybe you can take a look at it, I am not sure what to complete in the reviewers part of the PR(Subject matter expert, etc.). Let me know if change is needed, best regards, Alfred.

**Comment by BbrSofiane** [comment]
@nedbat 

We need to update the links that refer to these instructions to now point to the readthedocs.

**Comment by regisb** [comment]
Here is the actual link: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/index.html

**Comment by arbrandes** [comment]
> We need to update the links that refer to these instructions to now point to the readthedocs.

I think the referred PR pretty much does that already for the edx-documentation repo.  So I think we can call this one done and create any follow-up tickets, if necessary.

**Comment by BbrSofiane** [comment]
Thanks @alfredchavez  for your contribution! 🎉
