### ISSUE TITLE
HTML titles of MFEs include hardcoded "edX" strings

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#54]
Both the Account and Gradebook MFEs include hardcoded "edX" strings in the HTML `<title>`:

![edx title](https://user-images.githubusercontent.com/44319/115267484-84e8f700-a139-11eb-8189-9050adcec8a6.png)

As far as I understand, this is where these strings come from:

- Account: https://github.com/edx/frontend-app-account/blob/e59ada660c9deb28a7eb82be4cd836c837744087/public/index.html#L4
- Gradebook: https://github.com/edx/frontend-app-gradebook/blob/8bc1fc82f2c8e616e33ebb6f47ae7086ee6e3b56/public/index.html#L4

The root of the problem lies in the MFE template, which includes this string by default: https://github.com/edx/frontend-template-application/blob/96a3c64b32c77d4be6af5a7b2a289c42447d26d0/public/index.html#L4

Instead of "edX", the title should include the `SITE_NAME`. 

This is an issue for people who are not running edx.org.

**Comment by BbrSofiane** [comment]
@sarina is this something you can take?

**Comment by sarina** [comment]
Yes, created a ticket here: https://openedx.atlassian.net/browse/OPENEDX-485 David will try to take a look next week

**Comment by BbrSofiane** [comment]
@davidjoy have you had a chance to look into this? (I can't access the Jira ticket)

**Comment by sarina** [comment]
We have some PRs in review. You can't see https://openedx.atlassian.net/browse/CENG-6 ? We thought we made the project public...

**Comment by BbrSofiane** [comment]
Thanks! For the link I'll check again when I get on my laptop.

**Comment by davidjoy** [comment]
Hi @BbrSofiane - I'm almost done with this.  All commits are made, just need to merge PRs into master and the lilac branch in each repo.

**Comment by davidjoy** [comment]
This is done.  I don't have permission to transition this issue. 😄

**Comment by BbrSofiane** [comment]
@davidjoy Thanks! I will close the issue. 

Can you post the link to the PR?

**Comment by davidjoy** [comment]
https://github.com/edx/frontend-app-account/pull/432 - PR to lilac.master
https://github.com/edx/frontend-app-gradebook/pull/178 - cherry picked to lilac.master

And for good measure:

https://github.com/edx/frontend-app-profile/pull/413
https://github.com/edx/frontend-template-application/pull/330
