### ISSUE TITLE
The gradebook MFE header includes a hardcoded link to edx.org

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#55]
![edx-org-gradebook](https://user-images.githubusercontent.com/44319/115269227-6421a100-a13b-11eb-8c2b-187be562c852.png)

The gradebook header logo is an image for which the "src" attribute is customizable, but not the the hyperlink destination (edx.org): https://github.com/edx/frontend-app-gradebook/blob/8bc1fc82f2c8e616e33ebb6f47ae7086ee6e3b56/src/components/Header/index.jsx#L16

I'm not sure this is an issue for Lilac, as the Gradebook was not listed among the four MFEs enabled by default; still, I think it would be great if such issues could be resolved in time for Lilac, such that the gradebook becomes actually usable before then.

**Comment by BbrSofiane** [comment]
@sarina Is this something that edX is better placed to do?

**Comment by sarina** [comment]
We are not defaulting the Gradebook MFE as it is not i18n'd properly. I can't guarantee we can fix for Lilac; probably a better question for @davidjoy

**Comment by ChrisChV** [comment]
Hi!
I'd like to fix this, I already prepared a PR if someone can check it: https://github.com/edx/frontend-app-gradebook/pull/186

**Comment by BbrSofiane** [comment]
Hi @ChrisChV thanks for your contribution!

@davidjoy Can you review this?

**Comment by mtyaka** [comment]
It looks like this was fixed in edx/frontend-app-gradebook#186. Can we close this issue?

**Comment by BbrSofiane** [comment]
Yes, thank you for your contribution @mtyaka!
