### ISSUE TITLE
Lilac failed to build via native installation

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/build-test-release-wg#56]
When building master/lilac.master from scratch it fails on mysql role.
Rebuilding on prepared ubuntu with installed mysql-client/server packages completed success.

https://discuss.openedx.org/t/master-native-installation-failed-to-build/4795

PRs:
https://github.com/edx/configuration/pull/6376
https://github.com/edx/configuration/pull/6377
https://github.com/edx/configuration/pull/6378

**Comment by BbrSofiane** [comment]
@pomegranited Could you review this? It's stopping any new native installation.

**Comment by pomegranited** [comment]
Sure thing @BbrSofiane , I'm launching a deployment now, but it's the end of my day, so will approve first thing tomorrow.

**Comment by BbrSofiane** [comment]
Thanks!

**Comment by pomegranited** [comment]
Tested and merged. Thank you @cmltaWt0 !
