### ISSUE TITLE
MFE Configuration Settings Documentation

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#58]
https://discuss.openedx.org/t/we-really-really-need-some-docs-on-mfe-env-settings/4788

**Comment by davidjoy** [comment]
I've added this FEDX task which I'm hoping our team can pick up very soon. 

https://openedx.atlassian.net/browse/FEDX-566

(Our new team doesn't have its own Jira project yet!)

**Comment by BbrSofiane** [comment]
Thanks @davidjoy, I'll assign this to you for now so any updates can land here.

**Comment by BbrSofiane** [comment]
@davidjoy  any updates on this?

**Comment by davidjoy** [comment]
@BbrSofiane - None yet, unfortunately.

**Comment by BbrSofiane** [comment]
https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#configuration-with-environment-variables

**Comment by BbrSofiane** [comment]
@davidjoy from the current state of the document we're happy to consider this issue closed.

We will open specific issues if we find anything is missing.
