### ISSUE TITLE
native.sh doesn't exit with the correct status

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#59]
If Ansible fails, the native.sh exit status is still zero.

https://discuss.openedx.org/t/master-native-installation-failed-to-build/4795/6?u=nedbat

**Comment by nedbat** [comment]
https://github.com/edx/configuration/pull/6386

**Comment by nedbat** [comment]
Fixed with https://github.com/edx/configuration/pull/6383

**Comment by regisb** [comment]
Good! This means that today's CI on git.overhang.io will run with the included fix, we'll see how that works.
