### ISSUE TITLE
Apply Django 2.2.21 security patch

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#60]
Django versions 3.2.1, 3.1.9 and 2.2.21 will be released on Tuesday, May 4, 2021 around 0900 UTC. 
They will fix one security defect with severity “low”.

**Comment by BbrSofiane** [comment]
@nedbat is there a guide somewhere with the steps to do this? It might useful to have them on github and refer to them for these tasks so that anyone feels confident to pick it up.

**Comment by nedbat** [comment]
@BbrSofiane The steps I used are in Discourse, and I just updated them with the 2.2.23 steps I used today: https://discuss.openedx.org/t/django-2-2-19-security-update/4305/3?u=nedbat

This requires updating 14 of the 38 main repos. My assumption is that this makes pull requests impractical, so write access is needed to the repos.
