### ISSUE TITLE
Lilac release notes

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#61]
The wiki page for [Process to Create an Open edX Release](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release) has a couple of steps for creating release notes:

- [x] Get release notes started
- [x] Make release-specific pages for installation and release notes

In addition, we need to:

- [x] add an appropriate TOC to the release notes
- [x] add any items from the [Lilac wiki page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2023915819/Lilac)  
- [x] Review and incorporate any feature posts from [edX Partner announcements](https://partners.edx.org/announcements)
- [ ] Review and incorporate any feature posts from the [open edX blog](https://open.edx.org/category/blog/)
- [ ] Compile a list of relevant repos for review, e.g. ORA, Proctoring, etc. 
- [ ] Review commit messages from relevant repos 
- [ ] Review [DEPR tickets ](https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=452)

**Comment by pdpinch** [comment]
@nedbat @arbrandes do you have any advice on how I can determine which repos are included in the Lilac release? My plan is to review the changelogs for each. If there isn't a changelog then I'll have to look through the git log.

**Comment by pdpinch** [comment]
@nedbat the PR template for the docs template suggests that I should "Build an RTD draft," which seems like a good idea. Do you know how to do that?

**Comment by nedbat** [comment]
@pdpinch I can make a ReadTheDocs project to publish the release notes branch.  For your own use, you can build locally with ./run_tests.sh as described in the readme.  A ReadTheDocs project would let us point reviewers to the published pages, though they'd still have to get feedback to us somehow.

**Comment by nedbat** [comment]
OK, now there is an auto-updating readthedocs project: https://draft-lilac-release-notes.readthedocs.io/en/latest/

**Comment by pdpinch** [comment]
@nedbat possibly dumb question: can I/should I include screenshots in the release notes? I'm trying to decide how to include product updates like [this](https://docs.google.com/document/d/1ZD8rCrBHO6rg-a08ZUEvW_iX-2m7HBiCK09Gr-Rg_uc/edit?ts=609d6a51#heading=h.s524z6gywhvr).

**Comment by arbrandes** [comment]
We agreed during the meeting on Jun 7 to release the notes as they were by the time we tagged them.

@pdpinch, I'd just remove the explicit "TBD" references, unless of course they've already been fleshed out with actual content by the time of the release.
