### ISSUE TITLE
The menu of frontend-component-header 

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#66]
By default Order history is not visible in MFEs

![image](https://user-images.githubusercontent.com/13796098/117651446-dbba7d00-b189-11eb-8950-c933ff2a7260.png)

**Comment by ChrisChV** [comment]
Hi! I would like to fix this issue, but I need more context about the problem. What is correct, show or not show the Order history in MFEs?

**Comment by BbrSofiane** [comment]
Hi @ChrisChV, thanks for taking this on!

@davidjoy @sarina Would you be able to provide some guidance here?

**Comment by davidjoy** [comment]
Huh - I don't see any references to order history in that entire repository.  That feels wrong.

**Comment by BbrSofiane** [comment]
@davidjoy Hmm I can see "Order History" on edx.org

**Comment by BbrSofiane** [comment]
Yeah I can see it here: https://github.com/edx/frontend-component-header-edx/blob/4b69ab80e63ce6884851b475378057ce40ba0b24/src/Header.jsx#L25

**Comment by BbrSofiane** [comment]
So to fix this:
- [ ] Port the changes needed to add "Order History" using frontend-component-header-edx as an example
- [ ] Add the variable to the README

Is that correct?

**Comment by davidjoy** [comment]
Yes, edx.org uses frontend-component-header-edx, which has this menu item.  Your suggestion makes sense to me. 👍🏻

**Comment by BbrSofiane** [comment]
@ChrisChV Does it make sense to you?

**Comment by ChrisChV** [comment]
Yes it makes sense to me, I can do it

**Comment by ChrisChV** [comment]
I created a PR:  https://github.com/edx/frontend-component-header/pull/107

**Comment by BbrSofiane** [comment]
Hi @ChrisChV, Looks like the PR has been merged. Thanks for your contribution! 🎉
