### ISSUE TITLE
Improve README on frontend-app-ecommerce

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#68]
Improve README on frontend-app-ecommerce 

#30

**Comment by sarina** [comment]
Please use this template: https://github.com/edx/frontend-template-application/blob/master/README-template-frontend-app.rst

**Comment by arbrandes** [comment]
This [had already been done](https://github.com/edx/frontend-app-ecommerce/commit/aadb276bc8a9afe8dfabc71e8dcc480c4d286ade#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f).  For Lilac, I don't think any further improvement is necessary.
