### ISSUE TITLE
All emails include the edX.org logo which is a sailthru tracking image

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#7]
This bug was first reported here: https://discuss.overhang.io/t/change-edx-logo-in-activation-mail/1238

The problem is that all emails sent to Open edX users (including e.g: email address confirmation messages) include a prominently visible, hard-coded edX.org logo which appears to be a tracking image: https://media.sailthru.com/595/1k1/8/o/599f355101b3f.png

This is an absolute horror because it means that all emails sent to Open edX users from all Open edX platforms (even outside of edx.org) report opening stats to sailthru.

This behaviour was modified after the Koa branch was cut in the following PR: https://github.com/edx/edx-platform/pull/25654/files
I think these changes should be backported to the Koa branch.

https://openedx.atlassian.net/browse/BTR-58

**Comment by NeOneSoft** [comment]
Hi!!! @arbrandes, @BbrSofiane, I would like to work on this issue if you are agree!!

**Comment by BbrSofiane** [comment]
@NeOneSoft Thanks for taking this on!

**Comment by NeOneSoft** [comment]
Hi!!@BbrSofiane, I'll ready created a PR for this issue. I'll be attending any comment and thanks a lot!!
https://github.com/edx/edx-platform/pull/27064/commits/d407433e61ebf5758b5024498942f91d75dc27a7

**Comment by BbrSofiane** [comment]
Thanks @NeOneSoft!

@nedbat @pdpinch Can one you merge the PR?

**Comment by nedbat** [comment]
Merged.
