### ISSUE TITLE
[Tutor] Instrumentation and documentation for running Tutor at scale

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#77]
Brought up as [Criterion 1](https://github.com/edx/open-edx-proposals/blob/master/oeps/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst#criterion-1-how-well-can-tutor-deploy-open-edx-for-production-use) in OEP-45, ADR-1, the community needs a publicly documented, reproduceable way to run Tutor at scale on multiple servers.

A good example of what is meant by this is @braden's ["Tutorraform"](https://discuss.openedx.org/t/tech-talk-demo-deploying-multiple-open-edx-instances-onto-a-kubernetes-cluster-with-tutor/4641) (pending a name change, for trademark reasons).  We should consider this ticket closed when at least one such solution, whether it is the former or not, is accepted by the community to fulfill Criterion 1 as described.

**Comment by BbrSofiane** [comment]
overhangio/tutor#547

**Comment by regisb** [comment]
I'm closing this, as the tutorial was now merged in the nightly branch. Please comment on the PR mentioned above.
