### ISSUE TITLE
The Zendesk "contact us" page is enabled by default

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#79]
On both Lilac.rc1 and Koa.3, the LMS footer includes a link to /support/contact_us. This page includes a form that is submitted to Zendesk.
 
![Screenshot from 2021-06-07 12-14-29](https://user-images.githubusercontent.com/44319/120999902-f03e6500-c789-11eb-961a-501b2188791f.png)

But for most Open edX instances, Zendesk is not actually enabled. Thus, submitting the form results in a 500 error:

```
lms_1               | 2021-06-07 10:09:37,596 INFO 6 [tracking] [user 3] [ip 80.67.176.14] logger.py:41 - {"name": "/zendesk_proxy/v1", "context": {"user_id": 3, "path": "/zendesk_proxy/v1", "course_id": "", "org_id": ""}, "username": "regis", "session": "2b2fda75a4304ed49cf077eb5755e95f", "ip": "80.67.176.14", "agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0", "host": "lilac.overhang.io", "referer": "https://lilac.overhang.io/support/contact_us", "accept_language": "fr,en;q=0.5", "event": "{\"GET\": {}, \"POST\": {}}", "time": "2021-06-07T10:09:37.596168+00:00", "event_type": "/zendesk_proxy/v1", "event_source": "server", "page": null}
lms_1               | 2021-06-07 10:09:37,605 INFO 6 [edx_rest_framework_extensions.auth.jwt.middleware] [user 3] [ip 80.67.176.14] middleware.py:70 - ('The view ZendeskPassthroughView allows Jwt Authentication. The required permission class, NotJwtRestrictedApplication,', ' was automatically added.')
lms_1               | 2021-06-07 10:09:37,608 ERROR 6 [openedx.core.djangoapps.zendesk_proxy.utils] [user 3] [ip 80.67.176.14] utils.py:67 - zendesk_proxy action required
lms_1               | zendesk not configured
lms_1               | No ticket created for payload {"ticket": {"requester": {"name": "regis", "email": "regis@behmo.com"}, "subject": "Account Settings", "comment": {"body": "Pouac ?", "uploads": null}, "custom_fields": [{"value": "Not specific to a course"}], "tags": ["LMS"]}}
lms_1               | 2021-06-07 10:09:37,611 ERROR 6 [django.request] [user None] [ip None] log.py:222 - Service Unavailable: /zendesk_proxy/v1
```

In theory, it is possible to disable this page explicitly by setting the `CONTACT_US_PAGE: false` site configuration entry. But I did not observe that setting this site configuration entry changed anything -- I might have had to clear some cache, some further investigation would be needed. In any case, setting site configuration is cumbersome, both for automated and manual installations.

I believe that a proper fix would be to disable Zendesk by default and to enable it only if the `ZENDESK_URL` setting is defined.

**Comment by alfredchavez** [comment]
Hi, I'd like to contribute to this issue, but I have a question, what do you mean by disable Zendesk, remove(hide) that form or  maybe disable the button when `ZENDESK_URL` is not defined?

**Comment by regisb** [comment]
Hi @alfredchavez! Thanks for your proposition. My personal opinion is that /support/contact_us should redirect to /contact when the Zendesk url is not defined. But if you have a better idea then I'm all ears.

**Comment by alfredchavez** [comment]
Hi @regisb, your solution sounds great, I am going to implement it

**Comment by BbrSofiane** [comment]
Hi @alfredchavez, thanks for your contribution!

Can you cherry pick the commit on the lilac.master branch? Once that's merged we can close the issue.

**Comment by alfredchavez** [comment]
Hi @BbrSofiane just checked on it and it seems there is a PR already for it https://github.com/edx/edx-platform/pull/28300
