### ISSUE TITLE
Generating static assets is too slow because of obsolete Webpack version

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#8]
We did a brief study on the Webpack config where BTR-5 reported that uglify plugin is supposed to be used twice and the size of the output is same with or without the plugin.

On further investigation it was found the UglifyJsPlugin is just called on prod build and this plugin is not solely responsible for slowing down the build.

The proposal was also to update `devtool:eval` which can be a faster devtool equivalent. We also arrive at the understanding that the webpack  config used and the version of webpack that is being used is very obsolete. So we should invest time in upgrading webpack and work on the webpack config to support the newer version.

https://openedx.atlassian.net/browse/BTR-5?focusedCommentId=507315

https://openedx.atlassian.net/browse/BTR-60

**Comment by cmltaWt0** [comment]
@BbrSofiane ready to take a ticket

**Comment by NeOneSoft** [comment]
Hi @ghassanmas!! , following the PR's related with this issue seems that almost all the tasks to get a better performance were done.Do we need something else to continue and close this issue?
