### ISSUE TITLE
Add Tutor installation instructions to the official Open edX installation instructions

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#80]
The installation documentation are missing any reference to the installation using tutor.

We need to add:
- [x] A brief description of the situation regarding the move to Tutor as the official native installation
- [x] A brief description of the reasons to use the native installation instead
- [x] Link to the tutor installation instructions

**Comment by regisb** [comment]
We agreed to work on this collaboratively with @arbrandes.

**Comment by arbrandes** [comment]
@regisb (and @nedbat), please take a peek at https://github.com/edx/edx-documentation/pull/1952!
