### ISSUE TITLE
[Tutor] Seek to understand governance needs

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#83]
This issue is meant to both house and track discussion around Tutor governance, picking up where it left off [in the OEP-45, ADR-1 pull request](https://github.com/edx/open-edx-proposals/pull/178#issuecomment-849468947).

The executive summary so far, is:

* @regisb created the [Tutor Maintainers Program](https://discuss.overhang.io/t/the-tutor-maintainer-handbook/1375) in response to inquiries by the community around governance and the future of community involvement in the project, giving members rights and responsibilities above regular users.
* @antoviaque has questioned whether that is sufficient, given that the aforementioned program does not include committer rights.  Xavier believes it would be best if the maintainer's program followed the [Open edX Core Commiters](https://open.edx.org/blog/open-edx-core-committers-program/) model, allowing recognized members commit rights to the main Tutor repository.
* A compromised was reached in that:  1) the [the "Tutor ADR"](https://github.com/edx/open-edx-proposals/pull/178) would be merged in Provisional status, 2) Tutor would be announced as a recommended installation method for Lilac, and 3) the community would continue improving/evaluating Tutor and its governance in the Maple release cycle, and if for some reason it is found to be lacking (either technically or direction-wise), the provisional status could be extended, or in the worst case, the official recommendation removed.  Conversely, if it is _not_ found to be lacking, the Provisional status of the ADR would be changed to Accepted.

**Comment by arbrandes** [comment]
@antoviaque, do you mind assigning yourself?

**Comment by antoviaque** [comment]
@arbrandes Thanks for creating this!

For assigning myself, sounds good - but I don't seem to be able to do that? Here is what I see:
![image](https://user-images.githubusercontent.com/514483/121774889-8e4b7a00-cb52-11eb-8683-daa8a702e79b.png)

@regisb @nasthagiri Are we still planning to do that meeting the 3 of us, now that Lilac is out?

CC @Kelketek who has expressed interest participating in these discussions.

**Comment by nasthagiri** [comment]
Yes, it would be good to connect on this with an in-sync meeting.  We can try the week of the 21st since I'm out most of next week. @antoviaque Could we trouble you with finding a common time? https://calendly.com/nasthagiri

**Comment by antoviaque** [comment]
@nasthagiri Sure! Sorry for the delayed response, a mail filter put the notification at the wrong place.

Looking at your calendar for next week, there are a couple of times on Friday 25th that could work on my side -- either 3:45pm UTC or 4:30pm UTC. @regisb would either of those work for you? I've tentatively booked the first one for now (3:45pm UTC, which is 17:45 French time), but we can move it as needed.

CC @Kelketek if you want to join.

And thanks @BbrSofiane for assigning this to me :) Did I miss anything, or simply the permissions?

**Comment by BbrSofiane** [comment]
@antoviaque I think it's just a permission issue :)

**Comment by regisb** [comment]
> Looking at your calendar for next week, there are a couple of times on Friday 25th that could work on my side -- either 3:45pm UTC or 4:30pm UTC. @regisb would either of those work for you? I've tentatively booked the first one for now (3:45pm UTC, which is 17:45 French time), but we can move it as needed.

Yes, this is fine!

**Comment by nasthagiri** [comment]
Here's the meeting link: https://meet.google.com/ooe-wmoy-xyv?authuser=0

**Comment by antoviaque** [comment]
@regisb @nasthagiri @Kelketek I'm writing a quick recap of the outcome of the meeting while it's fresh in mind - see if it matches your own perception, and don't hesitate to correct me or complete it as needed:

After restating our different viewpoints on the topic of governance and core committers, which matched the previous discussions, one of the main point that came to light is that there is a need for @regisb to earn more money from Tutor, and being the sole author/committer is something you perceive as important to further that goal. While this is something I would disagree on, this is a decision that belongs to @regisb  and the Tutor project. We acknowledged that Tutor currently wants users, maybe with occasional contributions, but not other regular committers, particularly on the core. 

Even though, Tutor still remains a useful project to the Open edX community, and a good step for the project as a whole. It's just that instead of considering Tutor as part of Open edX and trying to contribute to it as core members like we do with the rest of the Open edX project, we can consider that Open edX is going to be more a user of Tutor – like Open edX uses Django or MongoDB for example. Ie, we might still send patches upstream from time to time (like we would do with any upstream project we use), but won't try to join the core.

On the OpenCraft side, we'll still be working on integrating Tutor with our infrastructure, and do contributions in that context - which should still yield plenty of them.

And we are not entirely giving up on the idea : ) If you ever change your mind @regisb I'll be happy to revisit this. With time, once we have collaborated more, with the number of users & core work increasing, we should hopefully develop trust that could help aligning our goals more. 

Thanks for the conversation in any case, it felt very useful to clarify.

**Comment by regisb** [comment]
This sounds about right, thanks for the recap @antoviaque. I'll just clarify a couple things:

> there is a need for @regisb to earn more money from Tutor

To be more precise, right now I'm mostly trying to break even and earn a living wage. I'm not talking about flying my private jet to Tahiti -- although that would be nice. Just buying a new laptop would be a good start.

(fwiw the financials of my company are publicly available on the web)

> being the sole author/committer is something you perceive as important to further that goal

I am far from being the sole author. Plenty of people contribute to Tutor: https://github.com/overhangio/tutor/graphs/contributors

> We acknowledged that Tutor currently wants users, maybe with occasional contributions, but not other regular committers, particularly on the core.

This is not entirely correct. Tutor has more than enough users. What I'd like now is to have more [customers](https://overhang.io/tutor/wizardedition) and [maintainers](https://discuss.overhang.io/t/the-tutor-maintainer-handbook/1375) (including regular contributors). But you're right that I'm not interested in managing extra core committers.

Another point that is missing from this recap is that I'm more than happy to foster a thriving ecosystem of plugins for Tutor. Developers are already working on [codejail](https://github.com/eduNEXT/tutor-contrib-codejail/) or [jupyter](https://github.com/murat-polat/tutor-contrib-jupyter) plugins for Tutor, and I think this is awesome.

I was also happy to hear that OpenCraft will be willing to use and contribute to Tutor, despite not having write access to the repository. Large SaaS providers are power users of Tutor and we have a lot to learn from how you leverage this tool.

**Comment by nasthagiri** [comment]
@antoviaque @regisb Thank you both for recapping our conversation. I appreciate your openness to meeting and seeking to understand the _needs_ of both sides.

Reflecting back on what we heard to ensure we understood each other was a good first step before discussing possible solutions. We were able to learn about 2 different needs seemingly pulling us in different directions:

- creator reputation for financial stability
- displaying trust to activate community contributions.

In [Working in Public](https://www.goodreads.com/en/book/show/54140556-working-in-public), Nadia provides several anecdotes from her research on how _"creator reputation matters almost more than the software being built for certain projects"_. She also describes the differences between [different open source models](https://project-types.github.io/): stadiums (low percentage of contributors compared to users) versus clubs and federations (high contributor growth). These dynamics and constraints can be challenging for sustaining open source projects. We see these coming to life in this discussion about Tutor.

Given this understanding of our underlying needs, to reiterate where I understood we landed:

1. We will distinguish between **Tutor-core** and **Tutor-plugins**.
2. Regis remains the sole **author** of Tutor-core, leveraging his newly minted [Maintainer](https://discuss.overhang.io/t/the-tutor-maintainer-handbook/1375) program.
3. Open edX community members will be **users** of Tutor-core, choosing to contribute fixes upstream or participate in Tutor's Maintainer program.
4. The Open edX community will author and maintain Tutor-plugins, leveraging the [Core Committer](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers) program. These may reside in the openedx GitHub organization and tagged with Open edX named releases.
5. We will see how this goes and be open to revisiting as we learn from practice.

**Comment by Kelketek** [comment]
@regisb I spent some time mulling over our needs and yours, and I think I've come up with an idea that may help you address your needs-- especially in regards to funding your continued work around Tutor. I've spoken with @antoviaque about it, but would like to speak with the two of you to see if this is something you'd be interested in before digging into it further. Could you schedule some time with us using this link? https://calendly.com/opencraft/fox-xavier-45-minute-meeting

**Comment by BbrSofiane** [comment]
https://discuss.overhang.io/t/tep-rethinking-the-tutor-maintainers-program/2724
