### ISSUE TITLE
The native installation should pin MFE versions

### ISSUE THREAD

**Issue by arbrandes** [openedx/build-test-release-wg#90]
### Description

Recently, [a commit](https://github.com/edx/frontend-app-gradebook/commit/15b76edb5dff3cb42043b247fa7dfe67bb31b91f) that likely introduced a backward-incompatible change (if not a bonafide bug!) to the Gradebook MFE and Lilac.master.  Even if the Gradebook is not officially supported for Lilac by the BTR group, we need a way to avoid such upstream changes from breaking the other ones.

A suggested solution is to add the following to the [pre-existing MFE vars on openedx_native.yml](https://github.com/edx/configuration/blob/open-release/lilac.master/playbooks/openedx_native.yml#L11-L13):

```yaml
MFE_DEPLOY_VERSION: {{ OPENEDX_RELEASE }}
```

### Acceptance criteria

* A generic solution (not necessarily the suggested one) is found for all MFEs
* It is tested to work with all group-supported MFEs (Account, Payment, and Ecommerce) by making sure that after a native installation the proper version is checked out)
* A PR to master is merged
* A PR to lilac.master is merged

### Estimated effort

2 hours of a developer experienced with the native installation

### Bounties

N/A

**Comment by BbrSofiane** [comment]
@arbrandes What were the steps to reproduce this issue?

I've run a native installation and all the MFEs are checked out with the correct branch (open-release/lilac.master).

Looking at [edx/configuration/install/native.sh](https://github.com/edx/configuration/blob/open-release/lilac.master/util/install/native.sh#L125), `MFE_DEPLOY_VERSION` is set by the install script.

**Comment by arbrandes** [comment]
@BbrSofiane, excellent catch.  This issue was reported to me by the Opencraft team when deploying via [Ocim](https://github.com/open-craft/opencraft/), and I neglected to check native.sh.  I guess we can close this, then. :)
