### ISSUE TITLE
Latest Chrome 92 blocks popups from iframe, impacting LTI

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#94]
https://openedx.atlassian.net/browse/TNL-8559 (not sure if public)

Learners on the latest Chrome  92.0.4515.107 are blocked from launching LTI in a new window when the LTI allows transfering username and email to a third party. 

Google Chrome blocks the alert message from appearing. 

Javascript console gave "A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked. See https://www.chromestatus.com/feature/5148698084376576 for more details."

The problem seems to MFE only.  

The problem did not occur in legacy learner experience

How to replicate
1. Open Google Chrome
2. Ensure you have the latest Chrome version: Chrome/92.0.4515.107 
3. Go to page https://learning.edx.org/course/course-v1:NYUx+DBMS.3+3T2020/block-v1:NYUx+DBMS.3+3T2020+type@sequential+block@224716e6d2124627a096cfa3954568fe/block-v1:NYUx+DBMS.3+3T2020+type@vertical+block@50673761b1fd4aec8288f30a35071a7f
4. Click on the LTI launcher button " View resource in a new window"
5. No action is happening

@doctoryes is working on fixes for Lilac.

**Comment by BbrSofiane** [comment]
@nedbat does this only happen on the learning MFE?

**Comment by doctoryes** [comment]
@BbrSofiane Correct - only on the learning MFE and only on Chrome 92+. The issue also affects modal dialogs in ORA units, again only learning MFE/Chrome 92+.

**Comment by BbrSofiane** [comment]
Is this a (big) problem for Lilac since we don't support the Learning MFE in that release?

Or is it an easy fix to backport?

**Comment by doctoryes** [comment]
It's an easy fix to backport - and that work is in-progress here:
https://github.com/edx/edx-platform/pull/28321

**Comment by BbrSofiane** [comment]
@doctoryes I see the the PR is merged, can we close this issue?

**Comment by doctoryes** [comment]
The documentation PR has not been reviewed/merged yet. Once that's done, then this issue can be closed.

**Comment by doctoryes** [comment]
Oh - and the documentation PR is here:
https://github.com/edx/edx-documentation/pull/1966
