### ISSUE TITLE
[Tutor] Codejail plugin should be ready for Maple

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#98]

**Comment by ericfab179** [comment]
@BbrSofiane I left here the PRs realted to this work so maybe I can drag more attention to them and you can help me asking for reviews. Thanks.
Tutor plugin: https://github.com/eduNEXT/tutor-contrib-codejail/pull/1
Codejail service: https://github.com/eduNEXT/codejailservice/pull/2
edx-platform: https://github.com/edx/edx-platform/pull/27795

**Comment by regisb** [comment]
Merged! As far as I am concerned we can close this issue.
